// Auto-generated by cs2-universal-dumper. Do not edit.
#![allow(non_upper_case_globals, non_snake_case, dead_code)]

pub mod animationsystem {
    /// rva 0x14F0A0
    pub const Animation__ShouldUpdateSequences: usize = 0x7FFF65EAF0A0;
}

pub mod client {
    /// rva 0x78B480
    pub const AddNametagEntity: usize = 0x7FFF56CBB480;
    /// rva 0xA46B20
    pub const AddStattrakEntity: usize = 0x7FFF56F76B20;
    /// rva 0x8DC410
    pub const AutowallInit: usize = 0x7FFF56E0C410;
    /// rva 0x988DB0
    pub const AutowallTraceData: usize = 0x7FFF56EB8DB0;
    /// rva 0x804ED0
    pub const AutowallTracePos: usize = 0x7FFF56D34ED0;
    /// rva 0x31A3DF
    pub const CAM_ThinkReturn: usize = 0x7FFF5684A3DF;
    /// rva 0xEA7F10
    pub const CAttributeStringFill: usize = 0x7FFF573D7F10;
    /// rva 0x5F8A50
    pub const CAttributeStringInit: usize = 0x7FFF56B28A50;
    /// rva 0x17DBA70
    pub const CBufferStringInit: usize = 0x7FFF57D0BA70;
    /// rva 0xC57CA0
    pub const CCSGOInput__CreateMove: usize = 0x7FFF57187CA0;
    /// rva 0x7C2780
    pub const CCSInventoryManager__EquipItemInLoadout: usize = 0x7FFF56CF2780;
    /// rva 0x7E2CF0
    pub const CCSPlayerController: usize = 0x7FFF56D12CF0;
    /// rva 0x7C43A0
    pub const CCSPlayerInventory__GetItemInLoadout: usize = 0x7FFF56CF43A0;
    /// rva 0xBAC0C0
    pub const CCSPlayerPawn: usize = 0x7FFF570DC0C0;
    /// rva 0x80FD50
    pub const CCSPlayer_BulletServices: usize = 0x7FFF56D3FD50;
    /// rva 0x80BE30
    pub const CCSPlayer_CameraServices: usize = 0x7FFF56D3BE30;
    /// rva 0x8105A0
    pub const CCSPlayer_ItemServices: usize = 0x7FFF56D405A0;
    /// rva 0x838D70
    pub const CCSPlayer_MovementServices: usize = 0x7FFF56D68D70;
    /// rva 0x874A70
    pub const CCSPlayer_WeaponServices: usize = 0x7FFF56DA4A70;
    /// rva 0x1045F00
    pub const CEconItemSchema__GetAttributeDefinitionByName: usize = 0x7FFF57575F00;
    /// rva 0x8B5820
    pub const CEconItemView__GetCustomPaintKitIndex: usize = 0x7FFF56DE5820;
    /// rva 0x27EEC0
    pub const CFogController: usize = 0x7FFF567AEEC0;
    /// rva 0x962AC0
    pub const CGameEntitySystem__OnAddEntity: usize = 0x7FFF56E92AC0;
    /// rva 0x963320
    pub const CGameEntitySystem__OnRemoveEntity: usize = 0x7FFF56E93320;
    /// rva 0x2A3C50
    pub const CPostProcessingVolume: usize = 0x7FFF567D3C50;
    /// rva 0x14E11E0
    pub const CSBaseGunFireData_fn: usize = 0x7FFF57A111E0;
    /// rva 0x205C007
    pub const CSGOInput_resolved: usize = 0x7FFF5858C007;
    /// rva 0xA27EE0
    pub const CSkeletonInstance__SetMeshGroupMask: usize = 0x7FFF56F57EE0;
    /// rva 0x257B80
    pub const CTonemapController2: usize = 0x7FFF56787B80;
    /// rva 0xC12110
    pub const C_AttributeContainer: usize = 0x7FFF57142110;
    /// rva 0x7428E0
    pub const C_CSWeaponBase: usize = 0x7FFF56C728E0;
    /// rva 0x70B950
    pub const C_EconItemView: usize = 0x7FFF56C3B950;
    /// rva 0x207AB0
    pub const CacheParticleEffect: usize = 0x7FFF56737AB0;
    /// rva 0xC780A0
    pub const CalcSpread: usize = 0x7FFF571A80A0;
    /// rva 0x84C3E0
    pub const CalcViewmodel: usize = 0x7FFF56D7C3E0;
    /// rva 0x14C0F10
    pub const CalculateInterpolation: usize = 0x7FFF579F0F10;
    /// rva 0xA05460
    pub const CalculateWorldSpaceBones: usize = 0x7FFF56F35460;
    /// rva 0xDE70C0
    pub const ClearHUDWeaponIcon: usize = 0x7FFF573170C0;
    /// rva 0x23363C0
    pub const ClientMode_ptr: usize = 0x7FFF588663C0;
    /// rva 0x8B9B32
    pub const ConvarGet: usize = 0x7FFF56DE9B32;
    /// rva 0x1509F40
    pub const CreateBaseTypeCache: usize = 0x7FFF57A39F40;
    /// rva 0x15FDCE6
    pub const CreateEntityByClassName: usize = 0x7FFF57B2DCE6;
    /// rva 0x4B1C60
    pub const CreateNewSubtickMoveStep: usize = 0x7FFF569E1C60;
    /// rva 0x981410
    pub const CreateParticleEffect: usize = 0x7FFF56EB1410;
    /// rva 0xFF07D0
    pub const CreateSOSubclassEconItem: usize = 0x7FFF575207D0;
    /// rva 0x940940
    pub const DestroyParticle: usize = 0x7FFF56E70940;
    /// rva 0x35A450
    pub const DispatchEffect: usize = 0x7FFF5688A450;
    /// rva 0x7B1230
    pub const DrawCrosshair: usize = 0x7FFF56CE1230;
    /// rva 0xA61080
    pub const DrawOverHead: usize = 0x7FFF56F91080;
    /// rva 0x85A980
    pub const DrawScopeOverlay: usize = 0x7FFF56D8A980;
    /// rva 0xC74740
    pub const DrawSmokeVertex: usize = 0x7FFF571A4740;
    /// rva 0xDBB188
    pub const FindHudElement: usize = 0x7FFF572EB188;
    /// rva 0xDBD160
    pub const FindHudElement_panorama: usize = 0x7FFF572ED160;
    /// rva 0x1818120
    pub const FindSOCache: usize = 0x7FFF57D48120;
    /// rva 0x10E93C0
    pub const FirstPersonLegs: usize = 0x7FFF576193C0;
    /// rva 0xDA45C0
    pub const FlashOverlay: usize = 0x7FFF572D45C0;
    /// rva 0x9CA520
    pub const ForceButtonsDown: usize = 0x7FFF56EFA520;
    /// rva 0x24C9710
    pub const GameEntitySystemPtr: usize = 0x7FFF589F9710;
    /// rva 0x2323900
    pub const GameRules_ptr: usize = 0x7FFF58853900;
    /// rva 0x2323900
    pub const GetBBox_ptr: usize = 0x7FFF58853900;
    /// rva 0x961A80
    pub const GetBaseEntity: usize = 0x7FFF56E91A80;
    /// rva 0x8C2710
    pub const GetBonePositionByName: usize = 0x7FFF56DF2710;
    /// rva 0x10BC6D0
    pub const GetChatObject: usize = 0x7FFF575EC6D0;
    /// rva 0x102F5D0
    pub const GetClientSystem: usize = 0x7FFF5755F5D0;
    /// rva 0x8B8130
    pub const GetControllerCmd: usize = 0x7FFF56DE8130;
    /// rva 0x379710
    pub const GetEconItemSystem: usize = 0x7FFF568A9710;
    /// rva 0x948D50
    pub const GetEntityHandle: usize = 0x7FFF56E78D50;
    /// rva 0xB08950
    pub const GetGlowColor: usize = 0x7FFF57038950;
    /// rva 0x22B2240
    pub const GetInstanceS: usize = 0x7FFF587E2240;
    /// rva 0x4AAA20
    pub const GetInt2_Event: usize = 0x7FFF569DAA20;
    /// rva 0x7C6A60
    pub const GetInventoryManager: usize = 0x7FFF56CF6A60;
    /// rva 0x8DB5A0
    pub const GetLocalControllerById: usize = 0x7FFF56E0B5A0;
    /// rva 0x169B40
    pub const GetMatrixForView: usize = 0x7FFF56699B40;
    /// rva 0x8B3990
    pub const GetPlayerInterp: usize = 0x7FFF56DE3990;
    /// rva 0x84A010
    pub const GetRemovedAimPunch_E8: usize = 0x7FFF56D7A010;
    /// rva 0x112837
    pub const GetRemovedAimpunch: usize = 0x7FFF56642837;
    /// rva 0x94D9C0
    pub const GetSurfaceData: usize = 0x7FFF56E7D9C0;
    /// rva 0x8B7F30
    pub const GetTickBase: usize = 0x7FFF56DE7F30;
    /// rva 0x8046A0
    pub const GetTraceInfo: usize = 0x7FFF56D346A0;
    /// rva 0x8B81C0
    pub const GetUserCmdManager: usize = 0x7FFF56DE81C0;
    /// rva 0xAD0030
    pub const GetViewAngles: usize = 0x7FFF57000030;
    /// rva 0x796B70
    pub const GetWeaponInAccuracyRecoveryTime: usize = 0x7FFF56CC6B70;
    /// rva 0x20444E8
    pub const GlobalVariables_ptr: usize = 0x7FFF585744E8;
    /// rva 0x81D8A0
    pub const HandleBulletPenetration: usize = 0x7FFF56D4D8A0;
    /// rva 0x1C35F0
    pub const HandleEntityList: usize = 0x7FFF566F35F0;
    /// rva 0x704290
    pub const HandleTeamIntro: usize = 0x7FFF56C34290;
    /// rva 0x10BA150
    pub const HudChatPrintf: usize = 0x7FFF575EA150;
    /// rva 0x32BAD0
    pub const InitFilter: usize = 0x7FFF5685BAD0;
    /// rva 0x83B590
    pub const InitPlayerMovementTraceFilter: usize = 0x7FFF56D6B590;
    /// rva 0x15F5340
    pub const InitTraceInfo: usize = 0x7FFF57B25340;
    /// rva 0xB0A500
    pub const IsGlowing: usize = 0x7FFF5703A500;
    /// rva 0x8CA630
    pub const LevelInit: usize = 0x7FFF56DFA630;
    /// rva 0x916470
    pub const LoadFileForMe: usize = 0x7FFF56E46470;
    /// rva 0x6BB5E0
    pub const LoadPath: usize = 0x7FFF56BEB5E0;
    /// rva 0x8C2710
    pub const LookupBone: usize = 0x7FFF56DF2710;
    /// rva 0x9D4840
    pub const ModulationUpdate: usize = 0x7FFF56F04840;
    /// rva 0xC77780
    pub const NoSpread1: usize = 0x7FFF571A7780;
    /// rva 0x1F4C80
    pub const ParticleCollection: usize = 0x7FFF56724C80;
    /// rva 0x20288E8
    pub const ParticleManager_ptr: usize = 0x7FFF585588E8;
    /// rva 0x8D1840
    pub const PhysicsRunThink_Ctrl: usize = 0x7FFF56E01840;
    /// rva 0xB0E820
    pub const PhysicsRunThink_Pawn: usize = 0x7FFF5703E820;
    /// rva 0x1507DA0
    pub const PlayVSound_client: usize = 0x7FFF57A37DA0;
    /// rva 0x9C8E40
    pub const ProcessImpacts: usize = 0x7FFF56EF8E40;
    /// rva 0x9D3E20
    pub const ProcessMovement: usize = 0x7FFF56F03E20;
    /// rva 0x78C6B0
    pub const RegenerateWeaponSkin: usize = 0x7FFF56CBC6B0;
    /// rva 0x7B1380
    pub const RegenerateWeaponSkins: usize = 0x7FFF56CE1380;
    /// rva 0x602660
    pub const ReportHit: usize = 0x7FFF56B32660;
    /// rva 0x9D5EE0
    pub const RunCommand: usize = 0x7FFF56F05EE0;
    /// rva 0x85A980
    pub const Scope_callsite: usize = 0x7FFF56D8A980;
    /// rva 0x10BA150
    pub const SendChatMessage: usize = 0x7FFF575EA150;
    /// rva 0x21EE40
    pub const SetAbsOrigin_Pawn: usize = 0x7FFF5674EE40;
    /// rva 0xD905A0
    pub const SetBodyGroup_inv: usize = 0x7FFF572C05A0;
    /// rva 0x8009D0
    pub const SetCollisionBounds: usize = 0x7FFF56D309D0;
    /// rva 0xFFDFC0
    pub const SetDynamicAttributeValue: usize = 0x7FFF5752DFC0;
    /// rva 0xFFDFC0
    pub const SetDynamicAttributeValue_raw: usize = 0x7FFF5752DFC0;
    /// rva 0xA27EE0
    pub const SetMeshGroupMask: usize = 0x7FFF56F57EE0;
    /// rva 0x8D56F0
    pub const SetModel: usize = 0x7FFF56E056F0;
    /// rva 0xF16EB0
    pub const SetPlayerReady: usize = 0x7FFF57446EB0;
    /// rva 0x7D3600
    pub const SetTraceData: usize = 0x7FFF56D03600;
    /// rva 0x1813F50
    pub const SetTypeKV3: usize = 0x7FFF57D43F50;
    /// rva 0xADF070
    pub const SetViewAngle: usize = 0x7FFF5700F070;
    /// rva 0x8B5450
    pub const SetupCmd: usize = 0x7FFF56DE5450;
    /// rva 0xD16400
    pub const SetupMove: usize = 0x7FFF57246400;
    /// rva 0x117FD3F
    pub const SetupMovementMoves: usize = 0x7FFF576AFD3F;
    /// rva 0xA51640
    pub const SomeTimingFromPawn: usize = 0x7FFF56F81640;
    /// rva 0x804580
    pub const TestSurfaces: usize = 0x7FFF56D34580;
    /// rva 0xB6B0A0
    pub const TracePlayerBBox: usize = 0x7FFF5709B0A0;
    /// rva 0x988E90
    pub const TraceShape: usize = 0x7FFF56EB8E90;
    /// rva 0x802700
    pub const TraceToExit: usize = 0x7FFF56D32700;
    /// rva 0xF1B040
    pub const UpdatePostProcessing: usize = 0x7FFF5744B040;
    /// rva 0x1FA82B
    pub const UpdateSubClass: usize = 0x7FFF5672A82B;
    /// rva 0x7B03E0
    pub const UpdateTurningInAccuracy: usize = 0x7FFF56CE03E0;
    /// rva 0x2028558
    pub const VPhys2World_ptr: usize = 0x7FFF58558558;
    /// rva 0x23292E8
    pub const ViewRender_ptr: usize = 0x7FFF588592E8;
    /// rva 0xAC64B0
    pub const create_move_v2: usize = 0x7FFF56FF64B0;
    /// rva 0xC74830
    pub const draw_smoke_array: usize = 0x7FFF571A4830;
    /// rva 0x801140
    pub const draw_view_punch_v2: usize = 0x7FFF56D31140;
    /// rva 0x24C9818
    pub const entity_list_ptr: usize = 0x7FFF589F9818;
    /// rva 0xACD0C1
    pub const frame_stage_notify: usize = 0x7FFF56FFD0C1;
    /// rva 0x801140
    pub const get_fov: usize = 0x7FFF56D31140;
    /// rva 0xED6790
    pub const get_map_name: usize = 0x7FFF57406790;
    /// rva 0xACE990
    pub const get_view_angles_v2: usize = 0x7FFF56FFE990;
    /// rva 0x84C3E0
    pub const get_view_model: usize = 0x7FFF56D7C3E0;
    /// rva 0x2323900
    pub const global_vars_v2: usize = 0x7FFF58853900;
    /// rva 0xEF7BC0
    pub const is_demo_or_hltv: usize = 0x7FFF57427BC0;
    /// rva 0xAF4E40
    pub const level_init_v2: usize = 0x7FFF57024E40;
    /// rva 0xAF50C0
    pub const level_shutdown: usize = 0x7FFF570250C0;
    /// rva 0x2302E80
    pub const local_controller: usize = 0x7FFF58832E80;
    /// rva 0x217F60
    pub const mark_interp_latch_flags_dirty: usize = 0x7FFF56747F60;
    /// rva 0x963030
    pub const on_add_entity_v2: usize = 0x7FFF56E93030;
    /// rva 0xC58CF0
    pub const override_view_short: usize = 0x7FFF57188CF0;
    /// rva 0x1056410
    pub const paintkit_prefab: usize = 0x7FFF57586410;
    /// rva 0xEEA5C0
    pub const paintkit_seed: usize = 0x7FFF5741A5C0;
    /// rva 0xEEA5C0
    pub const paintkit_wear: usize = 0x7FFF5741A5C0;
    /// rva 0x22A1928
    pub const planted_c4_ptr: usize = 0x7FFF587D1928;
    /// rva 0x10E93C0
    pub const remove_legs: usize = 0x7FFF576193C0;
    /// rva 0xEEA5C0
    pub const statTrak_killEater: usize = 0x7FFF5741A5C0;
    /// rva 0x11B6E0
    pub const statTrak_scoreType: usize = 0x7FFF5664B6E0;
    /// rva 0x7015A0
    pub const unlock_inventory: usize = 0x7FFF56C315A0;
    /// rva 0xADEAC0
    pub const update_global_vars: usize = 0x7FFF5700EAC0;
    /// rva 0xF1F5F6
    pub const update_post_processing_v2: usize = 0x7FFF5744F5F6;
    /// rva 0x23290D0
    pub const view_matrix_ptr: usize = 0x7FFF588590D0;
}

pub mod engine2 {
    /// rva 0x769D0
    pub const Engine__GetScreenAspectRatio: usize = 0x7FFF9F6169D0;
    /// rva 0x6133F0
    pub const Engine__PVSManager_ptr: usize = 0x7FFF9FBB33F0;
    /// rva 0x66490
    pub const Engine__RunPrediction: usize = 0x7FFF9F606490;
}

pub mod materialsystem2 {
    /// rva 0x11E30
    pub const FindParameter: usize = 0x7FFF89661E30;
    /// rva 0x11BE0
    pub const MatSys__PrepareSceneMaterial: usize = 0x7FFF89661BE0;
    /// rva 0x12370
    pub const UpdateParameter: usize = 0x7FFF89662370;
}

pub mod particles {
    /// rva 0x220B0
    pub const Particles__DrawArray: usize = 0x7FFF60C020B0;
    /// rva 0x3A650
    pub const Particles__FindKeyVar: usize = 0x7FFF60C1A650;
    /// rva 0x9D8D0
    pub const Particles__SetMaterialShaderType: usize = 0x7FFF60C7D8D0;
}

pub mod scenesystem {
    /// rva 0x73520
    pub const CSceneAnimatableObject__GeneratePrimitives: usize = 0x7FFF61433520;
    /// rva 0x55BC0
    pub const DrawObject_legacy: usize = 0x7FFF61415BC0;
    /// rva 0x14FB90
    pub const DrawSkyboxArray: usize = 0x7FFF6150FB90;
    /// rva 0x12CF50
    pub const SceneSystem__DrawAggeregateObject: usize = 0x7FFF614ECF50;
    /// rva 0x7AAC0
    pub const SceneSystem__DrawArrayLight: usize = 0x7FFF6143AAC0;
}

pub mod soundsystem {
    /// rva 0x349820
    pub const SoundSystem__PlayVSound: usize = 0x7FFF654D9820;
    /// rva 0xB0720
    pub const SoundSystem__SomeUtlSymbolFunc: usize = 0x7FFF65240720;
}

pub mod tier0 {
    /// rva 0x129160
    pub const Tier0__LoadKeyValues: usize = 0x7FFFA0029160;
    /// rva 0x53F10
    pub const Tier0__UtlBuffer: usize = 0x7FFF9FF53F10;
}

