//! Multi-language emitters for resolved signatures.
//!
//! We already emit a hand-formatted [`signatures.json`].  This module adds
//! sibling files in the same set of languages the offset pass produces
//! (`.cs`, `.hpp`, `.rs`) so consumers can drop the file straight into
//! their project without writing a converter.
//!
//! Output is intentionally minimal — one constant per signature, named
//! after the signature, valued with the resolved virtual / relative
//! address.  Every emitter dedupes within a single (module, name) pair.

use std::collections::BTreeMap;

use super::SignatureHit;

/// Group resolved signatures by module so each emitter can render them as
/// nested namespaces / modules / classes.
fn grouped<'a>(hits: &'a [SignatureHit]) -> BTreeMap<&'a str, Vec<&'a SignatureHit>> {
    let mut out: BTreeMap<&'a str, Vec<&'a SignatureHit>> = BTreeMap::new();
    for h in hits.iter().filter(|h| h.found) {
        out.entry(h.module.as_str()).or_default().push(h);
    }
    for v in out.values_mut() {
        v.sort_by(|a, b| a.name.cmp(&b.name));
    }
    out
}

fn ident(name: &str) -> String {
    let mut s = String::with_capacity(name.len());
    for c in name.chars() {
        if c.is_ascii_alphanumeric() || c == '_' {
            s.push(c);
        } else {
            s.push('_');
        }
    }
    if s.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) {
        s.insert(0, '_');
    }
    s
}

fn module_ident(module: &str) -> String {
    ident(module.trim_end_matches(".dll"))
}

/// C# `static class` per module under a `Signatures` namespace.
pub fn render_cs(hits: &[SignatureHit]) -> String {
    let mut s = String::new();
    s.push_str("// Auto-generated by cs2-universal-dumper. Do not edit.\n\n");
    s.push_str("namespace CS2Sdk.Signatures;\n\n");
    s.push_str("public static class Signatures\n{\n");
    for (module, items) in grouped(hits) {
        s.push_str(&format!("    public static class {}\n    {{\n", module_ident(module)));
        for h in items {
            if let Some(va) = h.va {
                s.push_str(&format!(
                    "        public const ulong {} = 0x{:X}UL; // rva 0x{:X}\n",
                    ident(&h.name),
                    va,
                    h.rva.unwrap_or(0),
                ));
            }
        }
        s.push_str("    }\n");
    }
    s.push_str("}\n");
    s
}

/// C++ header with one `inline constexpr` per signature, namespaced per
/// module.
pub fn render_hpp(hits: &[SignatureHit]) -> String {
    let mut s = String::new();
    s.push_str("// Auto-generated by cs2-universal-dumper. Do not edit.\n");
    s.push_str("#pragma once\n\n#include <cstdint>\n\n");
    s.push_str("namespace cs2::signatures {\n");
    for (module, items) in grouped(hits) {
        s.push_str(&format!("    namespace {} {{\n", module_ident(module)));
        for h in items {
            if let Some(va) = h.va {
                s.push_str(&format!(
                    "        inline constexpr std::uintptr_t {} = 0x{:X}; // rva 0x{:X}\n",
                    ident(&h.name),
                    va,
                    h.rva.unwrap_or(0),
                ));
            }
        }
        s.push_str("    }\n");
    }
    s.push_str("}\n");
    s
}

/// Rust module per game module, with `pub const` addresses.
pub fn render_rs(hits: &[SignatureHit]) -> String {
    let mut s = String::new();
    s.push_str("// Auto-generated by cs2-universal-dumper. Do not edit.\n");
    s.push_str("#![allow(non_upper_case_globals, non_snake_case, dead_code)]\n\n");
    for (module, items) in grouped(hits) {
        s.push_str(&format!("pub mod {} {{\n", module_ident(module)));
        for h in items {
            if let Some(va) = h.va {
                s.push_str(&format!(
                    "    /// rva 0x{:X}\n    pub const {}: usize = 0x{:X};\n",
                    h.rva.unwrap_or(0),
                    ident(&h.name),
                    va,
                ));
            }
        }
        s.push_str("}\n\n");
    }
    s
}

/// Compact human-readable summary used by `SIGNATURES.md`.
pub fn render_markdown(hits: &[SignatureHit]) -> String {
    let mut s = String::new();
    s.push_str("# CS2 Signatures\n\n");
    s.push_str("_This file is regenerated on every successful run of `cs2-sdk`._\n\n");
    let groups = grouped(hits);
    let total_found = hits.iter().filter(|h| h.found).count();
    let total = hits.len();
    s.push_str(&format!(
        "**{}/{} signatures resolved across {} module(s).**\n\n",
        total_found,
        total,
        groups.len(),
    ));
    for (module, items) in groups {
        s.push_str(&format!("## `{}`\n\n", module));
        s.push_str("| Name | Resolve | VA | RVA | Pattern |\n");
        s.push_str("| --- | --- | --- | --- | --- |\n");
        for h in items {
            s.push_str(&format!(
                "| `{}` | `{}` | `0x{:X}` | `0x{:X}` | `{}` |\n",
                h.name,
                h.resolve,
                h.va.unwrap_or(0),
                h.rva.unwrap_or(0),
                h.pattern.replace('|', "\\|"),
            ));
        }
        s.push('\n');
    }
    s
}
