// Auto-generated by cs2-universal-dumper. Do not edit.
//
// module:        materialsystem2.dll
// classes:       14
// enums:         5
// build_number:  14152
// generated_at:  2026-04-21T22:41:52.146505500+00:00
//
// Use:
//   auto* pawn = reinterpret_cast<C_CSPlayerPawn*>(addr);
//   pawn->m_iHealth() = 100;

#pragma once
#include "cs2sdk_macros.hpp"

namespace cs2::sdk::materialsystem2 {

    inline constexpr std::uint32_t CS2_BUILD = 14152;

    class MaterialParam_t;
    class MaterialParamVector_t;
    class MaterialParamString_t;
    class PostProcessingResource_t;
    class MaterialParamInt_t;
    class PostProcessingVignetteParameters_t;
    class PostProcessingLocalContrastParameters_t;
    class PostProcessingTonemapParameters_t;
    class PostProcessingFogScatteringParameters_t;
    class MaterialParamBuffer_t;
    class MaterialResourceData_t;
    class PostProcessingBloomParameters_t;
    class MaterialParamFloat_t;
    class MaterialParamTexture_t;

    enum class VertJustification_e : std::uint32_t {
        VERT_JUSTIFICATION_TOP = 0x0,
        VERT_JUSTIFICATION_CENTER = 0x1,
        VERT_JUSTIFICATION_BOTTOM = 0x2,
        VERT_JUSTIFICATION_NONE = 0x3,
    };

    enum class LayoutPositionType_e : std::uint32_t {
        LAYOUTPOSITIONTYPE_VIEWPORT_RELATIVE = 0x0,
        LAYOUTPOSITIONTYPE_FRACTIONAL = 0x1,
        LAYOUTPOSITIONTYPE_NONE = 0x2,
    };

    enum class ViewFadeMode_t : std::uint32_t {
        VIEW_FADE_CONSTANT_COLOR = 0x0,
        VIEW_FADE_MODULATE = 0x1,
        VIEW_FADE_MOD2X = 0x2,
    };

    enum class BloomBlendMode_t : std::uint32_t {
        BLOOM_BLEND_ADD = 0x0,
        BLOOM_BLEND_SCREEN = 0x1,
        BLOOM_BLEND_BLUR = 0x2,
    };

    enum class HorizJustification_e : std::uint32_t {
        HORIZ_JUSTIFICATION_LEFT = 0x0,
        HORIZ_JUSTIFICATION_CENTER = 0x1,
        HORIZ_JUSTIFICATION_RIGHT = 0x2,
        HORIZ_JUSTIFICATION_NONE = 0x3,
    };

    // MaterialParam_t
    //   fields: 1
    class MaterialParam_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // MaterialParamVector_t
    //   parent: materialsystem2
    //   fields: 0
    class MaterialParamVector_t : public materialsystem2 {
    public:
    };

    // MaterialParamString_t
    //   parent: materialsystem2
    //   fields: 0
    class MaterialParamString_t : public materialsystem2 {
    public:
    };

    // PostProcessingResource_t
    //   fields: 1
    class PostProcessingResource_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // MaterialParamInt_t
    //   fields: 0
    class MaterialParamInt_t {
    public:
    };

    // PostProcessingVignetteParameters_t
    //   fields: 1
    class PostProcessingVignetteParameters_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // PostProcessingLocalContrastParameters_t
    //   fields: 1
    class PostProcessingLocalContrastParameters_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // PostProcessingTonemapParameters_t
    //   fields: 1
    class PostProcessingTonemapParameters_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // PostProcessingFogScatteringParameters_t
    //   fields: 1
    class PostProcessingFogScatteringParameters_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // MaterialParamBuffer_t
    //   parent: xL��
    //   fields: 0
    class MaterialParamBuffer_t : public xL {
    public:
    };

    // MaterialResourceData_t
    //   fields: 1
    class MaterialResourceData_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // PostProcessingBloomParameters_t
    //   fields: 1
    class PostProcessingBloomParameters_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // MaterialParamFloat_t
    //   fields: 0
    class MaterialParamFloat_t {
    public:
    };

    // MaterialParamTexture_t
    //   fields: 0
    class MaterialParamTexture_t {
    public:
    };

} // namespace cs2::sdk::materialsystem2
