// Auto-generated by cs2-universal-dumper. Do not edit.
//
// module:        panorama.dll
// classes:       0
// enums:         2
// build_number:  14155
// generated_at:  2026-04-25T13:59:50.678472200+00:00
//
// Use:
//   auto* pawn = reinterpret_cast<C_CSPlayerPawn*>(addr);
//   pawn->m_iHealth() = 100;

#pragma once
#include "cs2sdk_macros.hpp"

namespace cs2::sdk::panorama {

    inline constexpr std::uint32_t CS2_BUILD = 14155;


    enum class ELayoutNodeType : std::uint32_t {
        ROOT = 0x0,
        STYLES = 0x1,
        SCRIPT_BODY = 0x2,
        SCRIPTS = 0x3,
        SNIPPETS = 0x4,
        INCLUDE = 0x5,
        SNIPPET = 0x6,
        PANEL = 0x7,
        PANEL_ATTRIBUTE = 0x8,
        PANEL_ATTRIBUTE_VALUE = 0x9,
        REFERENCE_CONTENT = 0xA,
        REFERENCE_COMPILED = 0xB,
        REFERENCE_PASSTHROUGH = 0xC,
    };

    enum class EStyleNodeType : std::uint32_t {
        ROOT = 0x0,
        EXPRESSION = 0x1,
        PROPERTY = 0x2,
        DEFINE = 0x3,
        IMPORT = 0x4,
        KEYFRAMES = 0x5,
        KEYFRAME_SELECTOR = 0x6,
        STYLE_SELECTOR = 0x7,
        WHITESPACE = 0x8,
        EXPRESSION_TEXT = 0x9,
        EXPRESSION_URL = 0xA,
        EXPRESSION_CONCAT = 0xB,
        REFERENCE_CONTENT = 0xC,
        REFERENCE_COMPILED = 0xD,
        REFERENCE_PASSTHROUGH = 0xE,
        REFERENCE_PANEL = 0xF,
        COMPILER_CONDITIONAL = 0x10,
    };

} // namespace cs2::sdk::panorama
