// Auto-generated by cs2-universal-dumper. Do not edit.

namespace CS2Sdk.Signatures;

public static class Signatures
{
    public static class animationsystem
    {
        public const ulong Animation__ShouldUpdateSequences = 0x7FFEEAB2F0A0UL; // rva 0x14F0A0
    }
    public static class client
    {
        public const ulong AddNametagEntity = 0x7FFEDBA4AE20UL; // rva 0x78AE20
        public const ulong AddStattrakEntity = 0x7FFEDBD0AFD0UL; // rva 0xA4AFD0
        public const ulong AutowallInit = 0x7FFEDBBA0860UL; // rva 0x8E0860
        public const ulong AutowallTraceData = 0x7FFEDBC4D200UL; // rva 0x98D200
        public const ulong AutowallTracePos = 0x7FFEDBAC6C20UL; // rva 0x806C20
        public const ulong BulkRegenIterator = 0x7FFEDBA4E321UL; // rva 0x78E321
        public const ulong CAM_ThinkReturn = 0x7FFEDB5DA44FUL; // rva 0x31A44F
        public const ulong CAttributeStringFill = 0x7FFEDC16C510UL; // rva 0xEAC510
        public const ulong CAttributeStringInit = 0x7FFEDB8B8600UL; // rva 0x5F8600
        public const ulong CBodyComponent = 0x7FFEDB47C0B0UL; // rva 0x1BC0B0
        public const ulong CBodyComponentSkeletonInstance = 0x7FFEDB482F90UL; // rva 0x1C2F90
        public const ulong CBufferStringInit = 0x7FFEDCAA0100UL; // rva 0x17E0100
        public const ulong CCSGOInput__CreateMove = 0x7FFEDBF1C240UL; // rva 0xC5C240
        public const ulong CCSGameRules = 0x7FFEDB33E160UL; // rva 0x7E160
        public const ulong CCSGameRulesProxy = 0x7FFEDB9A9450UL; // rva 0x6E9450
        public const ulong CCSInventoryManager__EquipItemInLoadout = 0x7FFEDBA820D0UL; // rva 0x7C20D0
        public const ulong CCSPlayerController = 0x7FFEDBAA4FE0UL; // rva 0x7E4FE0
        public const ulong CCSPlayerController = 0x7FFEDBAA4FE0UL; // rva 0x7E4FE0
        public const ulong CCSPlayerController_ActionTrackingServices = 0x7FFEDBAA4FE0UL; // rva 0x7E4FE0
        public const ulong CCSPlayerController_DamageServices = 0x7FFEDBAA4FE0UL; // rva 0x7E4FE0
        public const ulong CCSPlayerController_InGameMoneyServices = 0x7FFEDBAA4FE0UL; // rva 0x7E4FE0
        public const ulong CCSPlayerController_InventoryServices = 0x7FFEDBAA4FE0UL; // rva 0x7E4FE0
        public const ulong CCSPlayerInventory__GetItemInLoadout = 0x7FFEDBA83CF0UL; // rva 0x7C3CF0
        public const ulong CCSPlayerPawn = 0x7FFEDBE6F680UL; // rva 0xBAF680
        public const ulong CCSPlayer_BulletServices = 0x7FFEDBAD2BE0UL; // rva 0x812BE0
        public const ulong CCSPlayer_BulletServices = 0x7FFEDBAD2BE0UL; // rva 0x812BE0
        public const ulong CCSPlayer_CameraServices = 0x7FFEDBACECF0UL; // rva 0x80ECF0
        public const ulong CCSPlayer_HostageServices = 0x7FFEDBAD2BE0UL; // rva 0x812BE0
        public const ulong CCSPlayer_ItemServices = 0x7FFEDBB0F730UL; // rva 0x84F730
        public const ulong CCSPlayer_MovementServices = 0x7FFEDBAFCB10UL; // rva 0x83CB10
        public const ulong CCSPlayer_MovementServices = 0x7FFEDBAFCB10UL; // rva 0x83CB10
        public const ulong CCSPlayer_PingServices = 0x7FFEDBB10940UL; // rva 0x850940
        public const ulong CCSPlayer_UseServices = 0x7FFEDBB40B50UL; // rva 0x880B50
        public const ulong CCSPlayer_WaterServices = 0x7FFEDBB35DE0UL; // rva 0x875DE0
        public const ulong CCSPlayer_WeaponServices = 0x7FFEDBB36190UL; // rva 0x876190
        public const ulong CCSPlayer_WeaponServices = 0x7FFEDBB36190UL; // rva 0x876190
        public const ulong CCSWeaponBase = 0x7FFEDBA3F260UL; // rva 0x77F260
        public const ulong CCSWeaponBaseGun = 0x7FFEDBA3F300UL; // rva 0x77F300
        public const ulong CCSWeaponBaseVData = 0x7FFEDBA1A170UL; // rva 0x75A170
        public const ulong CCollisionProperty = 0x7FFEDB5A0EE0UL; // rva 0x2E0EE0
        public const ulong CDecoyProjectile = 0x7FFEDBA0E0A0UL; // rva 0x74E0A0
        public const ulong CEconItemSchema__GetAttributeDefinitionByName = 0x7FFEDC30A580UL; // rva 0x104A580
        public const ulong CEconItemView__GetCustomPaintKitIndex = 0x7FFEDBB79C70UL; // rva 0x8B9C70
        public const ulong CFlashbangProjectile = 0x7FFEDC29DAD0UL; // rva 0xFDDAD0
        public const ulong CFogController = 0x7FFEDB53EF20UL; // rva 0x27EF20
        public const ulong CGameEntitySystem__OnAddEntity = 0x7FFEDBC26F10UL; // rva 0x966F10
        public const ulong CGameEntitySystem__OnRemoveEntity = 0x7FFEDBC27770UL; // rva 0x967770
        public const ulong CGameSceneNode = 0x7FFEDB463840UL; // rva 0x1A3840
        public const ulong CGlowProperty = 0x7FFEDB5A10F0UL; // rva 0x2E10F0
        public const ulong CHEGrenadeProjectile = 0x7FFEDC29DB70UL; // rva 0xFDDB70
        public const ulong CInputPtrGlobal = 0x7FFEDD3213C0UL; // rva 0x20613C0
        public const ulong CMolotovProjectile = 0x7FFEDBA0E280UL; // rva 0x74E280
        public const ulong CPostProcessingVolume = 0x7FFEDB563CB0UL; // rva 0x2A3CB0
        public const ulong CSBaseGunFireData_fn = 0x7FFEDC7A5870UL; // rva 0x14E5870
        public const ulong CSGOInput_ptr = 0x7FFEDD3213C0UL; // rva 0x20613C0
        public const ulong CSGOInput_resolved = 0x7FFEDD3213C7UL; // rva 0x20613C7
        public const ulong CSkeletonInstance = 0x7FFEDB463970UL; // rva 0x1A3970
        public const ulong CSkeletonInstance__SetMeshGroupMask = 0x7FFEDBCEC390UL; // rva 0xA2C390
        public const ulong CSmokeGrenadeProjectile = 0x7FFEDBA0E320UL; // rva 0x74E320
        public const ulong CTonemapController2 = 0x7FFEDB517BE0UL; // rva 0x257BE0
        public const ulong C_AttributeContainer = 0x7FFEDBED6580UL; // rva 0xC16580
        public const ulong C_BaseEntity = 0x7FFEDB30E260UL; // rva 0x4E260
        public const ulong C_BaseModelEntity = 0x7FFEDB417F60UL; // rva 0x157F60
        public const ulong C_BasePlayerPawn = 0x7FFEDB32DA20UL; // rva 0x6DA20
        public const ulong C_C4 = 0x7FFEDB35A370UL; // rva 0x9A370
        public const ulong C_CSPlayerPawn = 0x7FFEDB982380UL; // rva 0x6C2380
        public const ulong C_CSPlayerPawnBase = 0x7FFEDBE95760UL; // rva 0xBD5760
        public const ulong C_CSWeaponBase = 0x7FFEDBA02030UL; // rva 0x742030
        public const ulong C_EconItemView = 0x7FFEDB9CB400UL; // rva 0x70B400
        public const ulong C_Hostage = 0x7FFEDB3A73D0UL; // rva 0xE73D0
        public const ulong C_Inferno = 0x7FFEDB3B7390UL; // rva 0xF7390
        public const ulong C_PlantedC4 = 0x7FFEDB3B06F0UL; // rva 0xF06F0
        public const ulong C_SmokeGrenadeProjectile = 0x7FFEDB355960UL; // rva 0x95960
        public const ulong CacheParticleEffect = 0x7FFEDB4C7B10UL; // rva 0x207B10
        public const ulong CalcSpread = 0x7FFEDBF3C690UL; // rva 0xC7C690
        public const ulong CalcViewmodel = 0x7FFEDBB0E060UL; // rva 0x84E060
        public const ulong CalculateInterpolation = 0x7FFEDC7855A0UL; // rva 0x14C55A0
        public const ulong CalculateWorldSpaceBones = 0x7FFEDBCC98B0UL; // rva 0xA098B0
        public const ulong ClearHUDWeaponIcon = 0x7FFEDC0AB6C0UL; // rva 0xDEB6C0
        public const ulong ClientMode_ptr = 0x7FFEDD5FBA60UL; // rva 0x233BA60
        public const ulong ConCommand_firstperson = 0x7FFEDBD88AF0UL; // rva 0xAC8AF0
        public const ulong ConCommand_thirdperson = 0x7FFEDBD88BD0UL; // rva 0xAC8BD0
        public const ulong ConvarGet = 0x7FFEDBB7DF82UL; // rva 0x8BDF82
        public const ulong CreateBaseTypeCache = 0x7FFEDC7CE5D0UL; // rva 0x150E5D0
        public const ulong CreateEntityByClassName = 0x7FFEDC8C2376UL; // rva 0x1602376
        public const ulong CreateNewSubtickMoveStep = 0x7FFEDB771CD0UL; // rva 0x4B1CD0
        public const ulong CreateParticleEffect = 0x7FFEDBC45860UL; // rva 0x985860
        public const ulong CreateSOSubclassEconItem = 0x7FFEDC2B4E50UL; // rva 0xFF4E50
        public const ulong DestroyParticle = 0x7FFEDBC04D90UL; // rva 0x944D90
        public const ulong DispatchEffect = 0x7FFEDB61A4C0UL; // rva 0x35A4C0
        public const ulong DrawCrosshair = 0x7FFEDBA70BA0UL; // rva 0x7B0BA0
        public const ulong DrawOverHead = 0x7FFEDBD25530UL; // rva 0xA65530
        public const ulong DrawScopeOverlay = 0x7FFEDBB1C010UL; // rva 0x85C010
        public const ulong DrawSmokeVertex = 0x7FFEDBF38D30UL; // rva 0xC78D30
        public const ulong FindHudElement = 0x7FFEDC07F788UL; // rva 0xDBF788
        public const ulong FindHudElement_panorama = 0x7FFEDC081760UL; // rva 0xDC1760
        public const ulong FindSOCache = 0x7FFEDCADC7B0UL; // rva 0x181C7B0
        public const ulong FirstPersonLegs = 0x7FFEDC3ADA40UL; // rva 0x10EDA40
        public const ulong FlashOverlay = 0x7FFEDC068BB0UL; // rva 0xDA8BB0
        public const ulong ForceButtonsDown = 0x7FFEDBC8E970UL; // rva 0x9CE970
        public const ulong GameEntitySystemPtr = 0x7FFEDD78ED50UL; // rva 0x24CED50
        public const ulong GameRules_ptr = 0x7FFEDD5E8F38UL; // rva 0x2328F38
        public const ulong GetBBox_ptr = 0x7FFEDD5E8F38UL; // rva 0x2328F38
        public const ulong GetBaseEntity = 0x7FFEDBC25ED0UL; // rva 0x965ED0
        public const ulong GetBonePositionByName = 0x7FFEDBB86B60UL; // rva 0x8C6B60
        public const ulong GetChatObject = 0x7FFEDC380D50UL; // rva 0x10C0D50
        public const ulong GetClientSystem = 0x7FFEDC2F3C50UL; // rva 0x1033C50
        public const ulong GetControllerCmd = 0x7FFEDBB7C580UL; // rva 0x8BC580
        public const ulong GetEconItemSystem = 0x7FFEDB639780UL; // rva 0x379780
        public const ulong GetEntityHandle = 0x7FFEDBC0D1A0UL; // rva 0x94D1A0
        public const ulong GetGlowColor = 0x7FFEDBDC9400UL; // rva 0xB09400
        public const ulong GetInstanceS = 0x7FFEDD5775E0UL; // rva 0x22B75E0
        public const ulong GetInt2_Event = 0x7FFEDB76AA90UL; // rva 0x4AAA90
        public const ulong GetInventoryManager = 0x7FFEDBA863B0UL; // rva 0x7C63B0
        public const ulong GetLocalControllerById = 0x7FFEDBB9F9F0UL; // rva 0x8DF9F0
        public const ulong GetMatrixForView = 0x7FFEDB429BA0UL; // rva 0x169BA0
        public const ulong GetPlayerInterp = 0x7FFEDBB77DE0UL; // rva 0x8B7DE0
        public const ulong GetRemovedAimPunch_E8 = 0x7FFEDBB0C310UL; // rva 0x84C310
        public const ulong GetRemovedAimpunch = 0x7FFEDB3D2897UL; // rva 0x112897
        public const ulong GetSurfaceData = 0x7FFEDBC11E10UL; // rva 0x951E10
        public const ulong GetTickBase = 0x7FFEDBB7C380UL; // rva 0x8BC380
        public const ulong GetTraceInfo = 0x7FFEDBAC63F0UL; // rva 0x8063F0
        public const ulong GetUserCmdManager = 0x7FFEDBB7C610UL; // rva 0x8BC610
        public const ulong GetViewAngles = 0x7FFEDBD944E0UL; // rva 0xAD44E0
        public const ulong GetWeaponInAccuracyRecoveryTime = 0x7FFEDBA56510UL; // rva 0x796510
        public const ulong GlobalVariables_ptr = 0x7FFEDD3096A0UL; // rva 0x20496A0
        public const ulong GloveApply_PerTick = 0x7FFEDBE7FAA0UL; // rva 0xBBFAA0
        public const ulong HandleBulletPenetration = 0x7FFEDBAE0230UL; // rva 0x820230
        public const ulong HandleEntityList = 0x7FFEDB483650UL; // rva 0x1C3650
        public const ulong HandleTeamIntro = 0x7FFEDB9C3E00UL; // rva 0x703E00
        public const ulong HudChatPrintf = 0x7FFEDC37E7D0UL; // rva 0x10BE7D0
        public const ulong InitFilter = 0x7FFEDB5EBB40UL; // rva 0x32BB40
        public const ulong InitPlayerMovementTraceFilter = 0x7FFEDBAFF290UL; // rva 0x83F290
        public const ulong InitTraceInfo = 0x7FFEDC8B99D0UL; // rva 0x15F99D0
        public const ulong IsGlowing = 0x7FFEDBDCAB40UL; // rva 0xB0AB40
        public const ulong LevelInit = 0x7FFEDBB8EA80UL; // rva 0x8CEA80
        public const ulong LoadFileForMe = 0x7FFEDBBDA8C0UL; // rva 0x91A8C0
        public const ulong LoadPath = 0x7FFEDB97B150UL; // rva 0x6BB150
        public const ulong LookupBone = 0x7FFEDBB86B60UL; // rva 0x8C6B60
        public const ulong ModulationUpdate = 0x7FFEDBC98C90UL; // rva 0x9D8C90
        public const ulong NoSpread1 = 0x7FFEDBF3BD70UL; // rva 0xC7BD70
        public const ulong ParticleCollection = 0x7FFEDB4B4CE0UL; // rva 0x1F4CE0
        public const ulong ParticleManager_ptr = 0x7FFEDD2EDAA8UL; // rva 0x202DAA8
        public const ulong PhysicsRunThink_Ctrl = 0x7FFEDBB95C90UL; // rva 0x8D5C90
        public const ulong PhysicsRunThink_Pawn = 0x7FFEDBDCD590UL; // rva 0xB0D590
        public const ulong PlayVSound_client = 0x7FFEDC7CC430UL; // rva 0x150C430
        public const ulong ProcessImpacts = 0x7FFEDBC8D290UL; // rva 0x9CD290
        public const ulong ProcessMovement = 0x7FFEDBC98270UL; // rva 0x9D8270
        public const ulong RegenerateWeaponSkin = 0x7FFEDBA4C050UL; // rva 0x78C050
        public const ulong RegenerateWeaponSkin_v2 = 0x7FFEDBA4C050UL; // rva 0x78C050
        public const ulong RegenerateWeaponSkins = 0x7FFEDBA70CF0UL; // rva 0x7B0CF0
        public const ulong ReportHit = 0x7FFEDB8C21E0UL; // rva 0x6021E0
        public const ulong RunCommand = 0x7FFEDBC9A330UL; // rva 0x9DA330
        public const ulong Scope_callsite = 0x7FFEDBB1C010UL; // rva 0x85C010
        public const ulong SendChatMessage = 0x7FFEDC37E7D0UL; // rva 0x10BE7D0
        public const ulong SetAbsOrigin_Pawn = 0x7FFEDB4DEEA0UL; // rva 0x21EEA0
        public const ulong SetBodyGroup_inv = 0x7FFEDC054B90UL; // rva 0xD94B90
        public const ulong SetCollisionBounds = 0x7FFEDBAC3580UL; // rva 0x803580
        public const ulong SetDynamicAttributeValue = 0x7FFEDC2C2640UL; // rva 0x1002640
        public const ulong SetDynamicAttributeValue_raw = 0x7FFEDC2C2640UL; // rva 0x1002640
        public const ulong SetMeshGroupMask = 0x7FFEDBCEC390UL; // rva 0xA2C390
        public const ulong SetModel = 0x7FFEDBB99B40UL; // rva 0x8D9B40
        public const ulong SetPlayerReady = 0x7FFEDC1DB4B0UL; // rva 0xF1B4B0
        public const ulong SetTraceData = 0x7FFEDBA94790UL; // rva 0x7D4790
        public const ulong SetTypeKV3 = 0x7FFEDCAD85E0UL; // rva 0x18185E0
        public const ulong SetViewAngle = 0x7FFEDBDA3520UL; // rva 0xAE3520
        public const ulong SetupCmd = 0x7FFEDBB798A0UL; // rva 0x8B98A0
        public const ulong SetupMove = 0x7FFEDBFDA9F0UL; // rva 0xD1A9F0
        public const ulong SetupMovementMoves = 0x7FFEDC4443BFUL; // rva 0x11843BF
        public const ulong SomeTimingFromPawn = 0x7FFEDBD15AF0UL; // rva 0xA55AF0
        public const ulong Spawner_PerTickOrchestrator = 0x7FFEDBE82620UL; // rva 0xBC2620
        public const ulong TestSurfaces = 0x7FFEDBAC62D0UL; // rva 0x8062D0
        public const ulong TracePlayerBBox = 0x7FFEDBE2F670UL; // rva 0xB6F670
        public const ulong TraceShape = 0x7FFEDBC4D2E0UL; // rva 0x98D2E0
        public const ulong TraceToExit = 0x7FFEDBAC4440UL; // rva 0x804440
        public const ulong UpdatePostProcessing = 0x7FFEDC1DF640UL; // rva 0xF1F640
        public const ulong UpdateSubClass = 0x7FFEDB4BA88BUL; // rva 0x1FA88B
        public const ulong UpdateTurningInAccuracy = 0x7FFEDBA6FD50UL; // rva 0x7AFD50
        public const ulong VPhys2World_ptr = 0x7FFEDD2ED718UL; // rva 0x202D718
        public const ulong ViewRender_ptr = 0x7FFEDD5EDCB8UL; // rva 0x232DCB8
        public const ulong create_move_v2 = 0x7FFEDBD8A960UL; // rva 0xACA960
        public const ulong draw_smoke_array = 0x7FFEDBF38E20UL; // rva 0xC78E20
        public const ulong draw_view_punch_v2 = 0x7FFEDBAC3D00UL; // rva 0x803D00
        public const ulong entity_list_ptr = 0x7FFEDD78EE58UL; // rva 0x24CEE58
        public const ulong frame_stage_notify = 0x7FFEDBD91571UL; // rva 0xAD1571
        public const ulong get_fov = 0x7FFEDBAC3D00UL; // rva 0x803D00
        public const ulong get_map_name = 0x7FFEDC19AD90UL; // rva 0xEDAD90
        public const ulong get_view_angles_v2 = 0x7FFEDBD92E40UL; // rva 0xAD2E40
        public const ulong get_view_model = 0x7FFEDBB0E060UL; // rva 0x84E060
        public const ulong global_vars_v2 = 0x7FFEDD5E8F38UL; // rva 0x2328F38
        public const ulong is_demo_or_hltv = 0x7FFEDC1BC1C0UL; // rva 0xEFC1C0
        public const ulong level_init_v2 = 0x7FFEDBDB91D0UL; // rva 0xAF91D0
        public const ulong level_shutdown = 0x7FFEDBDB9450UL; // rva 0xAF9450
        public const ulong local_controller = 0x7FFEDD5C8520UL; // rva 0x2308520
        public const ulong mark_interp_latch_flags_dirty = 0x7FFEDB4D7FC0UL; // rva 0x217FC0
        public const ulong on_add_entity_v2 = 0x7FFEDBC27480UL; // rva 0x967480
        public const ulong override_view_short = 0x7FFEDBF1D290UL; // rva 0xC5D290
        public const ulong paintkit_prefab = 0x7FFEDC31AA90UL; // rva 0x105AA90
        public const ulong paintkit_seed = 0x7FFEDC1AEBC0UL; // rva 0xEEEBC0
        public const ulong paintkit_wear = 0x7FFEDC1AEBC0UL; // rva 0xEEEBC0
        public const ulong planted_c4_ptr = 0x7FFEDD566CB8UL; // rva 0x22A6CB8
        public const ulong remove_legs = 0x7FFEDC3ADA40UL; // rva 0x10EDA40
        public const ulong statTrak_killEater = 0x7FFEDC1AEBC0UL; // rva 0xEEEBC0
        public const ulong statTrak_scoreType = 0x7FFEDB3DB740UL; // rva 0x11B740
        public const ulong unlock_inventory = 0x7FFEDB9C1110UL; // rva 0x701110
        public const ulong update_global_vars = 0x7FFEDBDA2F70UL; // rva 0xAE2F70
        public const ulong update_post_processing_v2 = 0x7FFEDC1E3BF6UL; // rva 0xF23BF6
        public const ulong view_matrix_ptr = 0x7FFEDD5EEAC0UL; // rva 0x232EAC0
    }
    public static class engine2
    {
        public const ulong CSplitScreenSlot = 0x7FFF03C6A250UL; // rva 0x24A250
        public const ulong Engine__GetScreenAspectRatio = 0x7FFF03A969D0UL; // rva 0x769D0
        public const ulong Engine__PVSManager_ptr = 0x7FFF040333F0UL; // rva 0x6133F0
        public const ulong Engine__RunPrediction = 0x7FFF03A86490UL; // rva 0x66490
    }
    public static class materialsystem2
    {
        public const ulong FindParameter = 0x7FFF031E1E30UL; // rva 0x11E30
        public const ulong MatSys__PrepareSceneMaterial = 0x7FFF031E1BE0UL; // rva 0x11BE0
        public const ulong UpdateParameter = 0x7FFF031E2370UL; // rva 0x12370
    }
    public static class particles
    {
        public const ulong Particles__DrawArray = 0x7FFEE58820B0UL; // rva 0x220B0
        public const ulong Particles__FindKeyVar = 0x7FFEE589A650UL; // rva 0x3A650
        public const ulong Particles__SetMaterialShaderType = 0x7FFEE58FD8D0UL; // rva 0x9D8D0
    }
    public static class scenesystem
    {
        public const ulong CSceneAnimatableObject__GeneratePrimitives = 0x7FFEE60B3520UL; // rva 0x73520
        public const ulong DrawObject_legacy = 0x7FFEE6095BC0UL; // rva 0x55BC0
        public const ulong DrawSkyboxArray = 0x7FFEE618FB90UL; // rva 0x14FB90
        public const ulong SceneSystem__DrawAggeregateObject = 0x7FFEE616CF50UL; // rva 0x12CF50
        public const ulong SceneSystem__DrawArrayLight = 0x7FFEE60BAAC0UL; // rva 0x7AAC0
    }
    public static class soundsystem
    {
        public const ulong SoundSystem__PlayVSound = 0x7FFEEA159820UL; // rva 0x349820
        public const ulong SoundSystem__SomeUtlSymbolFunc = 0x7FFEE9EC0720UL; // rva 0xB0720
    }
    public static class tier0
    {
        public const ulong Tier0__LoadKeyValues = 0x7FFF065A9160UL; // rva 0x129160
        public const ulong Tier0__UtlBuffer = 0x7FFF064D3F10UL; // rva 0x53F10
    }
}
