// Auto-generated by cs2-universal-dumper. Do not edit.

namespace CS2Sdk.Signatures;

public static class Signatures
{
    public static class animationsystem
    {
        public const ulong Animation__ShouldUpdateSequences = 0x7FFF65EAF0A0UL; // rva 0x14F0A0
    }
    public static class client
    {
        public const ulong AddNametagEntity = 0x7FFF56CBB480UL; // rva 0x78B480
        public const ulong AddStattrakEntity = 0x7FFF56F76B20UL; // rva 0xA46B20
        public const ulong AutowallInit = 0x7FFF56E0C410UL; // rva 0x8DC410
        public const ulong AutowallTraceData = 0x7FFF56EB8DB0UL; // rva 0x988DB0
        public const ulong AutowallTracePos = 0x7FFF56D34ED0UL; // rva 0x804ED0
        public const ulong CAM_ThinkReturn = 0x7FFF5684A3DFUL; // rva 0x31A3DF
        public const ulong CAttributeStringFill = 0x7FFF573D7F10UL; // rva 0xEA7F10
        public const ulong CAttributeStringInit = 0x7FFF56B28A50UL; // rva 0x5F8A50
        public const ulong CBodyComponent = 0x7FFF566EC050UL; // rva 0x1BC050
        public const ulong CBodyComponentSkeletonInstance = 0x7FFF566F2F30UL; // rva 0x1C2F30
        public const ulong CBufferStringInit = 0x7FFF57D0BA70UL; // rva 0x17DBA70
        public const ulong CCSGameRules = 0x7FFF565AE170UL; // rva 0x7E170
        public const ulong CCSGameRulesProxy = 0x7FFF56C198E0UL; // rva 0x6E98E0
        public const ulong CCSInventoryManager__EquipItemInLoadout = 0x7FFF56CF2780UL; // rva 0x7C2780
        public const ulong CCSPlayerController = 0x7FFF56D12CF0UL; // rva 0x7E2CF0
        public const ulong CCSPlayerController = 0x7FFF56D12CF0UL; // rva 0x7E2CF0
        public const ulong CCSPlayerController_ActionTrackingServices = 0x7FFF56D12CF0UL; // rva 0x7E2CF0
        public const ulong CCSPlayerController_DamageServices = 0x7FFF56D12CF0UL; // rva 0x7E2CF0
        public const ulong CCSPlayerController_InGameMoneyServices = 0x7FFF56D12CF0UL; // rva 0x7E2CF0
        public const ulong CCSPlayerController_InventoryServices = 0x7FFF56D12CF0UL; // rva 0x7E2CF0
        public const ulong CCSPlayerInventory__GetItemInLoadout = 0x7FFF56CF43A0UL; // rva 0x7C43A0
        public const ulong CCSPlayerPawn = 0x7FFF570DC0C0UL; // rva 0xBAC0C0
        public const ulong CCSPlayer_BulletServices = 0x7FFF56D3FD50UL; // rva 0x80FD50
        public const ulong CCSPlayer_BulletServices = 0x7FFF56D3FD50UL; // rva 0x80FD50
        public const ulong CCSPlayer_CameraServices = 0x7FFF56D3BE30UL; // rva 0x80BE30
        public const ulong CCSPlayer_HostageServices = 0x7FFF56D3FD50UL; // rva 0x80FD50
        public const ulong CCSPlayer_ItemServices = 0x7FFF56D405A0UL; // rva 0x8105A0
        public const ulong CCSPlayer_MovementServices = 0x7FFF56D68D70UL; // rva 0x838D70
        public const ulong CCSPlayer_MovementServices = 0x7FFF56D68D70UL; // rva 0x838D70
        public const ulong CCSPlayer_PingServices = 0x7FFF56D7E8B0UL; // rva 0x84E8B0
        public const ulong CCSPlayer_UseServices = 0x7FFF56DACF80UL; // rva 0x87CF80
        public const ulong CCSPlayer_WaterServices = 0x7FFF56DA46C0UL; // rva 0x8746C0
        public const ulong CCSPlayer_WeaponServices = 0x7FFF56DA4A70UL; // rva 0x874A70
        public const ulong CCSPlayer_WeaponServices = 0x7FFF56DA4A70UL; // rva 0x874A70
        public const ulong CCSWeaponBase = 0x7FFF56CAF8C0UL; // rva 0x77F8C0
        public const ulong CCSWeaponBaseGun = 0x7FFF56CAF960UL; // rva 0x77F960
        public const ulong CCSWeaponBaseVData = 0x7FFF56C8A7D0UL; // rva 0x75A7D0
        public const ulong CCollisionProperty = 0x7FFF56810E80UL; // rva 0x2E0E80
        public const ulong CDecoyProjectile = 0x7FFF56C7E700UL; // rva 0x74E700
        public const ulong CEconItemSchema__GetAttributeDefinitionByName = 0x7FFF57575F00UL; // rva 0x1045F00
        public const ulong CEconItemView__GetCustomPaintKitIndex = 0x7FFF56DE5820UL; // rva 0x8B5820
        public const ulong CFlashbangProjectile = 0x7FFF575094D0UL; // rva 0xFD94D0
        public const ulong CFogController = 0x7FFF567AEEC0UL; // rva 0x27EEC0
        public const ulong CGameEntitySystem__OnAddEntity = 0x7FFF56E92AC0UL; // rva 0x962AC0
        public const ulong CGameEntitySystem__OnRemoveEntity = 0x7FFF56E93320UL; // rva 0x963320
        public const ulong CGameSceneNode = 0x7FFF566D3810UL; // rva 0x1A3810
        public const ulong CGlowProperty = 0x7FFF56811090UL; // rva 0x2E1090
        public const ulong CHEGrenadeProjectile = 0x7FFF57509570UL; // rva 0xFD9570
        public const ulong CMolotovProjectile = 0x7FFF56C7E8E0UL; // rva 0x74E8E0
        public const ulong CPostProcessingVolume = 0x7FFF567D3C50UL; // rva 0x2A3C50
        public const ulong CSBaseGunFireData_fn = 0x7FFF57A111E0UL; // rva 0x14E11E0
        public const ulong CSGOInput_resolved = 0x7FFF5858C007UL; // rva 0x205C007
        public const ulong CSkeletonInstance = 0x7FFF566D3910UL; // rva 0x1A3910
        public const ulong CSkeletonInstance__SetMeshGroupMask = 0x7FFF56F57EE0UL; // rva 0xA27EE0
        public const ulong CSmokeGrenadeProjectile = 0x7FFF56C7E980UL; // rva 0x74E980
        public const ulong CTonemapController2 = 0x7FFF56787B80UL; // rva 0x257B80
        public const ulong C_AttributeContainer = 0x7FFF57142110UL; // rva 0xC12110
        public const ulong C_BaseEntity = 0x7FFF5657E260UL; // rva 0x4E260
        public const ulong C_BaseModelEntity = 0x7FFF56687EB0UL; // rva 0x157EB0
        public const ulong C_BasePlayerPawn = 0x7FFF5659DA20UL; // rva 0x6DA20
        public const ulong C_C4 = 0x7FFF565CA3C0UL; // rva 0x9A3C0
        public const ulong C_CSPlayerPawn = 0x7FFF56BF2810UL; // rva 0x6C2810
        public const ulong C_CSPlayerPawnBase = 0x7FFF57100BF0UL; // rva 0xBD0BF0
        public const ulong C_CSWeaponBase = 0x7FFF56C728E0UL; // rva 0x7428E0
        public const ulong C_EconItemView = 0x7FFF56C3B950UL; // rva 0x70B950
        public const ulong C_Hostage = 0x7FFF56617370UL; // rva 0xE7370
        public const ulong C_Inferno = 0x7FFF56627330UL; // rva 0xF7330
        public const ulong C_PlantedC4 = 0x7FFF56620690UL; // rva 0xF0690
        public const ulong C_SmokeGrenadeProjectile = 0x7FFF565C59B0UL; // rva 0x959B0
        public const ulong CacheParticleEffect = 0x7FFF56737AB0UL; // rva 0x207AB0
        public const ulong CalcSpread = 0x7FFF571A80A0UL; // rva 0xC780A0
        public const ulong CalcViewmodel = 0x7FFF56D7C3E0UL; // rva 0x84C3E0
        public const ulong CalculateInterpolation = 0x7FFF579F0F10UL; // rva 0x14C0F10
        public const ulong CalculateWorldSpaceBones = 0x7FFF56F35460UL; // rva 0xA05460
        public const ulong ClearHUDWeaponIcon = 0x7FFF573170C0UL; // rva 0xDE70C0
        public const ulong ClientMode_ptr = 0x7FFF588663C0UL; // rva 0x23363C0
        public const ulong ConvarGet = 0x7FFF56DE9B32UL; // rva 0x8B9B32
        public const ulong CreateBaseTypeCache = 0x7FFF57A39F40UL; // rva 0x1509F40
        public const ulong CreateEntityByClassName = 0x7FFF57B2DCE6UL; // rva 0x15FDCE6
        public const ulong CreateNewSubtickMoveStep = 0x7FFF569E1C60UL; // rva 0x4B1C60
        public const ulong CreateParticleEffect = 0x7FFF56EB1410UL; // rva 0x981410
        public const ulong CreateSOSubclassEconItem = 0x7FFF575207D0UL; // rva 0xFF07D0
        public const ulong DestroyParticle = 0x7FFF56E70940UL; // rva 0x940940
        public const ulong DispatchEffect = 0x7FFF5688A450UL; // rva 0x35A450
        public const ulong DrawCrosshair = 0x7FFF56CE1230UL; // rva 0x7B1230
        public const ulong DrawOverHead = 0x7FFF56F91080UL; // rva 0xA61080
        public const ulong DrawScopeOverlay = 0x7FFF56D8A980UL; // rva 0x85A980
        public const ulong DrawSmokeVertex = 0x7FFF571A4740UL; // rva 0xC74740
        public const ulong FindHudElement = 0x7FFF572EB188UL; // rva 0xDBB188
        public const ulong FindHudElement_panorama = 0x7FFF572ED160UL; // rva 0xDBD160
        public const ulong FindSOCache = 0x7FFF57D48120UL; // rva 0x1818120
        public const ulong FirstPersonLegs = 0x7FFF576193C0UL; // rva 0x10E93C0
        public const ulong FlashOverlay = 0x7FFF572D45C0UL; // rva 0xDA45C0
        public const ulong ForceButtonsDown = 0x7FFF56EFA520UL; // rva 0x9CA520
        public const ulong GameEntitySystemPtr = 0x7FFF589F9710UL; // rva 0x24C9710
        public const ulong GameRules_ptr = 0x7FFF58853900UL; // rva 0x2323900
        public const ulong GetBBox_ptr = 0x7FFF58853900UL; // rva 0x2323900
        public const ulong GetBaseEntity = 0x7FFF56E91A80UL; // rva 0x961A80
        public const ulong GetBonePositionByName = 0x7FFF56DF2710UL; // rva 0x8C2710
        public const ulong GetChatObject = 0x7FFF575EC6D0UL; // rva 0x10BC6D0
        public const ulong GetClientSystem = 0x7FFF5755F5D0UL; // rva 0x102F5D0
        public const ulong GetControllerCmd = 0x7FFF56DE8130UL; // rva 0x8B8130
        public const ulong GetEconItemSystem = 0x7FFF568A9710UL; // rva 0x379710
        public const ulong GetEntityHandle = 0x7FFF56E78D50UL; // rva 0x948D50
        public const ulong GetGlowColor = 0x7FFF57038950UL; // rva 0xB08950
        public const ulong GetInstanceS = 0x7FFF587E2240UL; // rva 0x22B2240
        public const ulong GetInt2_Event = 0x7FFF569DAA20UL; // rva 0x4AAA20
        public const ulong GetInventoryManager = 0x7FFF56CF6A60UL; // rva 0x7C6A60
        public const ulong GetLocalControllerById = 0x7FFF56E0B5A0UL; // rva 0x8DB5A0
        public const ulong GetMatrixForView = 0x7FFF56699B40UL; // rva 0x169B40
        public const ulong GetPlayerInterp = 0x7FFF56DE3990UL; // rva 0x8B3990
        public const ulong GetRemovedAimPunch_E8 = 0x7FFF56D7A010UL; // rva 0x84A010
        public const ulong GetRemovedAimpunch = 0x7FFF56642837UL; // rva 0x112837
        public const ulong GetSurfaceData = 0x7FFF56E7D9C0UL; // rva 0x94D9C0
        public const ulong GetTickBase = 0x7FFF56DE7F30UL; // rva 0x8B7F30
        public const ulong GetTraceInfo = 0x7FFF56D346A0UL; // rva 0x8046A0
        public const ulong GetUserCmdManager = 0x7FFF56DE81C0UL; // rva 0x8B81C0
        public const ulong GetViewAngles = 0x7FFF57000030UL; // rva 0xAD0030
        public const ulong GetWeaponInAccuracyRecoveryTime = 0x7FFF56CC6B70UL; // rva 0x796B70
        public const ulong GlobalVariables_ptr = 0x7FFF585744E8UL; // rva 0x20444E8
        public const ulong HandleBulletPenetration = 0x7FFF56D4D8A0UL; // rva 0x81D8A0
        public const ulong HandleEntityList = 0x7FFF566F35F0UL; // rva 0x1C35F0
        public const ulong HandleTeamIntro = 0x7FFF56C34290UL; // rva 0x704290
        public const ulong HudChatPrintf = 0x7FFF575EA150UL; // rva 0x10BA150
        public const ulong InitFilter = 0x7FFF5685BAD0UL; // rva 0x32BAD0
        public const ulong InitPlayerMovementTraceFilter = 0x7FFF56D6B590UL; // rva 0x83B590
        public const ulong InitTraceInfo = 0x7FFF57B25340UL; // rva 0x15F5340
        public const ulong IsGlowing = 0x7FFF5703A500UL; // rva 0xB0A500
        public const ulong LevelInit = 0x7FFF56DFA630UL; // rva 0x8CA630
        public const ulong LoadFileForMe = 0x7FFF56E46470UL; // rva 0x916470
        public const ulong LoadPath = 0x7FFF56BEB5E0UL; // rva 0x6BB5E0
        public const ulong LookupBone = 0x7FFF56DF2710UL; // rva 0x8C2710
        public const ulong ModulationUpdate = 0x7FFF56F04840UL; // rva 0x9D4840
        public const ulong NoSpread1 = 0x7FFF571A7780UL; // rva 0xC77780
        public const ulong ParticleCollection = 0x7FFF56724C80UL; // rva 0x1F4C80
        public const ulong ParticleManager_ptr = 0x7FFF585588E8UL; // rva 0x20288E8
        public const ulong PhysicsRunThink_Ctrl = 0x7FFF56E01840UL; // rva 0x8D1840
        public const ulong PhysicsRunThink_Pawn = 0x7FFF5703E820UL; // rva 0xB0E820
        public const ulong PlayVSound_client = 0x7FFF57A37DA0UL; // rva 0x1507DA0
        public const ulong ProcessImpacts = 0x7FFF56EF8E40UL; // rva 0x9C8E40
        public const ulong ProcessMovement = 0x7FFF56F03E20UL; // rva 0x9D3E20
        public const ulong RegenerateWeaponSkin = 0x7FFF56CBC6B0UL; // rva 0x78C6B0
        public const ulong RegenerateWeaponSkins = 0x7FFF56CE1380UL; // rva 0x7B1380
        public const ulong ReportHit = 0x7FFF56B32660UL; // rva 0x602660
        public const ulong RunCommand = 0x7FFF56F05EE0UL; // rva 0x9D5EE0
        public const ulong Scope_callsite = 0x7FFF56D8A980UL; // rva 0x85A980
        public const ulong SendChatMessage = 0x7FFF575EA150UL; // rva 0x10BA150
        public const ulong SetAbsOrigin_Pawn = 0x7FFF5674EE40UL; // rva 0x21EE40
        public const ulong SetBodyGroup_inv = 0x7FFF572C05A0UL; // rva 0xD905A0
        public const ulong SetCollisionBounds = 0x7FFF56D309D0UL; // rva 0x8009D0
        public const ulong SetDynamicAttributeValue = 0x7FFF5752DFC0UL; // rva 0xFFDFC0
        public const ulong SetDynamicAttributeValue_raw = 0x7FFF5752DFC0UL; // rva 0xFFDFC0
        public const ulong SetMeshGroupMask = 0x7FFF56F57EE0UL; // rva 0xA27EE0
        public const ulong SetModel = 0x7FFF56E056F0UL; // rva 0x8D56F0
        public const ulong SetPlayerReady = 0x7FFF57446EB0UL; // rva 0xF16EB0
        public const ulong SetTraceData = 0x7FFF56D03600UL; // rva 0x7D3600
        public const ulong SetTypeKV3 = 0x7FFF57D43F50UL; // rva 0x1813F50
        public const ulong SetViewAngle = 0x7FFF5700F070UL; // rva 0xADF070
        public const ulong SetupCmd = 0x7FFF56DE5450UL; // rva 0x8B5450
        public const ulong SetupMove = 0x7FFF57246400UL; // rva 0xD16400
        public const ulong SetupMovementMoves = 0x7FFF576AFD3FUL; // rva 0x117FD3F
        public const ulong SomeTimingFromPawn = 0x7FFF56F81640UL; // rva 0xA51640
        public const ulong TestSurfaces = 0x7FFF56D34580UL; // rva 0x804580
        public const ulong TracePlayerBBox = 0x7FFF5709B0A0UL; // rva 0xB6B0A0
        public const ulong TraceShape = 0x7FFF56EB8E90UL; // rva 0x988E90
        public const ulong TraceToExit = 0x7FFF56D32700UL; // rva 0x802700
        public const ulong UpdatePostProcessing = 0x7FFF5744B040UL; // rva 0xF1B040
        public const ulong UpdateSubClass = 0x7FFF5672A82BUL; // rva 0x1FA82B
        public const ulong UpdateTurningInAccuracy = 0x7FFF56CE03E0UL; // rva 0x7B03E0
        public const ulong VPhys2World_ptr = 0x7FFF58558558UL; // rva 0x2028558
        public const ulong ViewRender_ptr = 0x7FFF588592E8UL; // rva 0x23292E8
        public const ulong create_move_v2 = 0x7FFF56FF64B0UL; // rva 0xAC64B0
        public const ulong draw_smoke_array = 0x7FFF571A4830UL; // rva 0xC74830
        public const ulong draw_view_punch_v2 = 0x7FFF56D31140UL; // rva 0x801140
        public const ulong entity_list_ptr = 0x7FFF589F9818UL; // rva 0x24C9818
        public const ulong frame_stage_notify = 0x7FFF56FFD0C1UL; // rva 0xACD0C1
        public const ulong get_fov = 0x7FFF56D31140UL; // rva 0x801140
        public const ulong get_map_name = 0x7FFF57406790UL; // rva 0xED6790
        public const ulong get_view_angles_v2 = 0x7FFF56FFE990UL; // rva 0xACE990
        public const ulong get_view_model = 0x7FFF56D7C3E0UL; // rva 0x84C3E0
        public const ulong global_vars_v2 = 0x7FFF58853900UL; // rva 0x2323900
        public const ulong is_demo_or_hltv = 0x7FFF57427BC0UL; // rva 0xEF7BC0
        public const ulong level_init_v2 = 0x7FFF57024E40UL; // rva 0xAF4E40
        public const ulong level_shutdown = 0x7FFF570250C0UL; // rva 0xAF50C0
        public const ulong local_controller = 0x7FFF58832E80UL; // rva 0x2302E80
        public const ulong mark_interp_latch_flags_dirty = 0x7FFF56747F60UL; // rva 0x217F60
        public const ulong on_add_entity_v2 = 0x7FFF56E93030UL; // rva 0x963030
        public const ulong override_view_short = 0x7FFF57188CF0UL; // rva 0xC58CF0
        public const ulong paintkit_prefab = 0x7FFF57586410UL; // rva 0x1056410
        public const ulong paintkit_seed = 0x7FFF5741A5C0UL; // rva 0xEEA5C0
        public const ulong paintkit_wear = 0x7FFF5741A5C0UL; // rva 0xEEA5C0
        public const ulong planted_c4_ptr = 0x7FFF587D1928UL; // rva 0x22A1928
        public const ulong remove_legs = 0x7FFF576193C0UL; // rva 0x10E93C0
        public const ulong statTrak_killEater = 0x7FFF5741A5C0UL; // rva 0xEEA5C0
        public const ulong statTrak_scoreType = 0x7FFF5664B6E0UL; // rva 0x11B6E0
        public const ulong unlock_inventory = 0x7FFF56C315A0UL; // rva 0x7015A0
        public const ulong update_global_vars = 0x7FFF5700EAC0UL; // rva 0xADEAC0
        public const ulong update_post_processing_v2 = 0x7FFF5744F5F6UL; // rva 0xF1F5F6
        public const ulong view_matrix_ptr = 0x7FFF588590D0UL; // rva 0x23290D0
    }
    public static class engine2
    {
        public const ulong CSplitScreenSlot = 0x7FFF9F7EA250UL; // rva 0x24A250
        public const ulong Engine__GetScreenAspectRatio = 0x7FFF9F6169D0UL; // rva 0x769D0
        public const ulong Engine__PVSManager_ptr = 0x7FFF9FBB33F0UL; // rva 0x6133F0
        public const ulong Engine__RunPrediction = 0x7FFF9F606490UL; // rva 0x66490
    }
    public static class materialsystem2
    {
        public const ulong FindParameter = 0x7FFF89661E30UL; // rva 0x11E30
        public const ulong MatSys__PrepareSceneMaterial = 0x7FFF89661BE0UL; // rva 0x11BE0
        public const ulong UpdateParameter = 0x7FFF89662370UL; // rva 0x12370
    }
    public static class particles
    {
        public const ulong Particles__DrawArray = 0x7FFF60C020B0UL; // rva 0x220B0
        public const ulong Particles__FindKeyVar = 0x7FFF60C1A650UL; // rva 0x3A650
        public const ulong Particles__SetMaterialShaderType = 0x7FFF60C7D8D0UL; // rva 0x9D8D0
    }
    public static class scenesystem
    {
        public const ulong CSceneAnimatableObject__GeneratePrimitives = 0x7FFF61433520UL; // rva 0x73520
        public const ulong DrawObject_legacy = 0x7FFF61415BC0UL; // rva 0x55BC0
        public const ulong SceneSystem__DrawAggeregateObject = 0x7FFF614ECF50UL; // rva 0x12CF50
        public const ulong SceneSystem__DrawArrayLight = 0x7FFF6143AAC0UL; // rva 0x7AAC0
    }
    public static class soundsystem
    {
        public const ulong SoundSystem__PlayVSound = 0x7FFF654D9820UL; // rva 0x349820
        public const ulong SoundSystem__SomeUtlSymbolFunc = 0x7FFF65240720UL; // rva 0xB0720
    }
    public static class tier0
    {
        public const ulong Tier0__LoadKeyValues = 0x7FFFA0029160UL; // rva 0x129160
        public const ulong Tier0__UtlBuffer = 0x7FFF9FF53F10UL; // rva 0x53F10
    }
}
