//! Typed interface accessor stubs.
//!
//! The existing `output::interfaces` emitter writes raw RVAs. This
//! emitter goes one step further and produces *accessor functions* per
//! interface name so consumers can pull a typed pointer out without
//! manually adding the module base every call site.
//!
//! Generated header (excerpt):
//!
//! ```cpp
//! namespace cs2::ifaces {
//!     namespace client_dll {
//!         // Source2Client002 -> client.dll + 0xABCDEF
//!         inline void* Source2Client002(std::uintptr_t base) {
//!             return reinterpret_cast<void*>(base + 0xABCDEF);
//!         }
//!     }
//! }
//! ```
//!
//! Internals already have the module base for each loaded DLL (e.g. via
//! `GetModuleHandleA`), so the `base` parameter keeps the emitter
//! agnostic of how the consumer fetches it.

use std::collections::BTreeMap;
use std::fmt::Write;

use crate::analysis::InterfaceMap;

use super::ident::{slugify, type_ident};

/// Render a C++ header with one inline accessor per interface, grouped
/// by module.
pub fn render_hpp(interfaces: &InterfaceMap, build_number: Option<u32>) -> String {
    let mut s = String::new();
    s.push_str("// Auto-generated by cs2-universal-dumper. Do not edit.\n");
    s.push_str("#pragma once\n\n");
    s.push_str("#include <cstdint>\n\n");
    if let Some(bn) = build_number {
        writeln!(s, "namespace cs2::ifaces {{ inline constexpr std::uint32_t CS2_BUILD = {bn}; }}\n").ok();
    }
    s.push_str("namespace cs2::ifaces {\n\n");
    for (module, ifaces) in interfaces {
        writeln!(s, "    namespace {} {{", slugify(module)).ok();
        let sorted: BTreeMap<&str, &u64> = ifaces
            .iter()
            .map(|(k, v)| (k.as_str(), v as &u64))
            .collect();
        for (name, rva) in sorted {
            writeln!(
                s,
                "        inline void* {ident}(std::uintptr_t module_base) noexcept {{ return reinterpret_cast<void*>(module_base + {rva:#X}); }}",
                ident = type_ident(name),
                rva = rva,
            )
            .ok();
        }
        writeln!(s, "    }} // namespace {}\n", slugify(module)).ok();
    }
    s.push_str("} // namespace cs2::ifaces\n");
    s
}

/// Render the same accessors as a C# static class hierarchy.
pub fn render_cs(interfaces: &InterfaceMap, build_number: Option<u32>) -> String {
    let mut s = String::new();
    s.push_str("// Auto-generated by cs2-universal-dumper. Do not edit.\n");
    s.push_str("namespace CS2Sdk.Interfaces;\n\n");
    s.push_str("public static class Interfaces\n{\n");
    if let Some(bn) = build_number {
        writeln!(s, "    public const uint CS2_BUILD = {bn}u;\n").ok();
    }
    for (module, ifaces) in interfaces {
        writeln!(s, "    public static class {}", slugify(module)).ok();
        writeln!(s, "    {{").ok();
        let sorted: BTreeMap<&str, &u64> = ifaces
            .iter()
            .map(|(k, v)| (k.as_str(), v as &u64))
            .collect();
        for (name, rva) in sorted {
            writeln!(
                s,
                "        public static nint {0}(nint moduleBase) => moduleBase + 0x{1:X};",
                type_ident(name),
                rva,
            )
            .ok();
        }
        writeln!(s, "    }}\n").ok();
    }
    s.push_str("}\n");
    s
}
