// Auto-generated by cs2-universal-dumper. Do not edit.
//
// module:        client.dll
// classes:       534
// enums:         12
// build_number:  14152
// generated_at:  2026-04-21T23:00:33.763106600+00:00
//
// Use:
//   auto* pawn = reinterpret_cast<C_CSPlayerPawn*>(addr);
//   pawn->m_iHealth() = 100;

#pragma once
#include "cs2sdk_macros.hpp"

namespace cs2::sdk::client {

    inline constexpr std::uint32_t CS2_BUILD = 14152;

    class C_CSGO_TeamIntroCharacterPosition;
    class C_FireCrackerBlast;
    class CCSGO_WingmanIntroCounterTerroristPosition;
    class CPulseCell_WaitForCursorsWithTag;
    class C_SceneEntity;
    class CCSPlayer_PingServices;
    class CEconItemAttribute;
    class CBaseTriggerAPI;
    class CFuncRetakeBarrier;
    class C_EnvWindShared;
    class C_SkyCamera;
    class CPulseCell_Base;
    class C_FuncRotating;
    class C_SoundOpvarSetPointBase;
    class C_EnvCubemapFog;
    class C_CSGO_TeamSelectTerroristPosition;
    class C_EnvParticleGlow;
    class CCS_PortraitWorldCallbackHandler;
    class CCSPlayerController_InventoryServices;
    class CCSPlayerModernJump;
    class C_EconEntity;
    class CPulse_ResumePoint;
    class CTriggerFan;
    class C_HostageCarriableProp;
    class C_BulletHitModel;
    class C_FuncElectrifiedVolume;
    class C_MapVetoPickController;
    class C_EnvVolumetricFogVolume;
    class C_CSGO_EndOfMatchCharacterPosition;
    class CPulseCell_PlaySequence;
    class C_BaseEntityAPI;
    class C_BarnLight;
    class CPulseCell_LerpCameraSettings;
    class CPointOffScreenIndicatorUi;
    class CCSObserver_UseServices;
    class C_PostProcessingVolume;
    class CCSPlayer_UseServices;
    class C_BaseModelEntity;
    class C_CSGO_CounterTerroristWingmanIntroCamera;
    class CPulseCell_PickBestOutflowSelector;
    class CInfoFan;
    class C_VoteController;
    class C_C4;
    class C_CSPlayerPawnBase;
    class C_BreakableProp;
    class CCSGO_WingmanIntroTerroristPosition;
    class CPrecipitationVData;
    class C_RetakeGameRules;
    class CPulseCell_WaitForObservable;
    class C_SoundAreaEntitySphere;
    class CPulseCell_Step_EntFire;
    class C_WeaponAWP;
    class C_BaseButton;
    class CCSObserver_ObserverServices;
    class CHitboxComponent;
    class ServerAuthoritativeWeaponSlot_t;
    class C_CSMinimapBoundary;
    class CPathQueryComponent;
    class C_Precipitation;
    class CLogicRelay;
    class SequenceHistory_t;
    class CPlayer_ItemServices;
    class CPulse_OutflowConnection;
    class C_WeaponUMP45;
    class C_WeaponG3SG1;
    class C_SpotlightEnd;
    class C_Fish;
    class C_WeaponFamas;
    class C_EnvVolumetricFogController;
    class CPulseGraphDef;
    class C_EnvDetailController;
    class C_EnvWindVolume;
    class CBasePlayerControllerAPI;
    class CHostageRescueZoneShim;
    class CEnvSoundscapeAlias_snd_soundscape;
    class CCSPlayer_HostageServices;
    class C_GameRulesProxy;
    class CRenderComponent;
    class C_Team;
    class C_PathParticleRopeAlias_path_particle_rope_clientside;
    class CPointChildModifier;
    class CCSPlayerLegacyJump;
    class C_WeaponNOVA;
    class C_DEagle;
    class C_CS2HudModelAddon;
    class C_TriggerMultiple;
    class C_CSGO_TeamPreviewCamera;
    class C_ColorCorrectionVolume;
    class CPlayer_MovementServices;
    class CInfoDynamicShadowHintBox;
    class CBaseAnimGraphController;
    class C_ColorCorrection;
    class AnimGraph2SerializedPoseRecipeSlot_t;
    class CBuoyancyHelper;
    class C_PhysBox;
    class CCSPlayer_CameraServices;
    class CFilterMultiple;
    class CPulseCell_FireCursors;
    class CEnvSoundscape;
    class C_SoundEventEntityAlias_snd_event_point;
    class C_FogController;
    class C_SoundOpvarSetOBBWindEntity;
    class C_MolotovGrenade;
    class C_NetTestBaseCombatCharacter;
    class CBodyComponentPoint;
    class C_WeaponM4A1Silencer;
    class C_EconItemView;
    class CPulseCell_Timeline;
    class CPulseCell_IntervalTimer;
    class CPulseCell_BaseRequirement;
    class CPulseCell_BaseState;
    class OutflowWithRequirements_t;
    class CPulseCell_IsRequirementValid;
    class C_SoundEventPathCornerEntity;
    class C_InfoVisibilityBox;
    class CCSPlayer_ItemServices;
    class CPulseCell_Value_Gradient;
    class IntervalTimer;
    class audioparams_t;
    class C_PathParticleRope;
    class C_DecoyProjectile;
    class C_AttributeContainer;
    class C_CSWeaponBase;
    class CTimeline;
    class CPulseCursorFuncs;
    class C_TonemapController2;
    class CountdownTimer;
    class PulseNodeDynamicOutflows_t;
    class C_WeaponMag7;
    class WeaponPurchaseCount_t;
    class CBasePulseGraphInstance;
    class FilterHealth;
    class C_PointClientUIHUD;
    class CPulseCell_Inflow_GraphHook;
    class SignatureOutflow_Resume;
    class CPathSimpleAPI;
    class C_InfoLadderDismount;
    class C_PointCommentaryNode;
    class CSpriteOriented;
    class shard_model_desc_t;
    class C_KeychainModule;
    class CFuncWater;
    class CCSPlayer_GlowServices;
    class CCSGameModeRules;
    class C_Flashbang;
    class C_PointClientUIWorldTextPanel;
    class CCSPlayer_WaterServices;
    class C_CSObserverPawn;
    class ViewAngleServerChange_t;
    class C_FuncLadder;
    class C_WeaponMP5SD;
    class C_World;
    class C_CSGO_TeamSelectCounterTerroristPosition;
    class C_WeaponGalilAR;
    class CCSPlayerBase_CameraServices;
    class C_TeamplayRules;
    class CPulseCell_Inflow_BaseEntrypoint;
    class C_WeaponSG556;
    class C_CSPlayerPawn;
    class C_CSGO_TeamIntroTerroristPosition;
    class CPulseCell_WaitForCursorsWithTagBase;
    class C_Hostage;
    class C_fogplayerparams_t;
    class CGameSceneNode;
    class CPlayer_ObserverServices;
    class CCashStack;
    class C_SoundAreaEntityBase;
    class C_PlayerVisibility;
    class CAttributeManager;
    class C_BasePlayerWeapon;
    class CRagdollManager;
    class C_HEGrenade;
    class C_EnvSky;
    class CPulse_InvokeBinding;
    class C_EnvWindController;
    class C_GameRules;
    class C_WeaponMAC10;
    class C_CSGO_MapPreviewCameraPath;
    class C_PointWorldText;
    class C_RopeKeyframe;
    class C_BaseToggle;
    class C_EnvCubemapBox;
    class C_EnvCombinedLightProbeVolumeAlias_func_combined_light_probe_volume;
    class C_RopeKeyframe;
    class CInfoDynamicShadowHint;
    class CPathNode;
    class C_FuncMoveLinear;
    class CServerOnlyModelEntity;
    class C_CSGO_TeamSelectCamera;
    class CPulseCell_IntervalTimer;
    class C_WeaponXM1014;
    class C_WorldModelGloves;
    class C_PhysicsPropMultiplayer;
    class C_SoundEventOBBEntity;
    class CPulseTestScriptLib;
    class CPulseCell_BaseLerp;
    class C_WeaponAug;
    class C_BasePropDoor;
    class CChoreoInfoTarget;
    class CTakeDamageResultAPI;
    class CNetworkedSequenceOperation;
    class C_Item_Healthshot;
    class CEntityInstance;
    class C_BaseModelEntity;
    class CCSPlayer_BulletServices;
    class C_SoundOpvarSetAutoRoomEntity;
    class C_EnvCombinedLightProbeVolume;
    class CCSGO_EndOfMatchLineupEnd;
    class C_MultiplayRules;
    class CPlayer_AutoaimServices;
    class C_LightDirectionalEntity;
    class C_BaseEntity;
    class ActiveModelConfig_t;
    class C_WeaponSSG08;
    class CPulseCell_Value_Curve;
    class C_Chicken;
    class C_BasePlayerPawn;
    class C_SoundOpvarSetAABBEntity;
    class C_WeaponBizon;
    class C_StattrakModule;
    class CCSObserver_CameraServices;
    class CEnvSoundscapeProxy;
    class C_SoundEventEntity;
    class CPulseCell_Inflow_EventHandler;
    class C_LightOrthoEntity;
    class CPulseCell_BaseFlow;
    class CBombTarget;
    class C_Knife;
    class C_CSGO_TerroristWingmanIntroCamera;
    class CSkeletonInstance;
    class CEntityComponent;
    class C_ItemDogtags;
    class C_LateUpdatedAnimating;
    class CPulseCell_Outflow_CycleShuffled;
    class CPulseCell_BaseLerp;
    class CPulseAnimFuncs;
    class C_BaseClientUIEntity;
    class CPulseCell_WaitForCursorsWithTagBase;
    class CPulseArraylib;
    class C_WeaponUSPSilencer;
    class C_MolotovProjectile;
    class C_TriggerLerpObject;
    class CPointTemplateAPI;
    class C_WeaponRevolver;
    class C_WeaponElite;
    class C_DynamicPropAlias_cable_dynamic;
    class CBaseProp;
    class CInfoOffscreenPanoramaTexture;
    class CCSWeaponBaseVData;
    class CAttributeManager;
    class SignatureOutflow_Continue;
    class CInfoTarget;
    class CPlayer_CameraServices;
    class CPulseCell_Timeline;
    class CPulseCell_Inflow_EntOutputHandler;
    class C_BaseCSGrenade;
    class CScenePayloadVData;
    class CFilterAttributeInt;
    class CPointTemplate;
    class CPlayer_FlashlightServices;
    class CCSPlayerController;
    class C_CSGO_TeamIntroCounterTerroristPosition;
    class C_CSGO_PreviewModel;
    class C_CSGO_TeamSelectCharacterPosition;
    class CPulseCell_Outflow_CycleOrdered;
    class C_SoundEventAABBEntity;
    class CCSPlayer_MovementServices;
    class SellbackPurchaseEntry_t;
    class C_TintController;
    class C_WeaponBaseItem;
    class CWaterSplasher;
    class C_FuncBrush;
    class PhysicsRagdollPose_t;
    class CPropDataComponent;
    class CPulseCell_LimitCount;
    class C_WeaponCZ75a;
    class C_DynamicLight;
    class CCS2PawnGraphController;
    class EngineCountdownTimer;
    class C_SoundEventSphereEntity;
    class CCSPlayerController_DamageServices;
    class C_CSGO_TeamPreviewModel;
    class C_TonemapController2Alias_env_tonemap_controller2;
    class C_Inferno;
    class CFilterLOS;
    class CPointOrient;
    class C_GlobalLight;
    class C_EnvWindClientside;
    class sky3dparams_t;
    class C_FlashbangProjectile;
    class C_SoundEventConeEntity;
    class CDestructiblePartsComponent;
    class C_WeaponP90;
    class C_EnvWind;
    class C_CSGO_TerroristTeamIntroCamera;
    class CPulseCell_Step_DebugLog;
    class CCSPlayerController_ActionTrackingServices;
    class CBodyComponentBaseAnimGraph;
    class C_CSGO_PreviewModelAlias_csgo_item_previewmodel;
    class C_InfoInstructorHintHostageRescueZone;
    class CPulseCell_BaseYieldingInflow;
    class PulseNodeDynamicOutflows_t;
    class C_TriggerBuoyancy;
    class CPlayer_MovementServices_Humanoid;
    class CPulseCell_IsRequirementValid;
    class C_WeaponTec9;
    class C_PhysPropClientside;
    class C_BaseDoor;
    class CSMatchStats_t;
    class EntityRenderAttribute_t;
    class CPulseCell_Inflow_ObservableVariableListener;
    class CFilterMultipleAPI;
    class CHostageRescueZone;
    class CModelState;
    class CPulseCell_LerpCameraSettings;
    class CPulseCell_Outflow_CycleOrdered;
    class C_CSWeaponBaseGun;
    class C_CSGameRulesProxy;
    class CCollisionProperty;
    class C_WeaponP250;
    class C_ShatterGlassShardPhysics;
    class CFilterMassGreater;
    class C_EntityDissolve;
    class C_SoundOpvarSetOBBEntity;
    class CCSGameModeRules_ArmsRace;
    class C_FuncMonitor;
    class C_ClientRagdoll;
    class PulseSelectorOutflowList_t;
    class CPulseCell_PlaySequence;
    class CBodyComponentSkeletonInstance;
    class C_CS2WeaponModuleBase;
    class C_CSGO_TeamPreviewCharacterPosition;
    class C_SmokeGrenadeProjectile;
    class CScriptComponent;
    class CCSPlayer_BuyServices;
    class C_PortraitWorldCallbackHandler;
    class C_DynamicProp;
    class C_CSTeam;
    class C_CS2HudModelWeapon;
    class C_TextureBasedAnimatable;
    class C_LightEnvironmentEntity;
    class DestructiblePartDamageRequestAPI;
    class CLogicRelayAPI;
    class C_TriggerPhysics;
    class C_PropDoorRotating;
    class C_HandleTest;
    class CInfoWorldLayer;
    class CBodyComponentBaseModelEntity;
    class C_Multimeter;
    class C_BaseTrigger;
    class FilterDamageType;
    class CAttributeList;
    class CPulseCell_Inflow_Wait;
    class CFilterProximity;
    class CCS2WeaponGraphController;
    class CEffectData;
    class C_ParticleSystem;
    class CPulseCell_Outflow_CycleShuffled;
    class C_WeaponSCAR20;
    class C_FuncMover;
    class CCSPlayerController_InventoryServices;
    class CLightComponent;
    class C_DecoyGrenade;
    class C_WaterBullet;
    class CCSPlayer_ActionTrackingServices;
    class C_EnvCubemap;
    class CCSObserver_MovementServices;
    class CBodyComponent;
    class CPulseCell_Inflow_Method;
    class C_BaseCombatCharacter;
    class CGlowProperty;
    class C_PointClientUIDialog;
    class CPulseCell_BaseValue;
    class C_WeaponHKP2000;
    class C_FootstepControl;
    class CCitadelSoundOpvarSetOBB;
    class C_CSGO_EndOfMatchLineupStart;
    class CPlayer_WaterServices;
    class CPulseCell_BooleanSwitchState;
    class CDamageRecord;
    class VPhysicsCollisionAttribute_t;
    class C_DynamicPropAlias_dynamic_prop;
    class CEnvSoundscapeProxyAlias_snd_soundscape_proxy;
    class C_OmniLight;
    class C_SceneEntity;
    class CPulseCell_Inflow_Yield;
    class CPulseMathlib;
    class C_NametagModule;
    class C_EconEntity;
    class CPlayer_UseServices;
    class C_PointValueRemapper;
    class CGameSceneNodeHandle;
    class CPulseCell_Unknown;
    class C_WeaponMP7;
    class CSPerRoundStats_t;
    class CPulseCell_Outflow_CycleRandom;
    class CPulseCell_Step_PublicOutput;
    class C_CS2HudModelBase;
    class C_CSGameRules;
    class CGrenadeTracer;
    class CCSGameModeRules_Noop;
    class CPulse_BlackboardReference;
    class C_BaseCSGrenadeProjectile;
    class C_GradientFog;
    class CCSPlayerController_InGameMoneyServices;
    class C_HEGrenadeProjectile;
    class CFilterModel;
    class C_SoundAreaEntityOrientedBox;
    class C_SoundOpvarSetPointEntity;
    class CPulseGameBlackboard;
    class CChoreoComponent;
    class CPulseCell_Value_RandomInt;
    class C_CSWeaponBaseShotgun;
    class C_RagdollPropAttached;
    class C_ModelPointEntity;
    class C_CSGO_PreviewPlayer;
    class C_RectLight;
    class CPathSimple;
    class C_FuncTrackTrain;
    class C_EconWearable;
    class C_EnvDecal;
    class EntitySpottedState_t;
    class fogparams_t;
    class C_WeaponM4A1;
    class C_Item;
    class C_CSPetPlacement;
    class C_Beam;
    class C_EnvLightProbeVolume;
    class CExplosionTypeData;
    class C_FuncConveyor;
    class CCSPlayer_WeaponServices;
    class C_PhysMagnet;
    class CEnvSoundscapeTriggerableAlias_snd_soundscape_triggerable;
    class C_Breakable;
    class C_PlantedC4;
    class CCSGO_WingmanIntroCharacterPosition;
    class CFilterName;
    class C_RagdollProp;
    class CPulse_CallInfo;
    class C_MapPreviewParticleSystem;
    class CBaseAnimGraph;
    class CPulseCell_InlineNodeSkipSelector;
    class C_LightEntity;
    class C_WeaponM249;
    class C_LocalTempEntity;
    class C_WeaponTaser;
    class C_PointEntity;
    class C_SingleplayRules;
    class CLogicalEntity;
    class C_PrecipitationBlocker;
    class C_CSGO_CounterTerroristTeamIntroCamera;
    class C_SoundOpvarSetPathCornerEntity;
    class CPlayer_WeaponServices;
    class C_WeaponNegev;
    class C_WeaponFiveSeven;
    class C_WeaponSawedoff;
    class C_TriggerVolume;
    class CPulseCell_LimitCount;
    class CPulseCell_Step_CallExternalMethod;
    class C_WeaponMP9;
    class C_DynamicPropAlias_prop_dynamic_override;
    class CEnvSoundscapeTriggerable;
    class C_PlayerPing;
    class C_AK47;
    class C_CSGO_MapPreviewCameraPathNode;
    class C_CSPlayerResource;
    class CSkyboxReference;
    class C_IncendiaryGrenade;
    class CFilterClass;
    class C_PointCameraVFOV;
    class C_PointCamera;
    class CPathWithDynamicNodes;
    class CBaseFilter;
    class WeaponPurchaseTracker_t;
    class PulseObservableBoolExpression_t;
    class CMapInfo;
    class C_CSGO_EndOfMatchCamera;
    class C_BaseGrenade;
    class C_PlayerSprayDecal;
    class CEntityIdentity;
    class CPulseCell_LimitCount;
    class C_CS2HudModelArms;
    class CBasePlayerVData;
    class C_LightSpotEntity;
    class CCSGameModeRules_Deathmatch;
    class CPulseCell_CursorQueue;
    class CPulseCell_Value_RandomFloat;
    class CPulseExecCursor;
    class C_Sprite;
    class C_CsmFovOverride;
    class C_WeaponGlock;
    class C_PhysicsProp;
    class CFilterTeam;
    class CBasePlayerWeaponVData;
    class CInfoInteraction;
    class C_SmokeGrenade;
    class C_CSGO_PreviewPlayerAlias_csgo_player_previewmodel;
    class CInfoParticleTarget;
    class CCSPlayer_DamageReactServices;
    class C_PointClientUIWorldPanel;
    class C_EntityFlame;
    class CBasePlayerController;
    class C_CSGO_EndOfMatchLineupEndpoint;
    class GeneratedTextureHandle_t;
    class CompositeMaterialInputContainer_t;
    class CompositeMaterialAssemblyProcedure_t;
    class CompositeMaterialInputLooseVariable_t;
    class screenshake_t;
    class CCS2UIPawnGraphController;
    class inv_image_light_barn_t;
    class inv_image_map_t;
    class inv_image_light_fill_t;
    class CInterpolatedValue;
    class inv_image_item_t;
    class TimedEvent;
    class CFlashlightEffect;
    class inv_image_camera_t;
    class CInventoryImageData;
    class inv_image_clearcolor_t;
    class C_CommandContext;
    class CompositeMaterialEditorPoint_t;
    class CPlayerSprayDecalRenderHelper;
    class C_IronSightController;
    class CompMatMutatorCondition_t;
    class inv_image_data_t;
    class CompMatPropertyMutator_t;
    class CCompositeMaterialEditorDoc;
    class CClientAlphaProperty;
    class screenfade_t;
    class CGlobalLightBase;
    class IClientAlphaProperty;
    class inv_image_light_sun_t;
    class CompositeMaterialMatchFilter_t;
    class CompositeMaterial_t;

    enum class C_BaseCombatCharacter : std::uint32_t {
        WATER_WAKE_NONE = 0x0,
        WATER_WAKE_IDLE = 0x1,
        WATER_WAKE_WALKING = 0x2,
        WATER_WAKE_RUNNING = 0x3,
        WATER_WAKE_WATER_OVERHEAD = 0x4,
    };

    enum class PulseBestOutflowRules_t : std::uint32_t {
        SORT_BY_NUMBER_OF_VALID_CRITERIA = 0x0,
        SORT_BY_OUTFLOW_INDEX = 0x1,
    };

    enum class PulseCursorCancelPriority_t : std::uint32_t {
        None = 0x0,
        CancelOnSucceeded = 0x1,
        SoftCancel = 0x2,
        HardCancel = 0x3,
    };

    enum class PulseMethodCallMode_t : std::uint32_t {
        SYNC_WAIT_FOR_COMPLETION = 0x0,
        ASYNC_FIRE_AND_FORGET = 0x1,
    };

    enum class CompositeMaterialInputLooseVariableType_t : std::uint32_t {
        LOOSE_VARIABLE_TYPE_BOOLEAN = 0x0,
        LOOSE_VARIABLE_TYPE_INTEGER1 = 0x1,
        LOOSE_VARIABLE_TYPE_INTEGER2 = 0x2,
        LOOSE_VARIABLE_TYPE_INTEGER3 = 0x3,
        LOOSE_VARIABLE_TYPE_INTEGER4 = 0x4,
        LOOSE_VARIABLE_TYPE_FLOAT1 = 0x5,
        LOOSE_VARIABLE_TYPE_FLOAT2 = 0x6,
        LOOSE_VARIABLE_TYPE_FLOAT3 = 0x7,
        LOOSE_VARIABLE_TYPE_FLOAT4 = 0x8,
        LOOSE_VARIABLE_TYPE_COLOR4 = 0x9,
        LOOSE_VARIABLE_TYPE_STRING = 0xA,
        LOOSE_VARIABLE_TYPE_SYSTEMVAR = 0xB,
        LOOSE_VARIABLE_TYPE_RESOURCE_MATERIAL = 0xC,
        LOOSE_VARIABLE_TYPE_RESOURCE_TEXTURE = 0xD,
        LOOSE_VARIABLE_TYPE_PANORAMA_RENDER = 0xE,
    };

    enum class CompositeMaterialInputTextureType_t : std::uint32_t {
        INPUT_TEXTURE_TYPE_DEFAULT = 0x0,
        INPUT_TEXTURE_TYPE_NORMALMAP = 0x1,
        INPUT_TEXTURE_TYPE_COLOR = 0x2,
        INPUT_TEXTURE_TYPE_MASKS = 0x3,
        INPUT_TEXTURE_TYPE_ROUGHNESS = 0x4,
        INPUT_TEXTURE_TYPE_PEARLESCENCE_MASK = 0x5,
        INPUT_TEXTURE_TYPE_AO = 0x6,
        INPUT_TEXTURE_TYPE_POSITION = 0x7,
    };

    enum class InventoryNodeType_t : std::uint32_t {
        NODE_TYPE_INVALID = 0x0,
        VIRTUAL_NODE_SCHEMA_PREFAB = 0x1,
        VIRTUAL_NODE_SCHEMA_ITEMDEF = 0x2,
        VIRTUAL_NODE_SCHEMA_STICKER = 0x3,
        VIRTUAL_NODE_SCHEMA_KEYCHAIN = 0x4,
        CONCRETE_NODE_SCHEMA_PREFAB = 0x5,
        CONCRETE_NODE_SCHEMA_ITEMDEF = 0x6,
        CONCRETE_NODE_SCHEMA_STICKER = 0x7,
        CONCRETE_NODE_SCHEMA_KEYCHAIN = 0x8,
    };

    enum class CompositeMaterialInputContainerSourceType_t : std::uint32_t {
        CONTAINER_SOURCE_TYPE_TARGET_MATERIAL = 0x0,
        CONTAINER_SOURCE_TYPE_MATERIAL_FROM_TARGET_ATTR = 0x1,
        CONTAINER_SOURCE_TYPE_SPECIFIC_MATERIAL = 0x2,
        CONTAINER_SOURCE_TYPE_LOOSE_VARIABLES = 0x3,
        CONTAINER_SOURCE_TYPE_VARIABLE_FROM_TARGET_ATTR = 0x4,
        CONTAINER_SOURCE_TYPE_TARGET_INSTANCE_MATERIAL = 0x5,
    };

    enum class CompMatPropertyMutatorType_t : std::uint32_t {
        COMP_MAT_PROPERTY_MUTATOR_INIT = 0x0,
        COMP_MAT_PROPERTY_MUTATOR_COPY_MATCHING_KEYS = 0x1,
        COMP_MAT_PROPERTY_MUTATOR_COPY_KEYS_WITH_SUFFIX = 0x2,
        COMP_MAT_PROPERTY_MUTATOR_COPY_PROPERTY = 0x3,
        COMP_MAT_PROPERTY_MUTATOR_SET_VALUE = 0x4,
        COMP_MAT_PROPERTY_MUTATOR_GENERATE_TEXTURE = 0x5,
        COMP_MAT_PROPERTY_MUTATOR_CONDITIONAL_MUTATORS = 0x6,
        COMP_MAT_PROPERTY_MUTATOR_POP_INPUT_QUEUE = 0x7,
        COMP_MAT_PROPERTY_MUTATOR_DRAW_TEXT = 0x8,
        COMP_MAT_PROPERTY_MUTATOR_RANDOM_ROLL_INPUT_VARIABLES = 0x9,
    };

    enum class CompositeMaterialVarSystemVar_t : std::uint32_t {
        COMPMATSYSVAR_COMPOSITETIME = 0x0,
        COMPMATSYSVAR_EMPTY_RESOURCE_SPACER = 0x1,
    };

    enum class CompositeMaterialMatchFilterType_t : std::uint32_t {
        MATCH_FILTER_MATERIAL_ATTRIBUTE_EXISTS = 0x0,
        MATCH_FILTER_MATERIAL_SHADER = 0x1,
        MATCH_FILTER_MATERIAL_NAME_SUBSTR = 0x2,
        MATCH_FILTER_MATERIAL_ATTRIBUTE_EQUALS = 0x3,
        MATCH_FILTER_MATERIAL_PROPERTY_EXISTS = 0x4,
        MATCH_FILTER_MATERIAL_PROPERTY_EQUALS = 0x5,
    };

    enum class CompMatPropertyMutatorConditionType_t : std::uint32_t {
        COMP_MAT_MUTATOR_CONDITION_INPUT_CONTAINER_EXISTS = 0x0,
        COMP_MAT_MUTATOR_CONDITION_INPUT_CONTAINER_VALUE_EXISTS = 0x1,
        COMP_MAT_MUTATOR_CONDITION_INPUT_CONTAINER_VALUE_EQUALS = 0x2,
    };

    // C_CSGO_TeamIntroCharacterPosition
    //   fields: 0
    class C_CSGO_TeamIntroCharacterPosition {
    public:
    };

    // C_FireCrackerBlast
    //   fields: 0
    class C_FireCrackerBlast {
    public:
    };

    // CCSGO_WingmanIntroCounterTerroristPosition
    //   fields: 0
    class CCSGO_WingmanIntroCounterTerroristPosition {
    public:
    };

    // CPulseCell_WaitForCursorsWithTag
    //   fields: 0
    class CPulseCell_WaitForCursorsWithTag {
    public:
    };

    // C_SceneEntity::QueuedEvents_t
    //   fields: 0
    class C_SceneEntity {
    public:
    };

    // CCSPlayer_PingServices
    //   parent: xL��
    //   fields: 0
    class CCSPlayer_PingServices : public xL {
    public:
    };

    // CEconItemAttribute
    //   fields: 0
    class CEconItemAttribute {
    public:
    };

    // CBaseTriggerAPI
    //   fields: 0
    class CBaseTriggerAPI {
    public:
    };

    // CFuncRetakeBarrier
    //   parent: xL��
    //   fields: 0
    class CFuncRetakeBarrier : public xL {
    public:
    };

    // C_EnvWindShared
    //   fields: 0
    class C_EnvWindShared {
    public:
    };

    // C_SkyCamera
    //   parent: 
    //   fields: 0
    class C_SkyCamera : public anonymous {
    public:
    };

    // CPulseCell_Base
    //   fields: 1
    class CPulseCell_Base {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // C_FuncRotating
    //   parent: 
    //   fields: 0
    class C_FuncRotating : public anonymous {
    public:
    };

    // C_SoundOpvarSetPointBase
    //   parent: xL��
    //   fields: 0
    class C_SoundOpvarSetPointBase : public xL {
    public:
    };

    // C_EnvCubemapFog
    //   fields: 0
    class C_EnvCubemapFog {
    public:
    };

    // C_CSGO_TeamSelectTerroristPosition
    //   parent: client
    //   fields: 0
    class C_CSGO_TeamSelectTerroristPosition : public client {
    public:
    };

    // C_EnvParticleGlow
    //   fields: 0
    class C_EnvParticleGlow {
    public:
    };

    // CCS_PortraitWorldCallbackHandler
    //   fields: 0
    class CCS_PortraitWorldCallbackHandler {
    public:
    };

    // CCSPlayerController_InventoryServices
    //   fields: 0
    class CCSPlayerController_InventoryServices {
    public:
    };

    // CCSPlayerModernJump
    //   fields: 0
    class CCSPlayerModernJump {
    public:
    };

    // C_EconEntity::AttachedModelData_t
    //   fields: 0
    class C_EconEntity {
    public:
    };

    // CPulse_ResumePoint
    //   fields: 0
    class CPulse_ResumePoint {
    public:
    };

    // CTriggerFan
    //   fields: 0
    class CTriggerFan {
    public:
    };

    // C_HostageCarriableProp
    //   fields: 0
    class C_HostageCarriableProp {
    public:
    };

    // C_BulletHitModel
    //   fields: 0
    class C_BulletHitModel {
    public:
    };

    // C_FuncElectrifiedVolume
    //   fields: 0
    class C_FuncElectrifiedVolume {
    public:
    };

    // C_MapVetoPickController
    //   fields: 0
    class C_MapVetoPickController {
    public:
    };

    // C_EnvVolumetricFogVolume
    //   fields: 0
    class C_EnvVolumetricFogVolume {
    public:
    };

    // C_CSGO_EndOfMatchCharacterPosition
    //   fields: 0
    class C_CSGO_EndOfMatchCharacterPosition {
    public:
    };

    // CPulseCell_PlaySequence
    //   fields: 0
    class CPulseCell_PlaySequence {
    public:
    };

    // C_BaseEntityAPI
    //   fields: 0
    class C_BaseEntityAPI {
    public:
    };

    // C_BarnLight
    //   fields: 0
    class C_BarnLight {
    public:
    };

    // CPulseCell_LerpCameraSettings
    //   parent: client
    //   fields: 0
    class CPulseCell_LerpCameraSettings : public client {
    public:
    };

    // CPointOffScreenIndicatorUi
    //   fields: 0
    class CPointOffScreenIndicatorUi {
    public:
    };

    // CCSObserver_UseServices
    //   fields: 0
    class CCSObserver_UseServices {
    public:
    };

    // C_PostProcessingVolume
    //   fields: 0
    class C_PostProcessingVolume {
    public:
    };

    // CCSPlayer_UseServices
    //   fields: 0
    class CCSPlayer_UseServices {
    public:
    };

    // C_BaseModelEntity::Emphasized_Phoneme
    //   fields: 0
    class C_BaseModelEntity {
    public:
    };

    // C_CSGO_CounterTerroristWingmanIntroCamera
    //   fields: 0
    class C_CSGO_CounterTerroristWingmanIntroCamera {
    public:
    };

    // CPulseCell_PickBestOutflowSelector
    //   fields: 0
    class CPulseCell_PickBestOutflowSelector {
    public:
    };

    // CInfoFan
    //   fields: 0
    class CInfoFan {
    public:
    };

    // C_VoteController
    //   parent: client
    //   fields: 0
    class C_VoteController : public client {
    public:
    };

    // C_C4
    //   parent: xL��
    //   fields: 0
    class C_C4 : public xL {
    public:
    };

    // C_CSPlayerPawnBase
    //   fields: 0
    class C_CSPlayerPawnBase {
    public:
    };

    // C_BreakableProp
    //   fields: 0
    class C_BreakableProp {
    public:
    };

    // CCSGO_WingmanIntroTerroristPosition
    //   fields: 0
    class CCSGO_WingmanIntroTerroristPosition {
    public:
    };

    // CPrecipitationVData
    //   parent: MNotSaved
    //   fields: 0
    class CPrecipitationVData : public MNotSaved {
    public:
    };

    // C_RetakeGameRules
    //   fields: 0
    class C_RetakeGameRules {
    public:
    };

    // CPulseCell_WaitForObservable
    //   fields: 0
    class CPulseCell_WaitForObservable {
    public:
    };

    // C_SoundAreaEntitySphere
    //   fields: 0
    class C_SoundAreaEntitySphere {
    public:
    };

    // CPulseCell_Step_EntFire
    //   parent: client
    //   fields: 0
    class CPulseCell_Step_EntFire : public client {
    public:
    };

    // C_WeaponAWP
    //   fields: 0
    class C_WeaponAWP {
    public:
    };

    // C_BaseButton
    //   parent: ��QX�
    //   fields: 0
    class C_BaseButton : public anonymous {
    public:
    };

    // CCSObserver_ObserverServices
    //   fields: 0
    class CCSObserver_ObserverServices {
    public:
    };

    // CHitboxComponent
    //   parent: client
    //   fields: 0
    class CHitboxComponent : public client {
    public:
    };

    // ServerAuthoritativeWeaponSlot_t
    //   fields: 0
    class ServerAuthoritativeWeaponSlot_t {
    public:
    };

    // C_CSMinimapBoundary
    //   fields: 0
    class C_CSMinimapBoundary {
    public:
    };

    // CPathQueryComponent
    //   parent: server
    //   fields: 0
    class CPathQueryComponent : public server {
    public:
    };

    // C_Precipitation
    //   parent: client
    //   fields: 0
    class C_Precipitation : public client {
    public:
    };

    // CLogicRelay
    //   fields: 0
    class CLogicRelay {
    public:
    };

    // SequenceHistory_t
    //   fields: 0
    class SequenceHistory_t {
    public:
    };

    // CPlayer_ItemServices
    //   fields: 0
    class CPlayer_ItemServices {
    public:
    };

    // CPulse_OutflowConnection
    //   fields: 0
    class CPulse_OutflowConnection {
    public:
    };

    // C_WeaponUMP45
    //   fields: 0
    class C_WeaponUMP45 {
    public:
    };

    // C_WeaponG3SG1
    //   fields: 0
    class C_WeaponG3SG1 {
    public:
    };

    // C_SpotlightEnd
    //   fields: 0
    class C_SpotlightEnd {
    public:
    };

    // C_Fish
    //   fields: 0
    class C_Fish {
    public:
    };

    // C_WeaponFamas
    //   fields: 0
    class C_WeaponFamas {
    public:
    };

    // C_EnvVolumetricFogController
    //   fields: 0
    class C_EnvVolumetricFogController {
    public:
    };

    // CPulseGraphDef
    //   fields: 1
    class CPulseGraphDef {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // C_EnvDetailController
    //   fields: 0
    class C_EnvDetailController {
    public:
    };

    // C_EnvWindVolume
    //   fields: 0
    class C_EnvWindVolume {
    public:
    };

    // CBasePlayerControllerAPI
    //   fields: 0
    class CBasePlayerControllerAPI {
    public:
    };

    // CHostageRescueZoneShim
    //   fields: 0
    class CHostageRescueZoneShim {
    public:
    };

    // CEnvSoundscapeAlias_snd_soundscape
    //   parent: client
    //   fields: 0
    class CEnvSoundscapeAlias_snd_soundscape : public client {
    public:
    };

    // CCSPlayer_HostageServices
    //   fields: 0
    class CCSPlayer_HostageServices {
    public:
    };

    // C_GameRulesProxy
    //   fields: 0
    class C_GameRulesProxy {
    public:
    };

    // CRenderComponent
    //   fields: 0
    class CRenderComponent {
    public:
    };

    // C_Team
    //   fields: 0
    class C_Team {
    public:
    };

    // C_PathParticleRopeAlias_path_particle_rope_clientside
    //   fields: 0
    class C_PathParticleRopeAlias_path_particle_rope_clientside {
    public:
    };

    // CPointChildModifier
    //   fields: 0
    class CPointChildModifier {
    public:
    };

    // CCSPlayerLegacyJump
    //   fields: 0
    class CCSPlayerLegacyJump {
    public:
    };

    // C_WeaponNOVA
    //   fields: 0
    class C_WeaponNOVA {
    public:
    };

    // C_DEagle
    //   fields: 0
    class C_DEagle {
    public:
    };

    // C_CS2HudModelAddon
    //   fields: 0
    class C_CS2HudModelAddon {
    public:
    };

    // C_TriggerMultiple
    //   fields: 0
    class C_TriggerMultiple {
    public:
    };

    // C_CSGO_TeamPreviewCamera
    //   fields: 0
    class C_CSGO_TeamPreviewCamera {
    public:
    };

    // C_ColorCorrectionVolume
    //   fields: 0
    class C_ColorCorrectionVolume {
    public:
    };

    // CPlayer_MovementServices
    //   fields: 0
    class CPlayer_MovementServices {
    public:
    };

    // CInfoDynamicShadowHintBox
    //   fields: 0
    class CInfoDynamicShadowHintBox {
    public:
    };

    // CBaseAnimGraphController
    //   fields: 0
    class CBaseAnimGraphController {
    public:
    };

    // C_ColorCorrection
    //   fields: 0
    class C_ColorCorrection {
    public:
    };

    // AnimGraph2SerializedPoseRecipeSlot_t
    //   fields: 0
    class AnimGraph2SerializedPoseRecipeSlot_t {
    public:
    };

    // CBuoyancyHelper
    //   fields: 0
    class CBuoyancyHelper {
    public:
    };

    // C_PhysBox
    //   parent: MGetKV3ClassDefaults
    //   fields: 0
    class C_PhysBox : public MGetKV3ClassDefaults {
    public:
    };

    // CCSPlayer_CameraServices
    //   fields: 0
    class CCSPlayer_CameraServices {
    public:
    };

    // CFilterMultiple
    //   fields: 0
    class CFilterMultiple {
    public:
    };

    // CPulseCell_FireCursors
    //   fields: 0
    class CPulseCell_FireCursors {
    public:
    };

    // CEnvSoundscape
    //   fields: 0
    class CEnvSoundscape {
    public:
    };

    // C_SoundEventEntityAlias_snd_event_point
    //   fields: 0
    class C_SoundEventEntityAlias_snd_event_point {
    public:
    };

    // C_FogController
    //   parent: MGetKV3ClassDefaults
    //   fields: 0
    class C_FogController : public MGetKV3ClassDefaults {
    public:
    };

    // C_SoundOpvarSetOBBWindEntity
    //   fields: 0
    class C_SoundOpvarSetOBBWindEntity {
    public:
    };

    // C_MolotovGrenade
    //   fields: 0
    class C_MolotovGrenade {
    public:
    };

    // C_NetTestBaseCombatCharacter
    //   parent: client
    //   fields: 0
    class C_NetTestBaseCombatCharacter : public client {
    public:
    };

    // CBodyComponentPoint
    //   fields: 0
    class CBodyComponentPoint {
    public:
    };

    // C_WeaponM4A1Silencer
    //   fields: 0
    class C_WeaponM4A1Silencer {
    public:
    };

    // C_EconItemView
    //   parent: 
    //   fields: 0
    class C_EconItemView : public anonymous {
    public:
    };

    // CPulseCell_Timeline::TimelineEvent_t
    //   fields: 1
    class CPulseCell_Timeline {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CPulseCell_IntervalTimer::CursorState_t
    //   fields: 1
    class CPulseCell_IntervalTimer {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CPulseCell_BaseRequirement
    //   parent: pulse_runtime_lib
    //   fields: 0
    class CPulseCell_BaseRequirement : public pulse_runtime_lib {
    public:
    };

    // CPulseCell_BaseState
    //   fields: 0
    class CPulseCell_BaseState {
    public:
    };

    // OutflowWithRequirements_t
    //   fields: 1
    class OutflowWithRequirements_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CPulseCell_IsRequirementValid
    //   parent: pulse_runtime_lib
    //   fields: 0
    class CPulseCell_IsRequirementValid : public pulse_runtime_lib {
    public:
    };

    // C_SoundEventPathCornerEntity
    //   fields: 0
    class C_SoundEventPathCornerEntity {
    public:
    };

    // C_InfoVisibilityBox
    //   fields: 0
    class C_InfoVisibilityBox {
    public:
    };

    // CCSPlayer_ItemServices
    //   fields: 0
    class CCSPlayer_ItemServices {
    public:
    };

    // CPulseCell_Value_Gradient
    //   parent: pulse_runtime_lib
    //   fields: 0
    class CPulseCell_Value_Gradient : public pulse_runtime_lib {
    public:
    };

    // IntervalTimer
    //   fields: 0
    class IntervalTimer {
    public:
    };

    // audioparams_t
    //   fields: 0
    class audioparams_t {
    public:
    };

    // C_PathParticleRope
    //   fields: 0
    class C_PathParticleRope {
    public:
    };

    // C_DecoyProjectile
    //   fields: 0
    class C_DecoyProjectile {
    public:
    };

    // C_AttributeContainer
    //   fields: 0
    class C_AttributeContainer {
    public:
    };

    // C_CSWeaponBase
    //   parent: client
    //   fields: 0
    class C_CSWeaponBase : public client {
    public:
    };

    // CTimeline
    //   parent: �@RX�
    //   fields: 0
    class CTimeline : public anonymous {
    public:
    };

    // CPulseCursorFuncs
    //   fields: 0
    class CPulseCursorFuncs {
    public:
    };

    // C_TonemapController2
    //   fields: 0
    class C_TonemapController2 {
    public:
    };

    // CountdownTimer
    //   fields: 1
    class CountdownTimer {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // PulseNodeDynamicOutflows_t::DynamicOutflow_t
    //   fields: 1
    class PulseNodeDynamicOutflows_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // C_WeaponMag7
    //   fields: 0
    class C_WeaponMag7 {
    public:
    };

    // WeaponPurchaseCount_t
    //   fields: 0
    class WeaponPurchaseCount_t {
    public:
    };

    // CBasePulseGraphInstance
    //   fields: 0
    class CBasePulseGraphInstance {
    public:
    };

    // FilterHealth
    //   fields: 0
    class FilterHealth {
    public:
    };

    // C_PointClientUIHUD
    //   fields: 0
    class C_PointClientUIHUD {
    public:
    };

    // CPulseCell_Inflow_GraphHook
    //   parent: pulse_runtime_lib
    //   fields: 0
    class CPulseCell_Inflow_GraphHook : public pulse_runtime_lib {
    public:
    };

    // SignatureOutflow_Resume
    //   fields: 0
    class SignatureOutflow_Resume {
    public:
    };

    // CPathSimpleAPI
    //   fields: 0
    class CPathSimpleAPI {
    public:
    };

    // C_InfoLadderDismount
    //   fields: 0
    class C_InfoLadderDismount {
    public:
    };

    // C_PointCommentaryNode
    //   fields: 0
    class C_PointCommentaryNode {
    public:
    };

    // CSpriteOriented
    //   fields: 0
    class CSpriteOriented {
    public:
    };

    // shard_model_desc_t
    //   fields: 0
    class shard_model_desc_t {
    public:
    };

    // C_KeychainModule
    //   fields: 0
    class C_KeychainModule {
    public:
    };

    // CFuncWater
    //   fields: 0
    class CFuncWater {
    public:
    };

    // CCSPlayer_GlowServices
    //   parent: client
    //   fields: 0
    class CCSPlayer_GlowServices : public client {
    public:
    };

    // CCSGameModeRules
    //   fields: 1
    class CCSGameModeRules {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // C_Flashbang
    //   parent: WPN_ANIMSTATE_UNINITIALIZED
    //   fields: 0
    class C_Flashbang : public WPN_ANIMSTATE_UNINITIALIZED {
    public:
    };

    // C_PointClientUIWorldTextPanel
    //   fields: 0
    class C_PointClientUIWorldTextPanel {
    public:
    };

    // CCSPlayer_WaterServices
    //   fields: 0
    class CCSPlayer_WaterServices {
    public:
    };

    // C_CSObserverPawn
    //   parent: client
    //   fields: 0
    class C_CSObserverPawn : public client {
    public:
    };

    // ViewAngleServerChange_t
    //   fields: 0
    class ViewAngleServerChange_t {
    public:
    };

    // C_FuncLadder
    //   fields: 0
    class C_FuncLadder {
    public:
    };

    // C_WeaponMP5SD
    //   fields: 0
    class C_WeaponMP5SD {
    public:
    };

    // C_World
    //   fields: 0
    class C_World {
    public:
    };

    // C_CSGO_TeamSelectCounterTerroristPosition
    //   parent: server
    //   fields: 0
    class C_CSGO_TeamSelectCounterTerroristPosition : public server {
    public:
    };

    // C_WeaponGalilAR
    //   fields: 0
    class C_WeaponGalilAR {
    public:
    };

    // CCSPlayerBase_CameraServices
    //   fields: 0
    class CCSPlayerBase_CameraServices {
    public:
    };

    // C_TeamplayRules
    //   fields: 0
    class C_TeamplayRules {
    public:
    };

    // CPulseCell_Inflow_BaseEntrypoint
    //   fields: 0
    class CPulseCell_Inflow_BaseEntrypoint {
    public:
    };

    // C_WeaponSG556
    //   fields: 0
    class C_WeaponSG556 {
    public:
    };

    // C_CSPlayerPawn
    //   parent: 
    //   fields: 0
    class C_CSPlayerPawn : public anonymous {
    public:
    };

    // C_CSGO_TeamIntroTerroristPosition
    //   fields: 0
    class C_CSGO_TeamIntroTerroristPosition {
    public:
    };

    // CPulseCell_WaitForCursorsWithTagBase
    //   fields: 0
    class CPulseCell_WaitForCursorsWithTagBase {
    public:
    };

    // C_Hostage
    //   fields: 0
    class C_Hostage {
    public:
    };

    // C_fogplayerparams_t
    //   fields: 0
    class C_fogplayerparams_t {
    public:
    };

    // CGameSceneNode
    //   fields: 0
    class CGameSceneNode {
    public:
    };

    // CPlayer_ObserverServices
    //   fields: 0
    class CPlayer_ObserverServices {
    public:
    };

    // CCashStack
    //   fields: 0
    class CCashStack {
    public:
    };

    // C_SoundAreaEntityBase
    //   fields: 0
    class C_SoundAreaEntityBase {
    public:
    };

    // C_PlayerVisibility
    //   fields: 0
    class C_PlayerVisibility {
    public:
    };

    // CAttributeManager::cached_attribute_float_t
    //   fields: 0
    class CAttributeManager {
    public:
    };

    // C_BasePlayerWeapon
    //   fields: 0
    class C_BasePlayerWeapon {
    public:
    };

    // CRagdollManager
    //   fields: 0
    class CRagdollManager {
    public:
    };

    // C_HEGrenade
    //   parent: client
    //   fields: 0
    class C_HEGrenade : public client {
    public:
    };

    // C_EnvSky
    //   fields: 0
    class C_EnvSky {
    public:
    };

    // CPulse_InvokeBinding
    //   fields: 1
    class CPulse_InvokeBinding {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // C_EnvWindController
    //   fields: 0
    class C_EnvWindController {
    public:
    };

    // C_GameRules
    //   fields: 0
    class C_GameRules {
    public:
    };

    // C_WeaponMAC10
    //   fields: 0
    class C_WeaponMAC10 {
    public:
    };

    // C_CSGO_MapPreviewCameraPath
    //   fields: 0
    class C_CSGO_MapPreviewCameraPath {
    public:
    };

    // C_PointWorldText
    //   fields: 0
    class C_PointWorldText {
    public:
    };

    // C_RopeKeyframe
    //   parent: client
    //   fields: 0
    class C_RopeKeyframe : public client {
    public:
    };

    // C_BaseToggle
    //   parent: xL��
    //   fields: 0
    class C_BaseToggle : public xL {
    public:
    };

    // C_EnvCubemapBox
    //   fields: 0
    class C_EnvCubemapBox {
    public:
    };

    // C_EnvCombinedLightProbeVolumeAlias_func_combined_light_probe_volume
    //   fields: 0
    class C_EnvCombinedLightProbeVolumeAlias_func_combined_light_probe_volume {
    public:
    };

    // C_RopeKeyframe::CPhysicsDelegate
    //   fields: 0
    class C_RopeKeyframe {
    public:
    };

    // CInfoDynamicShadowHint
    //   fields: 0
    class CInfoDynamicShadowHint {
    public:
    };

    // CPathNode
    //   parent: xL��
    //   fields: 0
    class CPathNode : public xL {
    public:
    };

    // C_FuncMoveLinear
    //   fields: 0
    class C_FuncMoveLinear {
    public:
    };

    // CServerOnlyModelEntity
    //   fields: 0
    class CServerOnlyModelEntity {
    public:
    };

    // C_CSGO_TeamSelectCamera
    //   fields: 0
    class C_CSGO_TeamSelectCamera {
    public:
    };

    // CPulseCell_IntervalTimer
    //   fields: 0
    class CPulseCell_IntervalTimer {
    public:
    };

    // C_WeaponXM1014
    //   fields: 0
    class C_WeaponXM1014 {
    public:
    };

    // C_WorldModelGloves
    //   parent: client
    //   fields: 0
    class C_WorldModelGloves : public client {
    public:
    };

    // C_PhysicsPropMultiplayer
    //   fields: 0
    class C_PhysicsPropMultiplayer {
    public:
    };

    // C_SoundEventOBBEntity
    //   fields: 0
    class C_SoundEventOBBEntity {
    public:
    };

    // CPulseTestScriptLib
    //   fields: 0
    class CPulseTestScriptLib {
    public:
    };

    // CPulseCell_BaseLerp
    //   parent: pulse_runtime_lib
    //   fields: 0
    class CPulseCell_BaseLerp : public pulse_runtime_lib {
    public:
    };

    // C_WeaponAug
    //   fields: 0
    class C_WeaponAug {
    public:
    };

    // C_BasePropDoor
    //   parent: client
    //   fields: 0
    class C_BasePropDoor : public client {
    public:
    };

    // CChoreoInfoTarget
    //   fields: 0
    class CChoreoInfoTarget {
    public:
    };

    // CTakeDamageResultAPI
    //   fields: 0
    class CTakeDamageResultAPI {
    public:
    };

    // CNetworkedSequenceOperation
    //   fields: 0
    class CNetworkedSequenceOperation {
    public:
    };

    // C_Item_Healthshot
    //   fields: 0
    class C_Item_Healthshot {
    public:
    };

    // CEntityInstance
    //   fields: 0
    class CEntityInstance {
    public:
    };

    // C_BaseModelEntity
    //   parent: xL��
    //   fields: 0
    class C_BaseModelEntity : public xL {
    public:
    };

    // CCSPlayer_BulletServices
    //   parent: xL��
    //   fields: 0
    class CCSPlayer_BulletServices : public xL {
    public:
    };

    // C_SoundOpvarSetAutoRoomEntity
    //   fields: 0
    class C_SoundOpvarSetAutoRoomEntity {
    public:
    };

    // C_EnvCombinedLightProbeVolume
    //   fields: 0
    class C_EnvCombinedLightProbeVolume {
    public:
    };

    // CCSGO_EndOfMatchLineupEnd
    //   fields: 0
    class CCSGO_EndOfMatchLineupEnd {
    public:
    };

    // C_MultiplayRules
    //   fields: 0
    class C_MultiplayRules {
    public:
    };

    // CPlayer_AutoaimServices
    //   fields: 0
    class CPlayer_AutoaimServices {
    public:
    };

    // C_LightDirectionalEntity
    //   fields: 0
    class C_LightDirectionalEntity {
    public:
    };

    // C_BaseEntity
    //   parent: xL��
    //   fields: 0
    class C_BaseEntity : public xL {
    public:
    };

    // ActiveModelConfig_t
    //   fields: 0
    class ActiveModelConfig_t {
    public:
    };

    // C_WeaponSSG08
    //   fields: 0
    class C_WeaponSSG08 {
    public:
    };

    // CPulseCell_Value_Curve
    //   fields: 0
    class CPulseCell_Value_Curve {
    public:
    };

    // C_Chicken
    //   parent: server
    //   fields: 0
    class C_Chicken : public server {
    public:
    };

    // C_BasePlayerPawn
    //   parent: xL��
    //   fields: 0
    class C_BasePlayerPawn : public xL {
    public:
    };

    // C_SoundOpvarSetAABBEntity
    //   fields: 0
    class C_SoundOpvarSetAABBEntity {
    public:
    };

    // C_WeaponBizon
    //   parent: xL��
    //   fields: 0
    class C_WeaponBizon : public xL {
    public:
    };

    // C_StattrakModule
    //   fields: 0
    class C_StattrakModule {
    public:
    };

    // CCSObserver_CameraServices
    //   fields: 0
    class CCSObserver_CameraServices {
    public:
    };

    // CEnvSoundscapeProxy
    //   fields: 0
    class CEnvSoundscapeProxy {
    public:
    };

    // C_SoundEventEntity
    //   fields: 0
    class C_SoundEventEntity {
    public:
    };

    // CPulseCell_Inflow_EventHandler
    //   parent: pulse_runtime_lib
    //   fields: 0
    class CPulseCell_Inflow_EventHandler : public pulse_runtime_lib {
    public:
    };

    // C_LightOrthoEntity
    //   fields: 0
    class C_LightOrthoEntity {
    public:
    };

    // CPulseCell_BaseFlow
    //   parent: pulse_runtime_lib
    //   fields: 0
    class CPulseCell_BaseFlow : public pulse_runtime_lib {
    public:
    };

    // CBombTarget
    //   fields: 0
    class CBombTarget {
    public:
    };

    // C_Knife
    //   parent: @SH�� H��H����H���ZH��H�� [����������������@SH�� H��H� |�H���XZH��H�� [����H��X
    //   fields: 0
    class C_Knife : public anonymous {
    public:
    };

    // C_CSGO_TerroristWingmanIntroCamera
    //   fields: 0
    class C_CSGO_TerroristWingmanIntroCamera {
    public:
    };

    // CSkeletonInstance
    //   fields: 0
    class CSkeletonInstance {
    public:
    };

    // CEntityComponent
    //   fields: 0
    class CEntityComponent {
    public:
    };

    // C_ItemDogtags
    //   fields: 0
    class C_ItemDogtags {
    public:
    };

    // C_LateUpdatedAnimating
    //   fields: 0
    class C_LateUpdatedAnimating {
    public:
    };

    // CPulseCell_Outflow_CycleShuffled::InstanceState_t
    //   fields: 1
    class CPulseCell_Outflow_CycleShuffled {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CPulseCell_BaseLerp::CursorState_t
    //   fields: 1
    class CPulseCell_BaseLerp {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CPulseAnimFuncs
    //   fields: 0
    class CPulseAnimFuncs {
    public:
    };

    // C_BaseClientUIEntity
    //   fields: 0
    class C_BaseClientUIEntity {
    public:
    };

    // CPulseCell_WaitForCursorsWithTagBase::CursorState_t
    //   fields: 0
    class CPulseCell_WaitForCursorsWithTagBase {
    public:
    };

    // CPulseArraylib
    //   fields: 0
    class CPulseArraylib {
    public:
    };

    // C_WeaponUSPSilencer
    //   parent: xL��
    //   fields: 0
    class C_WeaponUSPSilencer : public xL {
    public:
    };

    // C_MolotovProjectile
    //   fields: 0
    class C_MolotovProjectile {
    public:
    };

    // C_TriggerLerpObject
    //   fields: 0
    class C_TriggerLerpObject {
    public:
    };

    // CPointTemplateAPI
    //   fields: 0
    class CPointTemplateAPI {
    public:
    };

    // C_WeaponRevolver
    //   fields: 0
    class C_WeaponRevolver {
    public:
    };

    // C_WeaponElite
    //   fields: 0
    class C_WeaponElite {
    public:
    };

    // C_DynamicPropAlias_cable_dynamic
    //   fields: 0
    class C_DynamicPropAlias_cable_dynamic {
    public:
    };

    // CBaseProp
    //   fields: 0
    class CBaseProp {
    public:
    };

    // CInfoOffscreenPanoramaTexture
    //   fields: 0
    class CInfoOffscreenPanoramaTexture {
    public:
    };

    // CCSWeaponBaseVData
    //   fields: 0
    class CCSWeaponBaseVData {
    public:
    };

    // CAttributeManager
    //   fields: 0
    class CAttributeManager {
    public:
    };

    // SignatureOutflow_Continue
    //   fields: 0
    class SignatureOutflow_Continue {
    public:
    };

    // CInfoTarget
    //   fields: 0
    class CInfoTarget {
    public:
    };

    // CPlayer_CameraServices
    //   fields: 0
    class CPlayer_CameraServices {
    public:
    };

    // CPulseCell_Timeline
    //   fields: 0
    class CPulseCell_Timeline {
    public:
    };

    // CPulseCell_Inflow_EntOutputHandler
    //   fields: 0
    class CPulseCell_Inflow_EntOutputHandler {
    public:
    };

    // C_BaseCSGrenade
    //   fields: 0
    class C_BaseCSGrenade {
    public:
    };

    // CScenePayloadVData
    //   fields: 1
    class CScenePayloadVData {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CFilterAttributeInt
    //   fields: 0
    class CFilterAttributeInt {
    public:
    };

    // CPointTemplate
    //   parent: client
    //   fields: 0
    class CPointTemplate : public client {
    public:
    };

    // CPlayer_FlashlightServices
    //   fields: 0
    class CPlayer_FlashlightServices {
    public:
    };

    // CCSPlayerController
    //   fields: 0
    class CCSPlayerController {
    public:
    };

    // C_CSGO_TeamIntroCounterTerroristPosition
    //   fields: 0
    class C_CSGO_TeamIntroCounterTerroristPosition {
    public:
    };

    // C_CSGO_PreviewModel
    //   fields: 0
    class C_CSGO_PreviewModel {
    public:
    };

    // C_CSGO_TeamSelectCharacterPosition
    //   fields: 0
    class C_CSGO_TeamSelectCharacterPosition {
    public:
    };

    // CPulseCell_Outflow_CycleOrdered::InstanceState_t
    //   fields: 1
    class CPulseCell_Outflow_CycleOrdered {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // C_SoundEventAABBEntity
    //   fields: 0
    class C_SoundEventAABBEntity {
    public:
    };

    // CCSPlayer_MovementServices
    //   fields: 0
    class CCSPlayer_MovementServices {
    public:
    };

    // SellbackPurchaseEntry_t
    //   fields: 0
    class SellbackPurchaseEntry_t {
    public:
    };

    // C_TintController
    //   fields: 0
    class C_TintController {
    public:
    };

    // C_WeaponBaseItem
    //   fields: 0
    class C_WeaponBaseItem {
    public:
    };

    // CWaterSplasher
    //   fields: 0
    class CWaterSplasher {
    public:
    };

    // C_FuncBrush
    //   parent: client
    //   fields: 0
    class C_FuncBrush : public client {
    public:
    };

    // PhysicsRagdollPose_t
    //   fields: 1
    class PhysicsRagdollPose_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CPropDataComponent
    //   fields: 0
    class CPropDataComponent {
    public:
    };

    // CPulseCell_LimitCount::InstanceState_t
    //   fields: 1
    class CPulseCell_LimitCount {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // C_WeaponCZ75a
    //   fields: 0
    class C_WeaponCZ75a {
    public:
    };

    // C_DynamicLight
    //   fields: 0
    class C_DynamicLight {
    public:
    };

    // CCS2PawnGraphController
    //   fields: 0
    class CCS2PawnGraphController {
    public:
    };

    // EngineCountdownTimer
    //   fields: 0
    class EngineCountdownTimer {
    public:
    };

    // C_SoundEventSphereEntity
    //   fields: 0
    class C_SoundEventSphereEntity {
    public:
    };

    // CCSPlayerController_DamageServices
    //   fields: 0
    class CCSPlayerController_DamageServices {
    public:
    };

    // C_CSGO_TeamPreviewModel
    //   fields: 0
    class C_CSGO_TeamPreviewModel {
    public:
    };

    // C_TonemapController2Alias_env_tonemap_controller2
    //   fields: 0
    class C_TonemapController2Alias_env_tonemap_controller2 {
    public:
    };

    // C_Inferno
    //   fields: 0
    class C_Inferno {
    public:
    };

    // CFilterLOS
    //   fields: 0
    class CFilterLOS {
    public:
    };

    // CPointOrient
    //   fields: 0
    class CPointOrient {
    public:
    };

    // C_GlobalLight
    //   parent: client
    //   fields: 0
    class C_GlobalLight : public client {
    public:
    };

    // C_EnvWindClientside
    //   fields: 0
    class C_EnvWindClientside {
    public:
    };

    // sky3dparams_t
    //   fields: 0
    class sky3dparams_t {
    public:
    };

    // C_FlashbangProjectile
    //   fields: 0
    class C_FlashbangProjectile {
    public:
    };

    // C_SoundEventConeEntity
    //   fields: 0
    class C_SoundEventConeEntity {
    public:
    };

    // CDestructiblePartsComponent
    //   fields: 1
    class CDestructiblePartsComponent {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // C_WeaponP90
    //   fields: 0
    class C_WeaponP90 {
    public:
    };

    // C_EnvWind
    //   parent: MNotSaved
    //   fields: 0
    class C_EnvWind : public MNotSaved {
    public:
    };

    // C_CSGO_TerroristTeamIntroCamera
    //   fields: 0
    class C_CSGO_TerroristTeamIntroCamera {
    public:
    };

    // CPulseCell_Step_DebugLog
    //   parent: pulse_runtime_lib
    //   fields: 0
    class CPulseCell_Step_DebugLog : public pulse_runtime_lib {
    public:
    };

    // CCSPlayerController_ActionTrackingServices
    //   fields: 0
    class CCSPlayerController_ActionTrackingServices {
    public:
    };

    // CBodyComponentBaseAnimGraph
    //   parent: xL��
    //   fields: 0
    class CBodyComponentBaseAnimGraph : public xL {
    public:
    };

    // C_CSGO_PreviewModelAlias_csgo_item_previewmodel
    //   fields: 0
    class C_CSGO_PreviewModelAlias_csgo_item_previewmodel {
    public:
    };

    // C_InfoInstructorHintHostageRescueZone
    //   fields: 0
    class C_InfoInstructorHintHostageRescueZone {
    public:
    };

    // CPulseCell_BaseYieldingInflow
    //   parent: pulse_runtime_lib
    //   fields: 0
    class CPulseCell_BaseYieldingInflow : public pulse_runtime_lib {
    public:
    };

    // PulseNodeDynamicOutflows_t
    //   fields: 1
    class PulseNodeDynamicOutflows_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // C_TriggerBuoyancy
    //   fields: 0
    class C_TriggerBuoyancy {
    public:
    };

    // CPlayer_MovementServices_Humanoid
    //   fields: 0
    class CPlayer_MovementServices_Humanoid {
    public:
    };

    // CPulseCell_IsRequirementValid::Criteria_t
    //   fields: 0
    class CPulseCell_IsRequirementValid {
    public:
    };

    // C_WeaponTec9
    //   fields: 0
    class C_WeaponTec9 {
    public:
    };

    // C_PhysPropClientside
    //   parent: xL��
    //   fields: 0
    class C_PhysPropClientside : public xL {
    public:
    };

    // C_BaseDoor
    //   fields: 0
    class C_BaseDoor {
    public:
    };

    // CSMatchStats_t
    //   fields: 0
    class CSMatchStats_t {
    public:
    };

    // EntityRenderAttribute_t
    //   fields: 0
    class EntityRenderAttribute_t {
    public:
    };

    // CPulseCell_Inflow_ObservableVariableListener
    //   fields: 0
    class CPulseCell_Inflow_ObservableVariableListener {
    public:
    };

    // CFilterMultipleAPI
    //   fields: 0
    class CFilterMultipleAPI {
    public:
    };

    // CHostageRescueZone
    //   fields: 0
    class CHostageRescueZone {
    public:
    };

    // CModelState
    //   fields: 0
    class CModelState {
    public:
    };

    // CPulseCell_LerpCameraSettings::CursorState_t
    //   parent: client
    //   fields: 0
    class CPulseCell_LerpCameraSettings : public client {
    public:
    };

    // CPulseCell_Outflow_CycleOrdered
    //   parent: pulse_runtime_lib
    //   fields: 0
    class CPulseCell_Outflow_CycleOrdered : public pulse_runtime_lib {
    public:
    };

    // C_CSWeaponBaseGun
    //   fields: 0
    class C_CSWeaponBaseGun {
    public:
    };

    // C_CSGameRulesProxy
    //   parent: client
    //   fields: 0
    class C_CSGameRulesProxy : public client {
    public:
    };

    // CCollisionProperty
    //   fields: 0
    class CCollisionProperty {
    public:
    };

    // C_WeaponP250
    //   fields: 0
    class C_WeaponP250 {
    public:
    };

    // C_ShatterGlassShardPhysics
    //   fields: 0
    class C_ShatterGlassShardPhysics {
    public:
    };

    // CFilterMassGreater
    //   fields: 0
    class CFilterMassGreater {
    public:
    };

    // C_EntityDissolve
    //   fields: 0
    class C_EntityDissolve {
    public:
    };

    // C_SoundOpvarSetOBBEntity
    //   fields: 0
    class C_SoundOpvarSetOBBEntity {
    public:
    };

    // CCSGameModeRules_ArmsRace
    //   fields: 0
    class CCSGameModeRules_ArmsRace {
    public:
    };

    // C_FuncMonitor
    //   parent: 
    //   fields: 0
    class C_FuncMonitor : public anonymous {
    public:
    };

    // C_ClientRagdoll
    //   fields: 0
    class C_ClientRagdoll {
    public:
    };

    // PulseSelectorOutflowList_t
    //   fields: 1
    class PulseSelectorOutflowList_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CPulseCell_PlaySequence::CursorState_t
    //   fields: 1
    class CPulseCell_PlaySequence {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CBodyComponentSkeletonInstance
    //   fields: 0
    class CBodyComponentSkeletonInstance {
    public:
    };

    // C_CS2WeaponModuleBase
    //   parent: client
    //   fields: 0
    class C_CS2WeaponModuleBase : public client {
    public:
    };

    // C_CSGO_TeamPreviewCharacterPosition
    //   fields: 0
    class C_CSGO_TeamPreviewCharacterPosition {
    public:
    };

    // C_SmokeGrenadeProjectile
    //   parent: xL��
    //   fields: 0
    class C_SmokeGrenadeProjectile : public xL {
    public:
    };

    // CScriptComponent
    //   fields: 0
    class CScriptComponent {
    public:
    };

    // CCSPlayer_BuyServices
    //   fields: 0
    class CCSPlayer_BuyServices {
    public:
    };

    // C_PortraitWorldCallbackHandler
    //   fields: 0
    class C_PortraitWorldCallbackHandler {
    public:
    };

    // C_DynamicProp
    //   fields: 0
    class C_DynamicProp {
    public:
    };

    // C_CSTeam
    //   parent: xL��
    //   fields: 0
    class C_CSTeam : public xL {
    public:
    };

    // C_CS2HudModelWeapon
    //   fields: 0
    class C_CS2HudModelWeapon {
    public:
    };

    // C_TextureBasedAnimatable
    //   fields: 0
    class C_TextureBasedAnimatable {
    public:
    };

    // C_LightEnvironmentEntity
    //   fields: 0
    class C_LightEnvironmentEntity {
    public:
    };

    // DestructiblePartDamageRequestAPI
    //   fields: 0
    class DestructiblePartDamageRequestAPI {
    public:
    };

    // CLogicRelayAPI
    //   fields: 0
    class CLogicRelayAPI {
    public:
    };

    // C_TriggerPhysics
    //   fields: 0
    class C_TriggerPhysics {
    public:
    };

    // C_PropDoorRotating
    //   fields: 0
    class C_PropDoorRotating {
    public:
    };

    // C_HandleTest
    //   fields: 0
    class C_HandleTest {
    public:
    };

    // CInfoWorldLayer
    //   fields: 0
    class CInfoWorldLayer {
    public:
    };

    // CBodyComponentBaseModelEntity
    //   fields: 0
    class CBodyComponentBaseModelEntity {
    public:
    };

    // C_Multimeter
    //   fields: 0
    class C_Multimeter {
    public:
    };

    // C_BaseTrigger
    //   fields: 0
    class C_BaseTrigger {
    public:
    };

    // FilterDamageType
    //   fields: 0
    class FilterDamageType {
    public:
    };

    // CAttributeList
    //   fields: 0
    class CAttributeList {
    public:
    };

    // CPulseCell_Inflow_Wait
    //   parent: pulse_runtime_lib
    //   fields: 0
    class CPulseCell_Inflow_Wait : public pulse_runtime_lib {
    public:
    };

    // CFilterProximity
    //   fields: 0
    class CFilterProximity {
    public:
    };

    // CCS2WeaponGraphController
    //   fields: 0
    class CCS2WeaponGraphController {
    public:
    };

    // CEffectData
    //   fields: 0
    class CEffectData {
    public:
    };

    // C_ParticleSystem
    //   fields: 0
    class C_ParticleSystem {
    public:
    };

    // CPulseCell_Outflow_CycleShuffled
    //   parent: pulse_runtime_lib
    //   fields: 0
    class CPulseCell_Outflow_CycleShuffled : public pulse_runtime_lib {
    public:
    };

    // C_WeaponSCAR20
    //   fields: 0
    class C_WeaponSCAR20 {
    public:
    };

    // C_FuncMover
    //   fields: 0
    class C_FuncMover {
    public:
    };

    // CCSPlayerController_InventoryServices::NetworkedLoadoutSlot_t
    //   fields: 0
    class CCSPlayerController_InventoryServices {
    public:
    };

    // CLightComponent
    //   fields: 0
    class CLightComponent {
    public:
    };

    // C_DecoyGrenade
    //   fields: 0
    class C_DecoyGrenade {
    public:
    };

    // C_WaterBullet
    //   fields: 0
    class C_WaterBullet {
    public:
    };

    // CCSPlayer_ActionTrackingServices
    //   fields: 0
    class CCSPlayer_ActionTrackingServices {
    public:
    };

    // C_EnvCubemap
    //   fields: 0
    class C_EnvCubemap {
    public:
    };

    // CCSObserver_MovementServices
    //   fields: 0
    class CCSObserver_MovementServices {
    public:
    };

    // CBodyComponent
    //   fields: 0
    class CBodyComponent {
    public:
    };

    // CPulseCell_Inflow_Method
    //   fields: 0
    class CPulseCell_Inflow_Method {
    public:
    };

    // C_BaseCombatCharacter
    //   fields: 0
    class C_BaseCombatCharacter {
    public:
    };

    // CGlowProperty
    //   fields: 0
    class CGlowProperty {
    public:
    };

    // C_PointClientUIDialog
    //   fields: 0
    class C_PointClientUIDialog {
    public:
    };

    // CPulseCell_BaseValue
    //   parent: pulse_runtime_lib
    //   fields: 0
    class CPulseCell_BaseValue : public pulse_runtime_lib {
    public:
    };

    // C_WeaponHKP2000
    //   fields: 0
    class C_WeaponHKP2000 {
    public:
    };

    // C_FootstepControl
    //   fields: 0
    class C_FootstepControl {
    public:
    };

    // CCitadelSoundOpvarSetOBB
    //   fields: 0
    class CCitadelSoundOpvarSetOBB {
    public:
    };

    // C_CSGO_EndOfMatchLineupStart
    //   fields: 0
    class C_CSGO_EndOfMatchLineupStart {
    public:
    };

    // CPlayer_WaterServices
    //   fields: 0
    class CPlayer_WaterServices {
    public:
    };

    // CPulseCell_BooleanSwitchState
    //   fields: 0
    class CPulseCell_BooleanSwitchState {
    public:
    };

    // CDamageRecord
    //   fields: 0
    class CDamageRecord {
    public:
    };

    // VPhysicsCollisionAttribute_t
    //   fields: 0
    class VPhysicsCollisionAttribute_t {
    public:
    };

    // C_DynamicPropAlias_dynamic_prop
    //   fields: 0
    class C_DynamicPropAlias_dynamic_prop {
    public:
    };

    // CEnvSoundscapeProxyAlias_snd_soundscape_proxy
    //   fields: 0
    class CEnvSoundscapeProxyAlias_snd_soundscape_proxy {
    public:
    };

    // C_OmniLight
    //   fields: 0
    class C_OmniLight {
    public:
    };

    // C_SceneEntity
    //   fields: 0
    class C_SceneEntity {
    public:
    };

    // CPulseCell_Inflow_Yield
    //   parent: pulse_runtime_lib
    //   fields: 0
    class CPulseCell_Inflow_Yield : public pulse_runtime_lib {
    public:
    };

    // CPulseMathlib
    //   fields: 0
    class CPulseMathlib {
    public:
    };

    // C_NametagModule
    //   fields: 0
    class C_NametagModule {
    public:
    };

    // C_EconEntity
    //   parent: server
    //   fields: 0
    class C_EconEntity : public server {
    public:
    };

    // CPlayer_UseServices
    //   fields: 0
    class CPlayer_UseServices {
    public:
    };

    // C_PointValueRemapper
    //   fields: 0
    class C_PointValueRemapper {
    public:
    };

    // CGameSceneNodeHandle
    //   fields: 0
    class CGameSceneNodeHandle {
    public:
    };

    // CPulseCell_Unknown
    //   fields: 0
    class CPulseCell_Unknown {
    public:
    };

    // C_WeaponMP7
    //   parent: ���W�
    //   fields: 0
    class C_WeaponMP7 : public anonymous {
    public:
    };

    // CSPerRoundStats_t
    //   fields: 0
    class CSPerRoundStats_t {
    public:
    };

    // CPulseCell_Outflow_CycleRandom
    //   parent: pulse_runtime_lib
    //   fields: 0
    class CPulseCell_Outflow_CycleRandom : public pulse_runtime_lib {
    public:
    };

    // CPulseCell_Step_PublicOutput
    //   parent: pulse_runtime_lib
    //   fields: 0
    class CPulseCell_Step_PublicOutput : public pulse_runtime_lib {
    public:
    };

    // C_CS2HudModelBase
    //   fields: 0
    class C_CS2HudModelBase {
    public:
    };

    // C_CSGameRules
    //   fields: 0
    class C_CSGameRules {
    public:
    };

    // CGrenadeTracer
    //   fields: 0
    class CGrenadeTracer {
    public:
    };

    // CCSGameModeRules_Noop
    //   fields: 0
    class CCSGameModeRules_Noop {
    public:
    };

    // CPulse_BlackboardReference
    //   fields: 1
    class CPulse_BlackboardReference {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // C_BaseCSGrenadeProjectile
    //   fields: 0
    class C_BaseCSGrenadeProjectile {
    public:
    };

    // C_GradientFog
    //   fields: 0
    class C_GradientFog {
    public:
    };

    // CCSPlayerController_InGameMoneyServices
    //   fields: 0
    class CCSPlayerController_InGameMoneyServices {
    public:
    };

    // C_HEGrenadeProjectile
    //   fields: 0
    class C_HEGrenadeProjectile {
    public:
    };

    // CFilterModel
    //   fields: 0
    class CFilterModel {
    public:
    };

    // C_SoundAreaEntityOrientedBox
    //   fields: 0
    class C_SoundAreaEntityOrientedBox {
    public:
    };

    // C_SoundOpvarSetPointEntity
    //   fields: 0
    class C_SoundOpvarSetPointEntity {
    public:
    };

    // CPulseGameBlackboard
    //   fields: 0
    class CPulseGameBlackboard {
    public:
    };

    // CChoreoComponent
    //   fields: 1
    class CChoreoComponent {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CPulseCell_Value_RandomInt
    //   fields: 0
    class CPulseCell_Value_RandomInt {
    public:
    };

    // C_CSWeaponBaseShotgun
    //   parent: client
    //   fields: 0
    class C_CSWeaponBaseShotgun : public client {
    public:
    };

    // C_RagdollPropAttached
    //   fields: 0
    class C_RagdollPropAttached {
    public:
    };

    // C_ModelPointEntity
    //   fields: 0
    class C_ModelPointEntity {
    public:
    };

    // C_CSGO_PreviewPlayer
    //   fields: 0
    class C_CSGO_PreviewPlayer {
    public:
    };

    // C_RectLight
    //   fields: 0
    class C_RectLight {
    public:
    };

    // CPathSimple
    //   fields: 0
    class CPathSimple {
    public:
    };

    // C_FuncTrackTrain
    //   fields: 0
    class C_FuncTrackTrain {
    public:
    };

    // C_EconWearable
    //   fields: 0
    class C_EconWearable {
    public:
    };

    // C_EnvDecal
    //   parent: MEntityAllowsPortraitWorldSpawn
    //   fields: 0
    class C_EnvDecal : public MEntityAllowsPortraitWorldSpawn {
    public:
    };

    // EntitySpottedState_t
    //   fields: 0
    class EntitySpottedState_t {
    public:
    };

    // fogparams_t
    //   fields: 0
    class fogparams_t {
    public:
    };

    // C_WeaponM4A1
    //   fields: 0
    class C_WeaponM4A1 {
    public:
    };

    // C_Item
    //   fields: 0
    class C_Item {
    public:
    };

    // C_CSPetPlacement
    //   fields: 0
    class C_CSPetPlacement {
    public:
    };

    // C_Beam
    //   parent: xL��
    //   fields: 0
    class C_Beam : public xL {
    public:
    };

    // C_EnvLightProbeVolume
    //   fields: 0
    class C_EnvLightProbeVolume {
    public:
    };

    // CExplosionTypeData
    //   fields: 1
    class CExplosionTypeData {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // C_FuncConveyor
    //   fields: 0
    class C_FuncConveyor {
    public:
    };

    // CCSPlayer_WeaponServices
    //   fields: 0
    class CCSPlayer_WeaponServices {
    public:
    };

    // C_PhysMagnet
    //   fields: 0
    class C_PhysMagnet {
    public:
    };

    // CEnvSoundscapeTriggerableAlias_snd_soundscape_triggerable
    //   fields: 0
    class CEnvSoundscapeTriggerableAlias_snd_soundscape_triggerable {
    public:
    };

    // C_Breakable
    //   parent: client
    //   fields: 0
    class C_Breakable : public client {
    public:
    };

    // C_PlantedC4
    //   parent: server
    //   fields: 0
    class C_PlantedC4 : public server {
    public:
    };

    // CCSGO_WingmanIntroCharacterPosition
    //   fields: 0
    class CCSGO_WingmanIntroCharacterPosition {
    public:
    };

    // CFilterName
    //   parent: 
    //   fields: 0
    class CFilterName : public anonymous {
    public:
    };

    // C_RagdollProp
    //   fields: 0
    class C_RagdollProp {
    public:
    };

    // CPulse_CallInfo
    //   fields: 1
    class CPulse_CallInfo {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // C_MapPreviewParticleSystem
    //   parent: client
    //   fields: 0
    class C_MapPreviewParticleSystem : public client {
    public:
    };

    // CBaseAnimGraph
    //   parent: MNotSaved
    //   fields: 0
    class CBaseAnimGraph : public MNotSaved {
    public:
    };

    // CPulseCell_InlineNodeSkipSelector
    //   fields: 0
    class CPulseCell_InlineNodeSkipSelector {
    public:
    };

    // C_LightEntity
    //   parent: MNotSaved
    //   fields: 0
    class C_LightEntity : public MNotSaved {
    public:
    };

    // C_WeaponM249
    //   fields: 0
    class C_WeaponM249 {
    public:
    };

    // C_LocalTempEntity
    //   parent: xL��
    //   fields: 0
    class C_LocalTempEntity : public xL {
    public:
    };

    // C_WeaponTaser
    //   fields: 0
    class C_WeaponTaser {
    public:
    };

    // C_PointEntity
    //   fields: 0
    class C_PointEntity {
    public:
    };

    // C_SingleplayRules
    //   parent: client
    //   fields: 0
    class C_SingleplayRules : public client {
    public:
    };

    // CLogicalEntity
    //   parent: client
    //   fields: 0
    class CLogicalEntity : public client {
    public:
    };

    // C_PrecipitationBlocker
    //   fields: 0
    class C_PrecipitationBlocker {
    public:
    };

    // C_CSGO_CounterTerroristTeamIntroCamera
    //   fields: 0
    class C_CSGO_CounterTerroristTeamIntroCamera {
    public:
    };

    // C_SoundOpvarSetPathCornerEntity
    //   fields: 0
    class C_SoundOpvarSetPathCornerEntity {
    public:
    };

    // CPlayer_WeaponServices
    //   fields: 0
    class CPlayer_WeaponServices {
    public:
    };

    // C_WeaponNegev
    //   fields: 0
    class C_WeaponNegev {
    public:
    };

    // C_WeaponFiveSeven
    //   fields: 0
    class C_WeaponFiveSeven {
    public:
    };

    // C_WeaponSawedoff
    //   fields: 0
    class C_WeaponSawedoff {
    public:
    };

    // C_TriggerVolume
    //   fields: 0
    class C_TriggerVolume {
    public:
    };

    // CPulseCell_LimitCount
    //   parent: pulse_runtime_lib
    //   fields: 0
    class CPulseCell_LimitCount : public pulse_runtime_lib {
    public:
    };

    // CPulseCell_Step_CallExternalMethod
    //   fields: 0
    class CPulseCell_Step_CallExternalMethod {
    public:
    };

    // C_WeaponMP9
    //   fields: 0
    class C_WeaponMP9 {
    public:
    };

    // C_DynamicPropAlias_prop_dynamic_override
    //   fields: 0
    class C_DynamicPropAlias_prop_dynamic_override {
    public:
    };

    // CEnvSoundscapeTriggerable
    //   fields: 0
    class CEnvSoundscapeTriggerable {
    public:
    };

    // C_PlayerPing
    //   fields: 0
    class C_PlayerPing {
    public:
    };

    // C_AK47
    //   fields: 0
    class C_AK47 {
    public:
    };

    // C_CSGO_MapPreviewCameraPathNode
    //   fields: 0
    class C_CSGO_MapPreviewCameraPathNode {
    public:
    };

    // C_CSPlayerResource
    //   fields: 0
    class C_CSPlayerResource {
    public:
    };

    // CSkyboxReference
    //   fields: 0
    class CSkyboxReference {
    public:
    };

    // C_IncendiaryGrenade
    //   fields: 0
    class C_IncendiaryGrenade {
    public:
    };

    // CFilterClass
    //   fields: 0
    class CFilterClass {
    public:
    };

    // C_PointCameraVFOV
    //   fields: 0
    class C_PointCameraVFOV {
    public:
    };

    // C_PointCamera
    //   parent: MEntityAllowsPortraitWorldSpawn
    //   fields: 0
    class C_PointCamera : public MEntityAllowsPortraitWorldSpawn {
    public:
    };

    // CPathWithDynamicNodes
    //   parent: client
    //   fields: 0
    class CPathWithDynamicNodes : public client {
    public:
    };

    // CBaseFilter
    //   fields: 0
    class CBaseFilter {
    public:
    };

    // WeaponPurchaseTracker_t
    //   fields: 0
    class WeaponPurchaseTracker_t {
    public:
    };

    // PulseObservableBoolExpression_t
    //   fields: 1
    class PulseObservableBoolExpression_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CMapInfo
    //   fields: 0
    class CMapInfo {
    public:
    };

    // C_CSGO_EndOfMatchCamera
    //   fields: 0
    class C_CSGO_EndOfMatchCamera {
    public:
    };

    // C_BaseGrenade
    //   fields: 0
    class C_BaseGrenade {
    public:
    };

    // C_PlayerSprayDecal
    //   fields: 0
    class C_PlayerSprayDecal {
    public:
    };

    // CEntityIdentity
    //   fields: 0
    class CEntityIdentity {
    public:
    };

    // CPulseCell_LimitCount::Criteria_t
    //   fields: 0
    class CPulseCell_LimitCount {
    public:
    };

    // C_CS2HudModelArms
    //   fields: 0
    class C_CS2HudModelArms {
    public:
    };

    // CBasePlayerVData
    //   fields: 0
    class CBasePlayerVData {
    public:
    };

    // C_LightSpotEntity
    //   fields: 0
    class C_LightSpotEntity {
    public:
    };

    // CCSGameModeRules_Deathmatch
    //   fields: 0
    class CCSGameModeRules_Deathmatch {
    public:
    };

    // CPulseCell_CursorQueue
    //   parent: pulse_runtime_lib
    //   fields: 0
    class CPulseCell_CursorQueue : public pulse_runtime_lib {
    public:
    };

    // CPulseCell_Value_RandomFloat
    //   fields: 0
    class CPulseCell_Value_RandomFloat {
    public:
    };

    // CPulseExecCursor
    //   fields: 0
    class CPulseExecCursor {
    public:
    };

    // C_Sprite
    //   parent: xL��
    //   fields: 0
    class C_Sprite : public xL {
    public:
    };

    // C_CsmFovOverride
    //   fields: 0
    class C_CsmFovOverride {
    public:
    };

    // C_WeaponGlock
    //   fields: 0
    class C_WeaponGlock {
    public:
    };

    // C_PhysicsProp
    //   fields: 0
    class C_PhysicsProp {
    public:
    };

    // CFilterTeam
    //   fields: 0
    class CFilterTeam {
    public:
    };

    // CBasePlayerWeaponVData
    //   fields: 0
    class CBasePlayerWeaponVData {
    public:
    };

    // CInfoInteraction
    //   fields: 0
    class CInfoInteraction {
    public:
    };

    // C_SmokeGrenade
    //   fields: 0
    class C_SmokeGrenade {
    public:
    };

    // C_CSGO_PreviewPlayerAlias_csgo_player_previewmodel
    //   fields: 0
    class C_CSGO_PreviewPlayerAlias_csgo_player_previewmodel {
    public:
    };

    // CInfoParticleTarget
    //   fields: 0
    class CInfoParticleTarget {
    public:
    };

    // CCSPlayer_DamageReactServices
    //   fields: 0
    class CCSPlayer_DamageReactServices {
    public:
    };

    // C_PointClientUIWorldPanel
    //   fields: 0
    class C_PointClientUIWorldPanel {
    public:
    };

    // C_EntityFlame
    //   fields: 0
    class C_EntityFlame {
    public:
    };

    // CBasePlayerController
    //   fields: 0
    class CBasePlayerController {
    public:
    };

    // C_CSGO_EndOfMatchLineupEndpoint
    //   fields: 0
    class C_CSGO_EndOfMatchLineupEndpoint {
    public:
    };

    // GeneratedTextureHandle_t
    //   fields: 0
    class GeneratedTextureHandle_t {
    public:
    };

    // CompositeMaterialInputContainer_t
    //   fields: 1
    class CompositeMaterialInputContainer_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CompositeMaterialAssemblyProcedure_t
    //   fields: 1
    class CompositeMaterialAssemblyProcedure_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CompositeMaterialInputLooseVariable_t
    //   fields: 1
    class CompositeMaterialInputLooseVariable_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // screenshake_t
    //   fields: 1
    class screenshake_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CCS2UIPawnGraphController
    //   fields: 0
    class CCS2UIPawnGraphController {
    public:
    };

    // inv_image_light_barn_t
    //   fields: 1
    class inv_image_light_barn_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // inv_image_map_t
    //   fields: 1
    class inv_image_map_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // inv_image_light_fill_t
    //   fields: 1
    class inv_image_light_fill_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CInterpolatedValue
    //   fields: 0
    class CInterpolatedValue {
    public:
    };

    // inv_image_item_t
    //   fields: 1
    class inv_image_item_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // TimedEvent
    //   fields: 0
    class TimedEvent {
    public:
    };

    // CFlashlightEffect
    //   fields: 0
    class CFlashlightEffect {
    public:
    };

    // inv_image_camera_t
    //   fields: 1
    class inv_image_camera_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CInventoryImageData
    //   fields: 1
    class CInventoryImageData {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // inv_image_clearcolor_t
    //   fields: 1
    class inv_image_clearcolor_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // C_CommandContext
    //   fields: 0
    class C_CommandContext {
    public:
    };

    // CompositeMaterialEditorPoint_t
    //   fields: 1
    class CompositeMaterialEditorPoint_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CPlayerSprayDecalRenderHelper
    //   fields: 0
    class CPlayerSprayDecalRenderHelper {
    public:
    };

    // C_IronSightController
    //   fields: 0
    class C_IronSightController {
    public:
    };

    // CompMatMutatorCondition_t
    //   fields: 1
    class CompMatMutatorCondition_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // inv_image_data_t
    //   fields: 1
    class inv_image_data_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CompMatPropertyMutator_t
    //   fields: 1
    class CompMatPropertyMutator_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CCompositeMaterialEditorDoc
    //   fields: 1
    class CCompositeMaterialEditorDoc {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CClientAlphaProperty
    //   parent: xL��
    //   fields: 0
    class CClientAlphaProperty : public xL {
    public:
    };

    // screenfade_t
    //   fields: 1
    class screenfade_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CGlobalLightBase
    //   fields: 0
    class CGlobalLightBase {
    public:
    };

    // IClientAlphaProperty
    //   fields: 0
    class IClientAlphaProperty {
    public:
    };

    // inv_image_light_sun_t
    //   fields: 1
    class inv_image_light_sun_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CompositeMaterialMatchFilter_t
    //   fields: 1
    class CompositeMaterialMatchFilter_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CompositeMaterial_t
    //   fields: 0
    class CompositeMaterial_t {
    public:
    };

} // namespace cs2::sdk::client
