// Auto-generated by cs2-universal-dumper. Do not edit.
//
// module:        engine2.dll
// classes:       56
// enums:         2
// build_number:  14152
// generated_at:  2026-04-21T23:00:33.763106600+00:00
//
// Use:
//   auto* pawn = reinterpret_cast<C_CSPlayerPawn*>(addr);
//   pawn->m_iHealth() = 100;

#pragma once
#include "cs2sdk_macros.hpp"

namespace cs2::sdk::engine2 {

    inline constexpr std::uint32_t CS2_BUILD = 14152;

    class CEntityInstance;
    class CEntityComponent;
    class CScriptComponent;
    class CEntityIdentity;
    class EventClientPostSimulate_t;
    class EventSimpleLoopFrameUpdate_t;
    class EventPostAdvanceTick_t;
    class CEntityIOOutput;
    class EventClientSceneSystemThreadStateChange_t;
    class EventClientOutput_t;
    class EventServerPostSimulate_t;
    class CEntityComponentHelper;
    class GameTime_t;
    class EventServerBeginSimulate_t;
    class EntityIOQueuePrioritizedEvent_t;
    class EventServerEndAsyncPostTickWork_t;
    class EventClientAdvanceTick_t;
    class EntInput_t;
    class CNetworkVarChainer;
    class EventClientSimulate_t;
    class EventClientPostOutput_t;
    class GameTick_t;
    class EventClientPollInput_t;
    class EventPreDataUpdate_t;
    class EventClientProcessGameInput_t;
    class EventFrameBoundary_t;
    class EventAppShutdown_t;
    class EventServerPostAdvanceTick_t;
    class EventProfileStorageAvailable_t;
    class EventPostDataUpdate_t;
    class EventClientPreSimulate_t;
    class EventClientPauseSimulate_t;
    class EventClientProcessNetworking_t;
    class CEntityAttributeTable;
    class EventClientPreOutputParallelWithServer_t;
    class EventAdvanceTick_t;
    class EventSplitScreenStateChanged_t;
    class EventClientPostAdvanceTick_t;
    class CVariantDefaultAllocator;
    class EventModInitialized_t;
    class EventClientPreOutput_t;
    class EventClientFrameSimulate_t;
    class EventServerAdvanceTick_t;
    class EventSetTime_t;
    class EventSimulate_t;
    class CEntityKeyValues;
    class EventClientAdvanceNonRenderedFrame_t;
    class EventServerProcessNetworking_t;
    class CEmptyEntityInstance;
    class EntComponentInfo_t;
    class EngineLoopState_t;
    class EventClientPollNetworking_t;
    class EventServerBeginAsyncPostTickWork_t;
    class EventClientProcessInput_t;
    class EventServerEndSimulate_t;
    class EventServerPollNetworking_t;

    enum class EntityDormancyType_t : std::uint32_t {
        ENTITY_NOT_DORMANT = 0x0,
        ENTITY_DORMANT = 0x1,
        ENTITY_SUSPENDED = 0x2,
    };

    enum class EntityIOTargetType_t : std::uint32_t {
        ENTITY_IO_TARGET_INVALID = 0xFFFFFFFFFFFFFFFF,
        ENTITY_IO_TARGET_ENTITYNAME = 0x2,
        ENTITY_IO_TARGET_EHANDLE = 0x6,
        ENTITY_IO_TARGET_ENTITYNAME_OR_CLASSNAME = 0x7,
    };

    // CEntityInstance
    //   fields: 0
    class CEntityInstance {
    public:
    };

    // CEntityComponent
    //   fields: 0
    class CEntityComponent {
    public:
    };

    // CScriptComponent
    //   fields: 0
    class CScriptComponent {
    public:
    };

    // CEntityIdentity
    //   fields: 0
    class CEntityIdentity {
    public:
    };

    // EventClientPostSimulate_t
    //   parent: engine2
    //   fields: 0
    class EventClientPostSimulate_t : public engine2 {
    public:
    };

    // EventSimpleLoopFrameUpdate_t
    //   fields: 0
    class EventSimpleLoopFrameUpdate_t {
    public:
    };

    // EventPostAdvanceTick_t
    //   parent: engine2
    //   fields: 0
    class EventPostAdvanceTick_t : public engine2 {
    public:
    };

    // CEntityIOOutput
    //   fields: 0
    class CEntityIOOutput {
    public:
    };

    // EventClientSceneSystemThreadStateChange_t
    //   fields: 0
    class EventClientSceneSystemThreadStateChange_t {
    public:
    };

    // EventClientOutput_t
    //   fields: 0
    class EventClientOutput_t {
    public:
    };

    // EventServerPostSimulate_t
    //   parent: xL��
    //   fields: 0
    class EventServerPostSimulate_t : public xL {
    public:
    };

    // CEntityComponentHelper
    //   fields: 0
    class CEntityComponentHelper {
    public:
    };

    // GameTime_t
    //   fields: 0
    class GameTime_t {
    public:
    };

    // EventServerBeginSimulate_t
    //   parent: xL��
    //   fields: 0
    class EventServerBeginSimulate_t : public xL {
    public:
    };

    // EntityIOQueuePrioritizedEvent_t
    //   fields: 1
    class EntityIOQueuePrioritizedEvent_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // EventServerEndAsyncPostTickWork_t
    //   fields: 0
    class EventServerEndAsyncPostTickWork_t {
    public:
    };

    // EventClientAdvanceTick_t
    //   parent: engine2
    //   fields: 0
    class EventClientAdvanceTick_t : public engine2 {
    public:
    };

    // EntInput_t
    //   fields: 0
    class EntInput_t {
    public:
    };

    // CNetworkVarChainer
    //   fields: 0
    class CNetworkVarChainer {
    public:
    };

    // EventClientSimulate_t
    //   parent: engine2
    //   fields: 0
    class EventClientSimulate_t : public engine2 {
    public:
    };

    // EventClientPostOutput_t
    //   fields: 0
    class EventClientPostOutput_t {
    public:
    };

    // GameTick_t
    //   fields: 0
    class GameTick_t {
    public:
    };

    // EventClientPollInput_t
    //   fields: 0
    class EventClientPollInput_t {
    public:
    };

    // EventPreDataUpdate_t
    //   fields: 0
    class EventPreDataUpdate_t {
    public:
    };

    // EventClientProcessGameInput_t
    //   fields: 0
    class EventClientProcessGameInput_t {
    public:
    };

    // EventFrameBoundary_t
    //   fields: 0
    class EventFrameBoundary_t {
    public:
    };

    // EventAppShutdown_t
    //   fields: 0
    class EventAppShutdown_t {
    public:
    };

    // EventServerPostAdvanceTick_t
    //   parent: xL��
    //   fields: 0
    class EventServerPostAdvanceTick_t : public xL {
    public:
    };

    // EventProfileStorageAvailable_t
    //   fields: 0
    class EventProfileStorageAvailable_t {
    public:
    };

    // EventPostDataUpdate_t
    //   fields: 0
    class EventPostDataUpdate_t {
    public:
    };

    // EventClientPreSimulate_t
    //   parent: engine2
    //   fields: 0
    class EventClientPreSimulate_t : public engine2 {
    public:
    };

    // EventClientPauseSimulate_t
    //   parent: xL��
    //   fields: 0
    class EventClientPauseSimulate_t : public xL {
    public:
    };

    // EventClientProcessNetworking_t
    //   fields: 0
    class EventClientProcessNetworking_t {
    public:
    };

    // CEntityAttributeTable
    //   fields: 0
    class CEntityAttributeTable {
    public:
    };

    // EventClientPreOutputParallelWithServer_t
    //   parent: xL��
    //   fields: 0
    class EventClientPreOutputParallelWithServer_t : public xL {
    public:
    };

    // EventAdvanceTick_t
    //   parent: xL��
    //   fields: 0
    class EventAdvanceTick_t : public xL {
    public:
    };

    // EventSplitScreenStateChanged_t
    //   fields: 0
    class EventSplitScreenStateChanged_t {
    public:
    };

    // EventClientPostAdvanceTick_t
    //   parent: engine2
    //   fields: 0
    class EventClientPostAdvanceTick_t : public engine2 {
    public:
    };

    // CVariantDefaultAllocator
    //   fields: 0
    class CVariantDefaultAllocator {
    public:
    };

    // EventModInitialized_t
    //   fields: 0
    class EventModInitialized_t {
    public:
    };

    // EventClientPreOutput_t
    //   fields: 0
    class EventClientPreOutput_t {
    public:
    };

    // EventClientFrameSimulate_t
    //   fields: 0
    class EventClientFrameSimulate_t {
    public:
    };

    // EventServerAdvanceTick_t
    //   parent: xL��
    //   fields: 0
    class EventServerAdvanceTick_t : public xL {
    public:
    };

    // EventSetTime_t
    //   fields: 0
    class EventSetTime_t {
    public:
    };

    // EventSimulate_t
    //   fields: 0
    class EventSimulate_t {
    public:
    };

    // CEntityKeyValues
    //   fields: 0
    class CEntityKeyValues {
    public:
    };

    // EventClientAdvanceNonRenderedFrame_t
    //   fields: 0
    class EventClientAdvanceNonRenderedFrame_t {
    public:
    };

    // EventServerProcessNetworking_t
    //   parent: engine2
    //   fields: 0
    class EventServerProcessNetworking_t : public engine2 {
    public:
    };

    // CEmptyEntityInstance
    //   fields: 0
    class CEmptyEntityInstance {
    public:
    };

    // EntComponentInfo_t
    //   fields: 0
    class EntComponentInfo_t {
    public:
    };

    // EngineLoopState_t
    //   fields: 0
    class EngineLoopState_t {
    public:
    };

    // EventClientPollNetworking_t
    //   fields: 0
    class EventClientPollNetworking_t {
    public:
    };

    // EventServerBeginAsyncPostTickWork_t
    //   fields: 0
    class EventServerBeginAsyncPostTickWork_t {
    public:
    };

    // EventClientProcessInput_t
    //   fields: 0
    class EventClientProcessInput_t {
    public:
    };

    // EventServerEndSimulate_t
    //   fields: 0
    class EventServerEndSimulate_t {
    public:
    };

    // EventServerPollNetworking_t
    //   parent: engine2
    //   fields: 0
    class EventServerPollNetworking_t : public engine2 {
    public:
    };

} // namespace cs2::sdk::engine2
