// Auto-generated by cs2-universal-dumper. Do not edit.
//
// module:        resourcesystem.dll
// classes:       58
// enums:         2
// build_number:  14152
// generated_at:  2026-04-21T23:00:33.763106600+00:00
//
// Use:
//   auto* pawn = reinterpret_cast<C_CSPlayerPawn*>(addr);
//   pawn->m_iHealth() = 100;

#pragma once
#include "cs2sdk_macros.hpp"

namespace cs2::sdk::resourcesystem {

    inline constexpr std::uint32_t CS2_BUILD = 14152;

    class InfoForResourceTypeCResponseRulesList;
    class InfoForResourceTypeCDotaItemDefinitionResource;
    class InfoForResourceTypeCMorphSetData;
    class InfoForResourceTypeCVSoundStackScriptList;
    class PackedAABB_t;
    class InfoForResourceTypeCVPhysXSurfacePropertiesList;
    class InfoForResourceTypeManifestTestResource_t;
    class ConstantInfo_t;
    class FuseFunctionIndex_t;
    class InfoForResourceTypeCGcExportableExternalData;
    class InfoForResourceTypeIAnimGraphModelBinding;
    class InfoForResourceTypeCJavaScriptResource;
    class CFuseSymbolTable;
    class InfoForResourceTypeCRenderMesh;
    class InfoForResourceTypeCVoxelVisibility;
    class InfoForResourceTypeCPhysAggregateData;
    class InfoForResourceTypeCNmClip;
    class InfoForResourceTypeWorld_t;
    class InfoForResourceTypeProceduralTestResource_t;
    class AABB_t;
    class InfoForResourceTypeCPostProcessingResource;
    class VariableInfo_t;
    class InfoForResourceTypeIParticleSnapshot;
    class FourQuaternions;
    class InfoForResourceTypeCPanoramaLayout;
    class InfoForResourceTypeCTypeScriptResource;
    class InfoForResourceTypeCChoreoSceneResource;
    class InfoForResourceTypeCNmSkeleton;
    class InfoForResourceTypeCTestResourceData;
    class InfoForResourceTypeCAnimationGroup;
    class InfoForResourceTypeCVSoundEventScriptList;
    class InfoForResourceTypeCVoiceContainerBase;
    class InfoForResourceTypeCPanoramaStyle;
    class InfoForResourceTypeCWorldNode;
    class InfoForResourceTypeCSurfaceGraph;
    class InfoForResourceTypeCCSGOEconItem;
    class InfoForResourceTypeCNmGraphDefinition;
    class InfoForResourceTypeCSmartProp;
    class CFuseProgram;
    class InfoForResourceTypeCCompositeMaterialKit;
    class InfoForResourceTypeCVMixListResource;
    class InfoForResourceTypeCAnimData;
    class InfoForResourceTypeIMaterial2;
    class InfoForResourceTypeIVectorGraphic;
    class InfoForResourceTypeCPanoramaDynamicImages;
    class InfoForResourceTypeIPulseGraphDef;
    class InfoForResourceTypeCVDataItemDefs;
    class FunctionInfo_t;
    class InfoForResourceTypeCVDataResource;
    class InfoForResourceTypeCModel;
    class InfoForResourceTypeCDOTANovelsList;
    class InfoForResourceTypeCTextureBase;
    class FuseVariableIndex_t;
    class InfoForResourceTypeIParticleSystemDefinition;
    class InfoForResourceTypeCSequenceGroupData;
    class ManifestTestResource_t;
    class InfoForResourceTypeCEntityLump;
    class InfoForResourceTypeCDOTAPatchNotesList;

    enum class FuseVariableType_t : std::uint8_t {
        INVALID = 0x0,
        BOOL = 0x1,
        INT8 = 0x2,
        INT16 = 0x3,
        INT32 = 0x4,
        UINT8 = 0x5,
        UINT16 = 0x6,
        UINT32 = 0x7,
        FLOAT32 = 0x8,
    };

    enum class FuseVariableAccess_t : std::uint8_t {
        WRITABLE = 0x0,
        READ_ONLY = 0x1,
    };

    // InfoForResourceTypeCResponseRulesList
    //   fields: 0
    class InfoForResourceTypeCResponseRulesList {
    public:
    };

    // InfoForResourceTypeCDotaItemDefinitionResource
    //   fields: 0
    class InfoForResourceTypeCDotaItemDefinitionResource {
    public:
    };

    // InfoForResourceTypeCMorphSetData
    //   fields: 0
    class InfoForResourceTypeCMorphSetData {
    public:
    };

    // InfoForResourceTypeCVSoundStackScriptList
    //   fields: 0
    class InfoForResourceTypeCVSoundStackScriptList {
    public:
    };

    // PackedAABB_t
    //   fields: 0
    class PackedAABB_t {
    public:
    };

    // InfoForResourceTypeCVPhysXSurfacePropertiesList
    //   fields: 0
    class InfoForResourceTypeCVPhysXSurfacePropertiesList {
    public:
    };

    // InfoForResourceTypeManifestTestResource_t
    //   fields: 0
    class InfoForResourceTypeManifestTestResource_t {
    public:
    };

    // ConstantInfo_t
    //   fields: 1
    class ConstantInfo_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FuseFunctionIndex_t
    //   fields: 0
    class FuseFunctionIndex_t {
    public:
    };

    // InfoForResourceTypeCGcExportableExternalData
    //   fields: 0
    class InfoForResourceTypeCGcExportableExternalData {
    public:
    };

    // InfoForResourceTypeIAnimGraphModelBinding
    //   fields: 0
    class InfoForResourceTypeIAnimGraphModelBinding {
    public:
    };

    // InfoForResourceTypeCJavaScriptResource
    //   fields: 0
    class InfoForResourceTypeCJavaScriptResource {
    public:
    };

    // CFuseSymbolTable
    //   fields: 1
    class CFuseSymbolTable {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // InfoForResourceTypeCRenderMesh
    //   fields: 0
    class InfoForResourceTypeCRenderMesh {
    public:
    };

    // InfoForResourceTypeCVoxelVisibility
    //   fields: 0
    class InfoForResourceTypeCVoxelVisibility {
    public:
    };

    // InfoForResourceTypeCPhysAggregateData
    //   fields: 0
    class InfoForResourceTypeCPhysAggregateData {
    public:
    };

    // InfoForResourceTypeCNmClip
    //   fields: 0
    class InfoForResourceTypeCNmClip {
    public:
    };

    // InfoForResourceTypeWorld_t
    //   fields: 0
    class InfoForResourceTypeWorld_t {
    public:
    };

    // InfoForResourceTypeProceduralTestResource_t
    //   fields: 0
    class InfoForResourceTypeProceduralTestResource_t {
    public:
    };

    // AABB_t
    //   fields: 0
    class AABB_t {
    public:
    };

    // InfoForResourceTypeCPostProcessingResource
    //   fields: 0
    class InfoForResourceTypeCPostProcessingResource {
    public:
    };

    // VariableInfo_t
    //   fields: 1
    class VariableInfo_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // InfoForResourceTypeIParticleSnapshot
    //   fields: 0
    class InfoForResourceTypeIParticleSnapshot {
    public:
    };

    // FourQuaternions
    //   fields: 0
    class FourQuaternions {
    public:
    };

    // InfoForResourceTypeCPanoramaLayout
    //   fields: 0
    class InfoForResourceTypeCPanoramaLayout {
    public:
    };

    // InfoForResourceTypeCTypeScriptResource
    //   fields: 0
    class InfoForResourceTypeCTypeScriptResource {
    public:
    };

    // InfoForResourceTypeCChoreoSceneResource
    //   fields: 0
    class InfoForResourceTypeCChoreoSceneResource {
    public:
    };

    // InfoForResourceTypeCNmSkeleton
    //   fields: 0
    class InfoForResourceTypeCNmSkeleton {
    public:
    };

    // InfoForResourceTypeCTestResourceData
    //   fields: 0
    class InfoForResourceTypeCTestResourceData {
    public:
    };

    // InfoForResourceTypeCAnimationGroup
    //   fields: 0
    class InfoForResourceTypeCAnimationGroup {
    public:
    };

    // InfoForResourceTypeCVSoundEventScriptList
    //   fields: 0
    class InfoForResourceTypeCVSoundEventScriptList {
    public:
    };

    // InfoForResourceTypeCVoiceContainerBase
    //   fields: 0
    class InfoForResourceTypeCVoiceContainerBase {
    public:
    };

    // InfoForResourceTypeCPanoramaStyle
    //   fields: 0
    class InfoForResourceTypeCPanoramaStyle {
    public:
    };

    // InfoForResourceTypeCWorldNode
    //   fields: 0
    class InfoForResourceTypeCWorldNode {
    public:
    };

    // InfoForResourceTypeCSurfaceGraph
    //   fields: 0
    class InfoForResourceTypeCSurfaceGraph {
    public:
    };

    // InfoForResourceTypeCCSGOEconItem
    //   fields: 0
    class InfoForResourceTypeCCSGOEconItem {
    public:
    };

    // InfoForResourceTypeCNmGraphDefinition
    //   fields: 0
    class InfoForResourceTypeCNmGraphDefinition {
    public:
    };

    // InfoForResourceTypeCSmartProp
    //   fields: 0
    class InfoForResourceTypeCSmartProp {
    public:
    };

    // CFuseProgram
    //   fields: 1
    class CFuseProgram {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // InfoForResourceTypeCCompositeMaterialKit
    //   fields: 0
    class InfoForResourceTypeCCompositeMaterialKit {
    public:
    };

    // InfoForResourceTypeCVMixListResource
    //   fields: 0
    class InfoForResourceTypeCVMixListResource {
    public:
    };

    // InfoForResourceTypeCAnimData
    //   fields: 0
    class InfoForResourceTypeCAnimData {
    public:
    };

    // InfoForResourceTypeIMaterial2
    //   fields: 0
    class InfoForResourceTypeIMaterial2 {
    public:
    };

    // InfoForResourceTypeIVectorGraphic
    //   fields: 0
    class InfoForResourceTypeIVectorGraphic {
    public:
    };

    // InfoForResourceTypeCPanoramaDynamicImages
    //   fields: 0
    class InfoForResourceTypeCPanoramaDynamicImages {
    public:
    };

    // InfoForResourceTypeIPulseGraphDef
    //   fields: 0
    class InfoForResourceTypeIPulseGraphDef {
    public:
    };

    // InfoForResourceTypeCVDataItemDefs
    //   fields: 0
    class InfoForResourceTypeCVDataItemDefs {
    public:
    };

    // FunctionInfo_t
    //   fields: 1
    class FunctionInfo_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // InfoForResourceTypeCVDataResource
    //   fields: 0
    class InfoForResourceTypeCVDataResource {
    public:
    };

    // InfoForResourceTypeCModel
    //   fields: 0
    class InfoForResourceTypeCModel {
    public:
    };

    // InfoForResourceTypeCDOTANovelsList
    //   fields: 0
    class InfoForResourceTypeCDOTANovelsList {
    public:
    };

    // InfoForResourceTypeCTextureBase
    //   fields: 0
    class InfoForResourceTypeCTextureBase {
    public:
    };

    // FuseVariableIndex_t
    //   fields: 0
    class FuseVariableIndex_t {
    public:
    };

    // InfoForResourceTypeIParticleSystemDefinition
    //   fields: 0
    class InfoForResourceTypeIParticleSystemDefinition {
    public:
    };

    // InfoForResourceTypeCSequenceGroupData
    //   fields: 0
    class InfoForResourceTypeCSequenceGroupData {
    public:
    };

    // ManifestTestResource_t
    //   fields: 1
    class ManifestTestResource_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // InfoForResourceTypeCEntityLump
    //   fields: 0
    class InfoForResourceTypeCEntityLump {
    public:
    };

    // InfoForResourceTypeCDOTAPatchNotesList
    //   fields: 0
    class InfoForResourceTypeCDOTAPatchNotesList {
    public:
    };

} // namespace cs2::sdk::resourcesystem
