// Auto-generated by cs2-universal-dumper. Do not edit.
//
// module:        steamaudio.dll
// classes:       17
// enums:         0
// build_number:  14152
// generated_at:  2026-04-21T23:00:33.763106600+00:00
//
// Use:
//   auto* pawn = reinterpret_cast<C_CSPlayerPawn*>(addr);
//   pawn->m_iHealth() = 100;

#pragma once
#include "cs2sdk_macros.hpp"

namespace cs2::sdk::steamaudio {

    inline constexpr std::uint32_t CS2_BUILD = 14152;

    class SteamAudioReverbClusteringSettings_t;
    class SteamAudioCustomDataDimensionsSettings_t;
    class SteamAudioPathSettings_t;
    class CSteamAudioAmbisonicsField;
    class CSteamAudioBakedPathingData;
    class SteamAudioReverbSettings_t;
    class CSteamAudioProbeData;
    class SteamAudioReverbCompressionSettings_t;
    class CSteamAudioBakedMaterialsData;
    class CSteamAudioBakedOcclusionData;
    class CSteamAudioBakedReverbData;
    class CSteamAudioProbeLineSegment;
    class SteamAudioCustomDataOcclusionSettings_t;
    class CSteamAudioBakedDimensionsData;
    class CSteamAudioSceneData;
    class CSteamAudioProbeGrid;
    class CSteamAudioCompressedReverb;

    // SteamAudioReverbClusteringSettings_t
    //   fields: 1
    class SteamAudioReverbClusteringSettings_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // SteamAudioCustomDataDimensionsSettings_t
    //   fields: 1
    class SteamAudioCustomDataDimensionsSettings_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // SteamAudioPathSettings_t
    //   fields: 1
    class SteamAudioPathSettings_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CSteamAudioAmbisonicsField
    //   fields: 1
    class CSteamAudioAmbisonicsField {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CSteamAudioBakedPathingData
    //   fields: 1
    class CSteamAudioBakedPathingData {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // SteamAudioReverbSettings_t
    //   fields: 1
    class SteamAudioReverbSettings_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CSteamAudioProbeData
    //   fields: 1
    class CSteamAudioProbeData {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // SteamAudioReverbCompressionSettings_t
    //   fields: 1
    class SteamAudioReverbCompressionSettings_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CSteamAudioBakedMaterialsData
    //   fields: 1
    class CSteamAudioBakedMaterialsData {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CSteamAudioBakedOcclusionData
    //   fields: 1
    class CSteamAudioBakedOcclusionData {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CSteamAudioBakedReverbData
    //   fields: 1
    class CSteamAudioBakedReverbData {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CSteamAudioProbeLineSegment
    //   fields: 1
    class CSteamAudioProbeLineSegment {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // SteamAudioCustomDataOcclusionSettings_t
    //   fields: 1
    class SteamAudioCustomDataOcclusionSettings_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CSteamAudioBakedDimensionsData
    //   fields: 1
    class CSteamAudioBakedDimensionsData {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CSteamAudioSceneData
    //   fields: 1
    class CSteamAudioSceneData {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CSteamAudioProbeGrid
    //   fields: 1
    class CSteamAudioProbeGrid {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CSteamAudioCompressedReverb
    //   fields: 1
    class CSteamAudioCompressedReverb {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

} // namespace cs2::sdk::steamaudio
