// Auto-generated by cs2-universal-dumper. Do not edit.

namespace CS2Sdk.Signatures;

public static class Signatures
{
    public static class animationsystem
    {
        public const ulong Animation__ShouldUpdateSequences = 0x7FFC0F0FF0A0UL; // rva 0x14F0A0
    }
    public static class client
    {
        public const ulong AddNametagEntity = 0x7FFBFFE7AE20UL; // rva 0x78AE20
        public const ulong AddStattrakEntity = 0x7FFC0013B030UL; // rva 0xA4B030
        public const ulong AutowallInit = 0x7FFBFFFD0860UL; // rva 0x8E0860
        public const ulong AutowallTraceData = 0x7FFC0007D260UL; // rva 0x98D260
        public const ulong AutowallTracePos = 0x7FFBFFEF6BE0UL; // rva 0x806BE0
        public const ulong BulkRegenIterator = 0x7FFBFFE7E321UL; // rva 0x78E321
        public const ulong CAM_ThinkReturn = 0x7FFBFFA0A44FUL; // rva 0x31A44F
        public const ulong CAttributeStringFill = 0x7FFC0059C570UL; // rva 0xEAC570
        public const ulong CAttributeStringInit = 0x7FFBFFCE8600UL; // rva 0x5F8600
        public const ulong CBaseEntity_TakeDamageOld = 0x7FFBFF913C70UL; // rva 0x223C70
        public const ulong CBaseModelEntity_SetBodygroup = 0x7FFBFFFC87F0UL; // rva 0x8D87F0
        public const ulong CBodyComponent = 0x7FFBFF8AC0B0UL; // rva 0x1BC0B0
        public const ulong CBodyComponentSkeletonInstance = 0x7FFBFF8B2F90UL; // rva 0x1C2F90
        public const ulong CBufferStringInit = 0x7FFC00ED0160UL; // rva 0x17E0160
        public const ulong CCSGOInput__CreateMove = 0x7FFC0034C2A0UL; // rva 0xC5C2A0
        public const ulong CCSGameRules = 0x7FFBFF76E160UL; // rva 0x7E160
        public const ulong CCSGameRulesProxy = 0x7FFBFFDD9450UL; // rva 0x6E9450
        public const ulong CCSInventoryManager__EquipItemInLoadout = 0x7FFBFFEB2090UL; // rva 0x7C2090
        public const ulong CCSPlayerController = 0x7FFBFFED4FA0UL; // rva 0x7E4FA0
        public const ulong CCSPlayerController = 0x7FFBFFED4FA0UL; // rva 0x7E4FA0
        public const ulong CCSPlayerController_ActionTrackingServices = 0x7FFBFFED4FA0UL; // rva 0x7E4FA0
        public const ulong CCSPlayerController_DamageServices = 0x7FFBFFED4FA0UL; // rva 0x7E4FA0
        public const ulong CCSPlayerController_InGameMoneyServices = 0x7FFBFFED4FA0UL; // rva 0x7E4FA0
        public const ulong CCSPlayerController_InventoryServices = 0x7FFBFFED4FA0UL; // rva 0x7E4FA0
        public const ulong CCSPlayerInventory__GetItemInLoadout = 0x7FFBFFEB3CB0UL; // rva 0x7C3CB0
        public const ulong CCSPlayerPawn = 0x7FFC0029F6E0UL; // rva 0xBAF6E0
        public const ulong CCSPlayer_BulletServices = 0x7FFBFFF02BC0UL; // rva 0x812BC0
        public const ulong CCSPlayer_BulletServices = 0x7FFBFFF02BC0UL; // rva 0x812BC0
        public const ulong CCSPlayer_CameraServices = 0x7FFBFFEFECD0UL; // rva 0x80ECD0
        public const ulong CCSPlayer_HostageServices = 0x7FFBFFF02BC0UL; // rva 0x812BC0
        public const ulong CCSPlayer_ItemServices = 0x7FFBFFF3F710UL; // rva 0x84F710
        public const ulong CCSPlayer_MovementServices = 0x7FFBFFF2CAF0UL; // rva 0x83CAF0
        public const ulong CCSPlayer_MovementServices = 0x7FFBFFF2CAF0UL; // rva 0x83CAF0
        public const ulong CCSPlayer_PingServices = 0x7FFBFFF40920UL; // rva 0x850920
        public const ulong CCSPlayer_RunCommand_Context = 0x7FFC000CA390UL; // rva 0x9DA390
        public const ulong CCSPlayer_UseServices = 0x7FFBFFF70B50UL; // rva 0x880B50
        public const ulong CCSPlayer_WaterServices = 0x7FFBFFF65DE0UL; // rva 0x875DE0
        public const ulong CCSPlayer_WeaponServices = 0x7FFBFFF66190UL; // rva 0x876190
        public const ulong CCSPlayer_WeaponServices = 0x7FFBFFF66190UL; // rva 0x876190
        public const ulong CCSWeaponBase = 0x7FFBFFE6F260UL; // rva 0x77F260
        public const ulong CCSWeaponBaseGun = 0x7FFBFFE6F300UL; // rva 0x77F300
        public const ulong CCSWeaponBaseVData = 0x7FFBFFE4A170UL; // rva 0x75A170
        public const ulong CCollisionProperty = 0x7FFBFF9D0EE0UL; // rva 0x2E0EE0
        public const ulong CCompositeMaterialManager_AddPanoramaPanelRenderRequest_Caller = 0x7FFC00AA9064UL; // rva 0x13B9064
        public const ulong CDecoyProjectile = 0x7FFBFFE3E0A0UL; // rva 0x74E0A0
        public const ulong CEconItemSchema__GetAttributeDefinitionByName = 0x7FFC0073A5E0UL; // rva 0x104A5E0
        public const ulong CEconItemView__GetCustomPaintKitIndex = 0x7FFBFFFA9C70UL; // rva 0x8B9C70
        public const ulong CFlashbangProjectile = 0x7FFC006CDB30UL; // rva 0xFDDB30
        public const ulong CFogController = 0x7FFBFF96EF20UL; // rva 0x27EF20
        public const ulong CGameEntitySystem__OnAddEntity = 0x7FFC00056F30UL; // rva 0x966F30
        public const ulong CGameEntitySystem__OnRemoveEntity = 0x7FFC00057790UL; // rva 0x967790
        public const ulong CGameSceneNode = 0x7FFBFF893840UL; // rva 0x1A3840
        public const ulong CGameSceneNode_BuildBoneMergeWork = 0x7FFC0002E3C0UL; // rva 0x93E3C0
        public const ulong CGameSceneNode_StartHierarchicalAttachment = 0x7FFC0007AE80UL; // rva 0x98AE80
        public const ulong CGameTrace_TraceShape_Client = 0x7FFC0007D340UL; // rva 0x98D340
        public const ulong CGlowProperty = 0x7FFBFF9D10F0UL; // rva 0x2E10F0
        public const ulong CGlowProperty_OnGlowTypeChanged = 0x7FFC001FB630UL; // rva 0xB0B630
        public const ulong CHEGrenadeProjectile = 0x7FFC006CDBD0UL; // rva 0xFDDBD0
        public const ulong CInputPtrGlobal = 0x7FFC017513C0UL; // rva 0x20613C0
        public const ulong CMolotovProjectile = 0x7FFBFFE3E280UL; // rva 0x74E280
        public const ulong CPaintKitDefinitions_FindOrCreateByName = 0x7FFC00747DD0UL; // rva 0x1057DD0
        public const ulong CPaintKitDefinitions_LoadDefaultKit = 0x7FFC00719EA0UL; // rva 0x1029EA0
        public const ulong CPostProcessingVolume = 0x7FFBFF993CB0UL; // rva 0x2A3CB0
        public const ulong CS2ItemEditor_BuildTemplateMaterialFromFile = 0x7FFC00AAA1E0UL; // rva 0x13BA1E0
        public const ulong CSBaseGunFireData_fn = 0x7FFC00BD58D0UL; // rva 0x14E58D0
        public const ulong CSGOInput_ptr = 0x7FFC017513C0UL; // rva 0x20613C0
        public const ulong CSGOInput_resolved = 0x7FFC017513C7UL; // rva 0x20613C7
        public const ulong CSkeletonInstance = 0x7FFBFF893970UL; // rva 0x1A3970
        public const ulong CSkeletonInstance__SetMeshGroupMask = 0x7FFC0011C3F0UL; // rva 0xA2C3F0
        public const ulong CSkeletonInstance_GetTransformsForHitboxList = 0x7FFC00108F60UL; // rva 0xA18F60
        public const ulong CSkeletonInstance_OnBodyGroupChoiceChanged = 0x7FFC00113BB0UL; // rva 0xA23BB0
        public const ulong CSkeletonInstance_OnSkeletonModelChanged = 0x7FFC00113DC0UL; // rva 0xA23DC0
        public const ulong CSkeletonInstance_PostDataUpdate = 0x7FFC00114D50UL; // rva 0xA24D50
        public const ulong CSkeletonInstance_SetMaterialGroup = 0x7FFC0011B0D0UL; // rva 0xA2B0D0
        public const ulong CSkeletonInstance_SetMeshGroupMask = 0x7FFC00113D20UL; // rva 0xA23D20
        public const ulong CSmokeGrenadeProjectile = 0x7FFBFFE3E320UL; // rva 0x74E320
        public const ulong CTonemapController2 = 0x7FFBFF947BE0UL; // rva 0x257BE0
        public const ulong CUtlVector_CompositeMaterialInput_AddToTail = 0x7FFBFFE79A00UL; // rva 0x789A52
        public const ulong C_AttributeContainer = 0x7FFC003065E0UL; // rva 0xC165E0
        public const ulong C_BaseEntity = 0x7FFBFF73E260UL; // rva 0x4E260
        public const ulong C_BaseModelEntity = 0x7FFBFF847F60UL; // rva 0x157F60
        public const ulong C_BasePlayerPawn = 0x7FFBFF75DA20UL; // rva 0x6DA20
        public const ulong C_C4 = 0x7FFBFF78A370UL; // rva 0x9A370
        public const ulong C_CSPlayerPawn = 0x7FFBFFDB2380UL; // rva 0x6C2380
        public const ulong C_CSPlayerPawnBase = 0x7FFC002C57C0UL; // rva 0xBD57C0
        public const ulong C_CSWeaponBase = 0x7FFBFFE32030UL; // rva 0x742030
        public const ulong C_EconEntity_BuildLegacyGloveSkinMaterial = 0x7FFC002AFB00UL; // rva 0xBBFB00
        public const ulong C_EconEntity_BuildLegacyWeaponSkinMaterial = 0x7FFBFFE7C050UL; // rva 0x78C050
        public const ulong C_EconEntity_BuildModernWeaponSkinMaterial = 0x7FFC004728E0UL; // rva 0xD828E0
        public const ulong C_EconEntity_BuildNametagOverlayMaterial = 0x7FFBFFE7AE20UL; // rva 0x78AE20
        public const ulong C_EconItemView = 0x7FFBFFDFB400UL; // rva 0x70B400
        public const ulong C_EconWearable_OnNewCustomMaterials = 0x7FFC007A67D0UL; // rva 0x10B67D0
        public const ulong C_Hostage = 0x7FFBFF7D73D0UL; // rva 0xE73D0
        public const ulong C_Inferno = 0x7FFBFF7E7390UL; // rva 0xF7390
        public const ulong C_PlantedC4 = 0x7FFBFF7E06F0UL; // rva 0xF06F0
        public const ulong C_SmokeGrenadeProjectile = 0x7FFBFF785960UL; // rva 0x95960
        public const ulong CacheParticleEffect = 0x7FFBFF8F7B10UL; // rva 0x207B10
        public const ulong CalcSpread = 0x7FFC0036C6F0UL; // rva 0xC7C6F0
        public const ulong CalcViewmodel = 0x7FFBFFF3E040UL; // rva 0x84E040
        public const ulong CalcViewmodelTransform_v2 = 0x7FFBFFE92460UL; // rva 0x7A2460
        public const ulong CalcViewmodelView = 0x7FFC003599D0UL; // rva 0xC699D0
        public const ulong CalculateInterpolation = 0x7FFC00BB5600UL; // rva 0x14C5600
        public const ulong CalculateWorldSpaceBones = 0x7FFC000F9910UL; // rva 0xA09910
        public const ulong ClearHUDWeaponIcon = 0x7FFC004DB720UL; // rva 0xDEB720
        public const ulong ClientModeCSNormal_OnEvent = 0x7FFC0034A110UL; // rva 0xC5A110
        public const ulong ClientMode_ptr = 0x7FFC01A2BA60UL; // rva 0x233BA60
        public const ulong Client_DispatchSpawn = 0x7FFC00BC32A0UL; // rva 0x14D32A0
        public const ulong CompositeMaterialPanoramaPanel_Init = 0x7FFC0027FB00UL; // rva 0xB8FB00
        public const ulong ConCommand_firstperson = 0x7FFC001B8B50UL; // rva 0xAC8B50
        public const ulong ConCommand_thirdperson = 0x7FFC001B8C30UL; // rva 0xAC8C30
        public const ulong ConvarGet = 0x7FFBFFFADF82UL; // rva 0x8BDF82
        public const ulong CreateBaseTypeCache = 0x7FFC00BFE630UL; // rva 0x150E630
        public const ulong CreateEntityByClassName = 0x7FFC00CF23D6UL; // rva 0x16023D6
        public const ulong CreateNewSubtickMoveStep = 0x7FFBFFBA1CD0UL; // rva 0x4B1CD0
        public const ulong CreateParticleEffect = 0x7FFC000758C0UL; // rva 0x9858C0
        public const ulong CreateSOSubclassEconItem = 0x7FFC006E4EB0UL; // rva 0xFF4EB0
        public const ulong DestroyParticle = 0x7FFC00034DB0UL; // rva 0x944DB0
        public const ulong DispatchEffect = 0x7FFBFFA4A4C0UL; // rva 0x35A4C0
        public const ulong DispatchSpawn_caller = 0x7FFC00BC32A0UL; // rva 0x14D32A0
        public const ulong DrawCrosshair = 0x7FFBFFEA0B60UL; // rva 0x7B0B60
        public const ulong DrawOverHead = 0x7FFC00155590UL; // rva 0xA65590
        public const ulong DrawScopeOverlay = 0x7FFBFFF4BFF0UL; // rva 0x85BFF0
        public const ulong DrawSmokeVertex = 0x7FFC00368D90UL; // rva 0xC78D90
        public const ulong FX_FireBullets = 0x7FFC0036BE80UL; // rva 0xC7BE80
        public const ulong FX_FireBullets = 0x7FFC0036BE80UL; // rva 0xC7BE80
        public const ulong FindHudElement = 0x7FFC004AF7E8UL; // rva 0xDBF7E8
        public const ulong FindHudElement_panorama = 0x7FFC004B17C0UL; // rva 0xDC17C0
        public const ulong FindSOCache = 0x7FFC00F0C810UL; // rva 0x181C810
        public const ulong FirstPersonLegs = 0x7FFC007DDAA0UL; // rva 0x10EDAA0
        public const ulong FlashOverlay = 0x7FFC00498C10UL; // rva 0xDA8C10
        public const ulong ForceButtonsDown = 0x7FFC000BE9D0UL; // rva 0x9CE9D0
        public const ulong GameEntitySystemPtr = 0x7FFC01BBED50UL; // rva 0x24CED50
        public const ulong GameEventManager_AddListener = 0x7FFC00028970UL; // rva 0x938970
        public const ulong GameEventManager_UnserializeEvent = 0x7FFC000811A0UL; // rva 0x9911A0
        public const ulong GameRules_ptr = 0x7FFC01A18F38UL; // rva 0x2328F38
        public const ulong GetBBox_ptr = 0x7FFC01A18F38UL; // rva 0x2328F38
        public const ulong GetBaseEntity = 0x7FFC00055EF0UL; // rva 0x965EF0
        public const ulong GetBonePositionByName = 0x7FFBFFFB6B60UL; // rva 0x8C6B60
        public const ulong GetChatObject = 0x7FFC007B0DB0UL; // rva 0x10C0DB0
        public const ulong GetClientSystem = 0x7FFC00723CB0UL; // rva 0x1033CB0
        public const ulong GetControllerCmd = 0x7FFBFFFAC580UL; // rva 0x8BC580
        public const ulong GetEconItemSystem = 0x7FFBFFA69780UL; // rva 0x379780
        public const ulong GetEntityHandle = 0x7FFC0003D1C0UL; // rva 0x94D1C0
        public const ulong GetGlowColor = 0x7FFC001F9460UL; // rva 0xB09460
        public const ulong GetInstanceS = 0x7FFC019A75E0UL; // rva 0x22B75E0
        public const ulong GetInt2_Event = 0x7FFBFFB9AA90UL; // rva 0x4AAA90
        public const ulong GetInventoryManager = 0x7FFBFFEB6370UL; // rva 0x7C6370
        public const ulong GetLocalControllerById = 0x7FFBFFFCF9F0UL; // rva 0x8DF9F0
        public const ulong GetLocalPlayer_dispatcher = 0x7FFBFFA69150UL; // rva 0x379150
        public const ulong GetMatrixForView = 0x7FFBFF859BA0UL; // rva 0x169BA0
        public const ulong GetPlayerByIndex_export = 0x7FFC005EE180UL; // rva 0xEFE180
        public const ulong GetPlayerInterp = 0x7FFBFFFA7DE0UL; // rva 0x8B7DE0
        public const ulong GetRemovedAimPunch_E8 = 0x7FFBFFF3C2F0UL; // rva 0x84C2F0
        public const ulong GetRemovedAimpunch = 0x7FFBFF802897UL; // rva 0x112897
        public const ulong GetSurfaceData = 0x7FFC00041E30UL; // rva 0x951E30
        public const ulong GetTickBase = 0x7FFBFFFAC380UL; // rva 0x8BC380
        public const ulong GetTraceInfo = 0x7FFBFFEF63B0UL; // rva 0x8063B0
        public const ulong GetUserCmdManager = 0x7FFBFFFAC610UL; // rva 0x8BC610
        public const ulong GetViewAngles = 0x7FFC001C4540UL; // rva 0xAD4540
        public const ulong GetWeaponInAccuracyRecoveryTime = 0x7FFBFFE86570UL; // rva 0x796570
        public const ulong GetWorldFovResolver = 0x7FFBFFEFBE50UL; // rva 0x80BE50
        public const ulong GlobalVariables_ptr = 0x7FFC017396A0UL; // rva 0x20496A0
        public const ulong GloveApply_PerTick = 0x7FFC002AFB00UL; // rva 0xBBFB00
        public const ulong GlowObjectManager_GetInstance = 0x7FFC001F9570UL; // rva 0xB09570
        public const ulong HandleBulletPenetration = 0x7FFBFFF10210UL; // rva 0x820210
        public const ulong HandleEntityList = 0x7FFBFF8B3650UL; // rva 0x1C3650
        public const ulong HandleTeamIntro = 0x7FFBFFDF3E00UL; // rva 0x703E00
        public const ulong HudChatPrintf = 0x7FFC007AE830UL; // rva 0x10BE830
        public const ulong InfoForResourceTypeCCompositeMaterialKit_TypeManager = 0x7FFC00AC6840UL; // rva 0x13D6840
        public const ulong InfoForResourceTypeCCompositeMaterial_TypeManager = 0x7FFC00AC6D90UL; // rva 0x13D6D90
        public const ulong InitFilter = 0x7FFBFFA1BB40UL; // rva 0x32BB40
        public const ulong InitPlayerMovementTraceFilter = 0x7FFBFFF2F270UL; // rva 0x83F270
        public const ulong InitTraceInfo = 0x7FFC00CE9A30UL; // rva 0x15F9A30
        public const ulong IsGlowing = 0x7FFC001FABA0UL; // rva 0xB0ABA0
        public const ulong LevelInit = 0x7FFBFFFBEA80UL; // rva 0x8CEA80
        public const ulong LoadFileForMe = 0x7FFC0000A8C0UL; // rva 0x91A8C0
        public const ulong LoadPath = 0x7FFBFFDAB150UL; // rva 0x6BB150
        public const ulong LookupBone = 0x7FFBFFFB6B60UL; // rva 0x8C6B60
        public const ulong ModulationUpdate = 0x7FFC000C8CF0UL; // rva 0x9D8CF0
        public const ulong NoClipOnChange = 0x7FFBFF856B50UL; // rva 0x166B50
        public const ulong NoSpread1 = 0x7FFC0036BDD0UL; // rva 0xC7BDD0
        public const ulong ParticleCollection = 0x7FFBFF8E4CE0UL; // rva 0x1F4CE0
        public const ulong ParticleManager_ptr = 0x7FFC0171DAA8UL; // rva 0x202DAA8
        public const ulong PhysicsRunThink_Ctrl = 0x7FFBFFFC5C90UL; // rva 0x8D5C90
        public const ulong PhysicsRunThink_Pawn = 0x7FFC001FD5F0UL; // rva 0xB0D5F0
        public const ulong PlayVSound_client = 0x7FFC00BFC490UL; // rva 0x150C490
        public const ulong ProcessImpacts = 0x7FFC000BD2F0UL; // rva 0x9CD2F0
        public const ulong ProcessMovement = 0x7FFC000C82D0UL; // rva 0x9D82D0
        public const ulong RegenerateWeaponSkin = 0x7FFBFFE7C050UL; // rva 0x78C050
        public const ulong RegenerateWeaponSkin_v2 = 0x7FFBFFE7C050UL; // rva 0x78C050
        public const ulong RegenerateWeaponSkins = 0x7FFBFFEA0CB0UL; // rva 0x7B0CB0
        public const ulong ReportHit = 0x7FFBFFCF21E0UL; // rva 0x6021E0
        public const ulong RunCommand = 0x7FFC000CA390UL; // rva 0x9DA390
        public const ulong RunCommand_processor = 0x7FFC000CA390UL; // rva 0x9DA390
        public const ulong Scope_callsite = 0x7FFBFFF4BFF0UL; // rva 0x85BFF0
        public const ulong SendChatMessage = 0x7FFC007AE830UL; // rva 0x10BE830
        public const ulong SetAbsOrigin_Pawn = 0x7FFBFF90EEA0UL; // rva 0x21EEA0
        public const ulong SetBodyGroup_inv = 0x7FFC00484BF0UL; // rva 0xD94BF0
        public const ulong SetCollisionBounds = 0x7FFBFFEF3540UL; // rva 0x803540
        public const ulong SetDynamicAttributeValue = 0x7FFC006F26A0UL; // rva 0x10026A0
        public const ulong SetDynamicAttributeValue_raw = 0x7FFC006F26A0UL; // rva 0x10026A0
        public const ulong SetMeshGroupMask = 0x7FFC0011C3F0UL; // rva 0xA2C3F0
        public const ulong SetModel = 0x7FFBFFFC9B40UL; // rva 0x8D9B40
        public const ulong SetPlayerReady = 0x7FFC0060B510UL; // rva 0xF1B510
        public const ulong SetTraceData = 0x7FFBFFEC4750UL; // rva 0x7D4750
        public const ulong SetTypeKV3 = 0x7FFC00F08640UL; // rva 0x1818640
        public const ulong SetViewAngle = 0x7FFC001D3580UL; // rva 0xAE3580
        public const ulong SetupCmd = 0x7FFBFFFA98A0UL; // rva 0x8B98A0
        public const ulong SetupMove = 0x7FFC0040AA50UL; // rva 0xD1AA50
        public const ulong SetupMovementMoves = 0x7FFC0087441FUL; // rva 0x118441F
        public const ulong SomeTimingFromPawn = 0x7FFC00145B50UL; // rva 0xA55B50
        public const ulong Spawner_PerTickOrchestrator = 0x7FFC002B2680UL; // rva 0xBC2680
        public const ulong SpectatorInput = 0x7FFBFFEC9130UL; // rva 0x7D9130
        public const ulong TestSurfaces = 0x7FFBFFEF6290UL; // rva 0x806290
        public const ulong TracePlayerBBox = 0x7FFC0025F6D0UL; // rva 0xB6F6D0
        public const ulong TraceShape = 0x7FFC0007D340UL; // rva 0x98D340
        public const ulong TraceShape_Client = 0x7FFC0007D340UL; // rva 0x98D340
        public const ulong TraceToExit = 0x7FFBFFEF4400UL; // rva 0x804400
        public const ulong UpdatePostProcessing = 0x7FFC0060F6A0UL; // rva 0xF1F6A0
        public const ulong UpdateSubClass = 0x7FFBFF8EA88BUL; // rva 0x1FA88B
        public const ulong UpdateTurningInAccuracy = 0x7FFBFFE9FD10UL; // rva 0x7AFD10
        public const ulong VPhys2World_ptr = 0x7FFC0171D718UL; // rva 0x202D718
        public const ulong ViewModelHideZoomed = 0x7FFBFFE903D0UL; // rva 0x7A03D0
        public const ulong ViewRender_ptr = 0x7FFC01A1DCB8UL; // rva 0x232DCB8
        public const ulong WriteSubtickFromEntry = 0x7FFC00343E10UL; // rva 0xC53E10
        public const ulong create_move_v2 = 0x7FFC001BA9C0UL; // rva 0xACA9C0
        public const ulong draw_smoke_array = 0x7FFC00368E80UL; // rva 0xC78E80
        public const ulong draw_view_punch_v2 = 0x7FFBFFEF3CC0UL; // rva 0x803CC0
        public const ulong entity_list_ptr = 0x7FFC01BBEE58UL; // rva 0x24CEE58
        public const ulong frame_stage_notify = 0x7FFC001C15D1UL; // rva 0xAD15D1
        public const ulong get_fov = 0x7FFBFFEF3CC0UL; // rva 0x803CC0
        public const ulong get_map_name = 0x7FFC005CADF0UL; // rva 0xEDADF0
        public const ulong get_view_angles_v2 = 0x7FFC001C2EA0UL; // rva 0xAD2EA0
        public const ulong get_view_model = 0x7FFBFFF3E040UL; // rva 0x84E040
        public const ulong global_vars_v2 = 0x7FFC01A18F38UL; // rva 0x2328F38
        public const ulong is_demo_or_hltv = 0x7FFC005EC220UL; // rva 0xEFC220
        public const ulong level_init_v2 = 0x7FFC001E9230UL; // rva 0xAF9230
        public const ulong level_shutdown = 0x7FFC001E94B0UL; // rva 0xAF94B0
        public const ulong local_controller = 0x7FFC019F8520UL; // rva 0x2308520
        public const ulong mark_interp_latch_flags_dirty = 0x7FFBFF907FC0UL; // rva 0x217FC0
        public const ulong on_add_entity_v2 = 0x7FFC000574A0UL; // rva 0x9674A0
        public const ulong override_view_short = 0x7FFC0034D2F0UL; // rva 0xC5D2F0
        public const ulong paintkit_prefab = 0x7FFC0074AAF0UL; // rva 0x105AAF0
        public const ulong paintkit_seed = 0x7FFC005DEC20UL; // rva 0xEEEC20
        public const ulong paintkit_wear = 0x7FFC005DEC20UL; // rva 0xEEEC20
        public const ulong planted_c4_ptr = 0x7FFC01996CB8UL; // rva 0x22A6CB8
        public const ulong remove_legs = 0x7FFC007DDAA0UL; // rva 0x10EDAA0
        public const ulong statTrak_killEater = 0x7FFC005DEC20UL; // rva 0xEEEC20
        public const ulong statTrak_scoreType = 0x7FFBFF80B740UL; // rva 0x11B740
        public const ulong unlock_inventory = 0x7FFBFFDF1110UL; // rva 0x701110
        public const ulong update_global_vars = 0x7FFC001D2FD0UL; // rva 0xAE2FD0
        public const ulong update_post_processing_v2 = 0x7FFC00613C56UL; // rva 0xF23C56
        public const ulong view_matrix_ptr = 0x7FFC01A1EAC0UL; // rva 0x232EAC0
    }
    public static class engine2
    {
        public const ulong CCommand_Tokenize = 0x7FFC1306D710UL; // rva 0x3FD710
        public const ulong CGameClient_ClientCommand = 0x7FFC12D11240UL; // rva 0xA1240
        public const ulong CHLTVClient_ExecuteStringCommand = 0x7FFC12D90D70UL; // rva 0x120D70
        public const ulong CSplitScreenSlot = 0x7FFC12EBA250UL; // rva 0x24A250
        public const ulong Cvar_RegisterConCommand = 0x7FFC1306D270UL; // rva 0x3FD270
        public const ulong Cvar_RegisterConVar = 0x7FFC1306C080UL; // rva 0x3FC080
        public const ulong Engine__GetScreenAspectRatio = 0x7FFC12CE69D0UL; // rva 0x769D0
        public const ulong Engine__PVSManager_ptr = 0x7FFC132833F0UL; // rva 0x6133F0
        public const ulong Engine__RunPrediction = 0x7FFC12CD6490UL; // rva 0x66490
        public const ulong Engine_Disconnect_main = 0x7FFC12E41510UL; // rva 0x1D1510
        public const ulong Engine_HLTVClient_ExecuteStringCommand = 0x7FFC12D90D70UL; // rva 0x120D70
        public const ulong Engine_HostStateMgr_QueueNewRequest = 0x7FFC12E8AFC0UL; // rva 0x21AFC0
        public const ulong Engine_HostStateMgr_QueueNewRequest = 0x7FFC12E8AFC0UL; // rva 0x21AFC0
        public const ulong Engine_LoadGameInfo = 0x7FFC12DFD760UL; // rva 0x18D760
        public const ulong Engine_MountAddon = 0x7FFC12E03440UL; // rva 0x193440
        public const ulong Engine_NetTimeoutDisconnect = 0x7FFC12CD9780UL; // rva 0x69780
        public const ulong Engine_NetworkGameClient_Connect = 0x7FFC12CEF400UL; // rva 0x7F400
        public const ulong Engine_NetworkGameClient_SetSignonState = 0x7FFC12CD0F80UL; // rva 0x60F80
        public const ulong Engine_RegisterConCommand = 0x7FFC1306D270UL; // rva 0x3FD270
        public const ulong Engine_RegisterConVar = 0x7FFC1306C080UL; // rva 0x3FC080
    }
    public static class materialsystem2
    {
        public const ulong CMaterial2_CompileComboAndGetVariables_DynamicShaderCompile = 0x7FFC11943FA0UL; // rva 0x13FA0
        public const ulong CMaterial2_LoadShadersAndSetupModes = 0x7FFC11940040UL; // rva 0x10040
        public const ulong CMaterialLayer_ApplyMaterialVarsForBatch = 0x7FFC11948B80UL; // rva 0x18B80
        public const ulong CMaterialLayer_BuildPassCommandData = 0x7FFC11948F80UL; // rva 0x18F80
        public const ulong CMaterialLayer_ComputeWorkItemsToSetupStaticCombosForMode = 0x7FFC11945F3CUL; // rva 0x15F3C
        public const ulong CMaterialLayer_CreateCommandBuffer = 0x7FFC11949820UL; // rva 0x19820
        public const ulong CMaterialSystem2_BindIdentityInstanceIDBufferAndSetRenderState = 0x7FFC119A0000UL; // rva 0x70000
        public const ulong CMaterialSystem2_DynamicShaderCompile_UnloadAllMaterials = 0x7FFC11969AA0UL; // rva 0x39AA0
        public const ulong CMaterialSystem2_FrameUpdate = 0x7FFC1196BAC0UL; // rva 0x3BAC0
        public const ulong CMaterialSystem2_GetErrorMaterial = 0x7FFC119474D7UL; // rva 0x174D7
        public const ulong CMaterialSystem2_Init = 0x7FFC11966E40UL; // rva 0x36E40
        public const ulong CMaterial_SetVariableAndRenderState = 0x7FFC1195F9B0UL; // rva 0x2F9B0
        public const ulong CVfxProgramData_FindOrCreateStaticComboDataInCache = 0x7FFC119DE0E0UL; // rva 0xAE0E0
        public const ulong FindParameter = 0x7FFC11941E30UL; // rva 0x11E30
        public const ulong MatSys__PrepareSceneMaterial = 0x7FFC11941BE0UL; // rva 0x11BE0
        public const ulong UpdateParameter = 0x7FFC11942370UL; // rva 0x12370
    }
    public static class networksystem
    {
        public const ulong CNetChan_ProcessMessages = 0x7FFC0FC1B280UL; // rva 0xBB280
        public const ulong CNetChan_SendNetMessage = 0x7FFC0FC1D670UL; // rva 0xBD670
        public const ulong NetSystem_CNetChan_ProcessMessages = 0x7FFC0FC1B280UL; // rva 0xBB280
        public const ulong NetSystem_CNetChan_SendNetMessage = 0x7FFC0FC1D670UL; // rva 0xBD670
    }
    public static class particles
    {
        public const ulong Particles__DrawArray = 0x7FFC09E520B0UL; // rva 0x220B0
        public const ulong Particles__FindKeyVar = 0x7FFC09E6A650UL; // rva 0x3A650
        public const ulong Particles__SetMaterialShaderType = 0x7FFC09ECD8D0UL; // rva 0x9D8D0
    }
    public static class rendersystemdx11
    {
        public const ulong CRenderDeviceBase_CreateConstantBuffer = 0x7FFC1259F500UL; // rva 0x2F500
        public const ulong CRenderDeviceDx11_BeginSubmittingDisplayLists = 0x7FFC125AC4E0UL; // rva 0x3C4E0
        public const ulong CRenderDeviceDx11_CompileShaderSourceMain = 0x7FFC125AFAF0UL; // rva 0x3FAF0
        public const ulong CSwapChainDx11_QueuePresentAndWait = 0x7FFC125A4650UL; // rva 0x34650
        public const ulong CSwapChainDx11_ResizeBuffers = 0x7FFC125ADD20UL; // rva 0x3DD20
        public const ulong RenderSystemDx11_QueuePresentAndWait = 0x7FFC125A4650UL; // rva 0x34650
        public const ulong RenderSystemDx11_SetHardwareGammaRamp = 0x7FFC125AF790UL; // rva 0x3F790
        public const ulong RenderSystemDx11_SetMode = 0x7FFC125A99E0UL; // rva 0x399E0
    }
    public static class resourcesystem
    {
        public const ulong ResourceSystem_BlockingLoadResourceByName = 0x7FFC5B0A7360UL; // rva 0x17360
        public const ulong ResourceSystem_FindOrRegisterResourceByName = 0x7FFC5B0A6D80UL; // rva 0x16D80
        public const ulong ResourceSystem_FrameUpdate = 0x7FFC5B0AC010UL; // rva 0x1C010
    }
    public static class scenesystem
    {
        public const ulong CSceneAnimatableObject__GeneratePrimitives = 0x7FFC0A683520UL; // rva 0x73520
        public const ulong CSceneSkyBoxObject_DrawSkyboxArray = 0x7FFC0A75FB90UL; // rva 0x14FB90
        public const ulong CSceneSystem_RenderViewLayer_Dispatch = 0x7FFC0A6FDD80UL; // rva 0xEDD80
        public const ulong CSceneSystem_Thread_CullView = 0x7FFC0A6F92F0UL; // rva 0xE92F0
        public const ulong DrawObject_legacy = 0x7FFC0A665BC0UL; // rva 0x55BC0
        public const ulong DrawSkyboxArray = 0x7FFC0A75FB90UL; // rva 0x14FB90
        public const ulong SceneSystem__DrawAggeregateObject = 0x7FFC0A73CF50UL; // rva 0x12CF50
        public const ulong SceneSystem__DrawArrayLight = 0x7FFC0A68AAC0UL; // rva 0x7AAC0
        public const ulong SceneSystem_Thread_RenderSceneDrawList = 0x7FFC0A6FDA30UL; // rva 0xEDA30
    }
    public static class soundsystem
    {
        public const ulong SoundSystem__PlayVSound = 0x7FFC0E729840UL; // rva 0x349840
        public const ulong SoundSystem__SomeUtlSymbolFunc = 0x7FFC0E490740UL; // rva 0xB0740
    }
    public static class tier0
    {
        public const ulong Tier0__LoadKeyValues = 0x7FFC5CF49160UL; // rva 0x129160
        public const ulong Tier0__UtlBuffer = 0x7FFC5CE73F10UL; // rva 0x53F10
    }
}
