//! Single-include amalgamation header(s).
//!
//! For internal cheats it's enormously useful to have one file you can
//! `#include` (or one Rust module you can copy in) that pulls in
//! offsets + interfaces + netvars + signatures + the SDK macros all at
//! once.
//!
//! This module emits:
//!
//! - `cs2sdk.hpp` — single-include C++ amalgamation
//! - `cs2sdk.rs`  — single-file Rust module
//!
//! Both are *idempotent* — they only re-export what other emitters in
//! this run produced, they don't duplicate any data.
//!
//! ## Design choice: `#include`s vs amalgamation
//!
//! We deliberately use `#include` rather than concatenating every file's
//! contents into one mega-file. That keeps:
//!
//! 1. compile times low (the user only pays for what they touch),
//! 2. error messages pointing at the right file, and
//! 3. diffs between two builds clean.

/// Render a single-include C++ header.
///
/// `sdk_modules` is the list of module file stems that the SDK class
/// emitter wrote (e.g. `["client_dll", "engine2_dll"]`).
pub fn render_hpp(sdk_modules: &[String], build_number: Option<u32>) -> String {
    let mut s = String::new();
    s.push_str("// Auto-generated by cs2-universal-dumper. Do not edit.\n");
    s.push_str("//\n");
    s.push_str("// Single-include amalgamation header for CS2 internal cheats.\n");
    s.push_str("//\n");
    s.push_str("// Drop the `sdk/` and `signatures/` folders into your project\n");
    s.push_str("// (preserving their relative layout), add `sdk/` to your\n");
    s.push_str("// include path, and:\n");
    s.push_str("//\n");
    s.push_str("//     #include \"cs2sdk.hpp\"\n");
    s.push_str("//\n");
    s.push_str("// gets you typed schema classes, netvars, interface accessors,\n");
    s.push_str("// and pattern strings for every resolved signature.\n\n");
    s.push_str("#pragma once\n\n");
    if let Some(bn) = build_number {
        s.push_str("namespace cs2 {\n");
        s.push_str(&format!("    inline constexpr unsigned int CS2_BUILD = {bn};\n"));
        s.push_str("}\n\n");
    }
    s.push_str("// SDK macros (SCHEMA_FIELD, field_ref<T>, ...)\n");
    s.push_str("#include \"cs2sdk_macros.hpp\"\n\n");
    s.push_str("// Per-module schema classes\n");
    for m in sdk_modules {
        s.push_str(&format!("#include \"{}.hpp\"\n", m));
    }
    s.push('\n');
    s.push_str("// Typed accessors + netvars + signature patterns\n");
    s.push_str("#include \"interfaces_sdk.hpp\"\n");
    s.push_str("#include \"netvars.hpp\"\n");
    s.push_str("#include \"../signatures/signatures.hpp\"\n");
    s
}

/// Render a single-file Rust module that re-exports every emitted
/// `*.rs` consumer file.
pub fn render_rs(sig_modules_present: bool, build_number: Option<u32>) -> String {
    let mut s = String::new();
    s.push_str("// Auto-generated by cs2-universal-dumper. Do not edit.\n");
    s.push_str("//\n");
    s.push_str("// Single-file Rust amalgamation. Drop the session's `sdk/` and\n");
    s.push_str("// `signatures/` directories side-by-side and add `mod cs2sdk;`\n");
    s.push_str("// pointing at this file.\n\n");
    s.push_str("#![allow(non_upper_case_globals, non_snake_case, dead_code)]\n\n");
    if let Some(bn) = build_number {
        s.push_str(&format!("pub const CS2_BUILD: u32 = {bn};\n\n"));
    }
    if sig_modules_present {
        s.push_str("#[path = \"../signatures/signatures.rs\"] pub mod signatures;\n");
    }
    s
}
