//! Per-interface vtable header / JSON emitter.
//!
//! Output:
//!
//! - `vtables.json`            — full machine-readable dump
//! - `vtables.hpp`             — `cs2::vtables::<module>::<iface>::Method = idx`
//! - `vtables.cs`              — same shape for C# consumers
//!
//! # Method-name recovery
//!
//! When a vtable slot's RVA matches the resolved RVA of a signature in
//! the database, we use the signature's `name` instead of the generic
//! `method_<N>`. That way a hook that needs `CCSGOInput::CreateMove`
//! can either grab it via the resolved signature *or* index into the
//! vtable, and both will compile against the same identifier.

use std::collections::{BTreeMap, HashMap};
use std::fmt::Write;

use crate::analysis::VTableMap;

use super::ident::{slugify, type_ident};

/// `(module, rva) -> signature_name`, built from a [`SignatureReport`]
/// once and reused across every vtable lookup.
pub type NameOracle = HashMap<(String, u64), String>;

/// Build a `(module, rva) -> name` map from a signature report so the
/// vtable writer can label slots that match a known signature.
pub fn name_oracle_from_signatures(
    hits: &[crate::signatures::SignatureHit],
) -> NameOracle {
    let mut out = NameOracle::new();
    for h in hits {
        if let (true, Some(rva)) = (h.found, h.rva) {
            out.entry((h.module.clone(), rva)).or_insert_with(|| h.name.clone());
        }
    }
    out
}

/// JSON dump.
pub fn render_json(vts: &VTableMap, oracle: &NameOracle) -> String {
    use serde_json::json;
    let mut by_module = BTreeMap::new();
    for (module, ifaces) in vts {
        let mut entries = BTreeMap::new();
        for (iface, info) in ifaces {
            let methods: Vec<_> = info
                .methods
                .iter()
                .enumerate()
                .map(|(idx, m)| {
                    let name = oracle
                        .get(&(m.module.clone(), m.rva))
                        .cloned()
                        .unwrap_or_else(|| format!("method_{idx}"));
                    json!({
                        "index":  idx,
                        "name":   name,
                        "module": m.module,
                        "rva":    format!("0x{:X}", m.rva),
                    })
                })
                .collect();
            entries.insert(
                iface,
                json!({
                    "vtable_module": info.vtable_module,
                    "vtable_rva":    format!("0x{:X}", info.vtable_rva),
                    "rtti_class":    info.rtti_class,
                    "method_count":  info.methods.len(),
                    "methods":       methods,
                }),
            );
        }
        by_module.insert(module, entries);
    }
    serde_json::to_string_pretty(&by_module).unwrap_or_else(|_| "{}".into())
}

/// C++ header.
pub fn render_hpp(vts: &VTableMap, oracle: &NameOracle, build_number: Option<u32>) -> String {
    let mut s = String::new();
    s.push_str("// Auto-generated by cs2-universal-dumper. Do not edit.\n");
    s.push_str("//\n");
    s.push_str("// Per-interface virtual function table indices. Use as:\n");
    s.push_str("//\n");
    s.push_str("//     auto** vt = *reinterpret_cast<void***>(iface);\n");
    s.push_str("//     auto fn  = reinterpret_cast<Sig_t>(\n");
    s.push_str("//         vt[cs2::vtables::client_dll::Source2Client002::CreateMove]);\n");
    s.push_str("//\n");
    s.push_str("// Slots whose target RVA matches a signature in the database\n");
    s.push_str("// are named after that signature; otherwise they are emitted\n");
    s.push_str("// as `method_<N>` and you can use the index directly.\n");
    s.push_str("\n#pragma once\n");
    s.push_str("#include <cstddef>\n#include <cstdint>\n\n");
    if let Some(bn) = build_number {
        writeln!(s, "namespace cs2::vtables {{ inline constexpr std::uint32_t CS2_BUILD = {bn}; }}\n").ok();
    }
    s.push_str("namespace cs2::vtables {\n\n");
    for (module, ifaces) in vts {
        writeln!(s, "    namespace {} {{", slugify(module)).ok();
        for (iface, info) in ifaces {
            let ns = info
                .rtti_class
                .as_deref()
                .map(sanitize_ident)
                .unwrap_or_else(|| type_ident(iface));
            let banner_class = info.rtti_class.as_deref().unwrap_or("<no RTTI>");
            writeln!(
                s,
                "        // {} (iface: {}) | vtable @ {}+0x{:X} ({} methods)",
                banner_class,
                iface,
                info.vtable_module,
                info.vtable_rva,
                info.methods.len(),
            ).ok();
            writeln!(s, "        namespace {} {{", ns).ok();
            for (idx, m) in info.methods.iter().enumerate() {
                let name = oracle
                    .get(&(m.module.clone(), m.rva))
                    .map(|s| sanitize_ident(s))
                    .unwrap_or_else(|| format!("method_{idx}"));
                writeln!(
                    s,
                    "            inline constexpr std::ptrdiff_t {:<48} = {:>4}; // {} + 0x{:X}",
                    name, idx, m.module, m.rva,
                ).ok();
            }
            writeln!(s, "        }} // namespace {}\n", ns).ok();
        }
        writeln!(s, "    }} // namespace {}\n", slugify(module)).ok();
    }
    s.push_str("} // namespace cs2::vtables\n");
    s
}

/// C# header — same shape, static class hierarchy.
pub fn render_cs(vts: &VTableMap, oracle: &NameOracle, build_number: Option<u32>) -> String {
    let mut s = String::new();
    s.push_str("// Auto-generated by cs2-universal-dumper. Do not edit.\n");
    s.push_str("namespace CS2Sdk.VTables;\n\n");
    s.push_str("public static class VTables\n{\n");
    if let Some(bn) = build_number {
        writeln!(s, "    public const uint CS2_BUILD = {bn}u;\n").ok();
    }
    for (module, ifaces) in vts {
        writeln!(s, "    public static class {}", slugify(module)).ok();
        writeln!(s, "    {{").ok();
        for (iface, info) in ifaces {
            let ns = info
                .rtti_class
                .as_deref()
                .map(sanitize_ident)
                .unwrap_or_else(|| slugify(iface));
            if let Some(rtti) = info.rtti_class.as_deref() {
                writeln!(s, "        // {} (iface: {})", rtti, iface).ok();
            }
            writeln!(s, "        public static class {}", ns).ok();
            writeln!(s, "        {{").ok();
            for (idx, m) in info.methods.iter().enumerate() {
                let name = oracle
                    .get(&(m.module.clone(), m.rva))
                    .map(|s| sanitize_ident(s))
                    .unwrap_or_else(|| format!("method_{idx}"));
                writeln!(
                    s,
                    "            public const nint {:<48} = {:>4}; // {} + 0x{:X}",
                    name, idx, m.module, m.rva,
                ).ok();
            }
            writeln!(s, "        }}\n").ok();
        }
        writeln!(s, "    }}\n").ok();
    }
    s.push_str("}\n");
    s
}

/// Strip qualifications and turn `Foo::Bar` into `Foo_Bar` so the
/// signature name is usable as a C++/C# identifier.
fn sanitize_ident(raw: &str) -> String {
    let mut s = String::with_capacity(raw.len());
    for c in raw.chars() {
        if c.is_ascii_alphanumeric() || c == '_' {
            s.push(c);
        } else {
            s.push('_');
        }
    }
    if s.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) {
        s.insert(0, '_');
    }
    s
}
