//! Multi-language emitters for resolved signatures.
//!
//! We already emit a hand-formatted [`signatures.json`].  This module adds
//! sibling files in the same set of languages the offset pass produces
//! (`.hpp`, `.rs`) so consumers can drop the file straight into
//! their project without writing a converter.
//!
//! Output is intentionally minimal — one constant per signature, named
//! after the signature, valued with the IDA-style byte **pattern**
//! (auto-synthesised at the resolved RVA when available, otherwise the
//! database pattern).  Consumers do their own pattern scanning at
//! runtime, which is build-portable and avoids leaking absolute
//! addresses into compiled artefacts.

use std::collections::BTreeMap;

use super::SignatureHit;

/// Group resolved signatures by module so each emitter can render them as
/// nested namespaces / modules / classes.
fn grouped<'a>(hits: &'a [SignatureHit]) -> BTreeMap<&'a str, Vec<&'a SignatureHit>> {
    let mut out: BTreeMap<&'a str, Vec<&'a SignatureHit>> = BTreeMap::new();
    for h in hits.iter().filter(|h| h.found) {
        out.entry(h.module.as_str()).or_default().push(h);
    }
    for v in out.values_mut() {
        v.sort_by(|a, b| a.name.cmp(&b.name));
    }
    out
}

fn ident(name: &str) -> String {
    let mut s = String::with_capacity(name.len());
    for c in name.chars() {
        if c.is_ascii_alphanumeric() || c == '_' {
            s.push(c);
        } else {
            s.push('_');
        }
    }
    if s.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) {
        s.insert(0, '_');
    }
    s
}

fn module_ident(module: &str) -> String {
    ident(module.trim_end_matches(".dll"))
}

fn markdown_cell(value: &str) -> String {
    value
        .replace('\r', "")
        .replace('\n', "\\n")
        .replace('|', "\\|")
        .replace('`', "'")
}

/// Pick the pattern string we want to emit for a given hit.  We prefer
/// the auto-synthesised IDA pattern at the resolved RVA (handles
/// `StringRef` entries whose database `pattern` is text, not bytes),
/// and fall back to the database pattern when `.text` was outside the
/// scanned range (rare).
fn emit_pattern(h: &SignatureHit) -> Option<&str> {
    if let Some(p) = h.pattern_synth.as_deref() {
        return Some(p);
    }
    // Skip StringRef when no synth — its `pattern` field is the literal
    // string, not a byte pattern, so it would never scan-match.
    if h.resolve == "StringRef" {
        return None;
    }
    Some(h.pattern.as_str())
}

/// C++ header with one `inline constexpr` IDA-style pattern per
/// signature, namespaced per module.  In addition to the pattern
/// strings we emit a sibling `using <Name>_t = void(__fastcall*)(...);`
/// function-pointer typedef for every signature so consumers can write
/// `auto fn = reinterpret_cast<cs2::fn::client_dll::CreateMove_t>(scan(...));`
/// without re-typing the calling convention.  We don't know the real
/// argument list (this would require type recovery from IDA / a
/// debugger), so the typedef is intentionally generic
/// (`void __fastcall(void*, ...)`) and the consumer can
/// `reinterpret_cast` it to a more specific shape when they hook.
pub fn render_hpp(hits: &[SignatureHit]) -> String {
    let mut s = String::new();
    s.push_str("// Auto-generated by cs2-universal-dumper. Do not edit.\n");
    s.push_str("// Each constant is an IDA-style byte pattern; scan it at\n");
    s.push_str("// runtime with your favourite pattern scanner.  The\n");
    s.push_str("// `cs2::fn::<module>::<Name>_t` typedef next to it gives a\n");
    s.push_str("// generic __fastcall function-pointer shape so consumers\n");
    s.push_str("// can `reinterpret_cast` the scan result without re-typing\n");
    s.push_str("// the calling convention.\n");
    s.push_str("#pragma once\n\n#include <string_view>\n\n");
    s.push_str("namespace cs2::signatures {\n");
    for (module, items) in grouped(hits) {
        s.push_str(&format!("    namespace {} {{\n", module_ident(&module)));
        for h in &items {
            let Some(pattern) = emit_pattern(h) else { continue };
            s.push_str(&format!(
                "        inline constexpr std::string_view {} = \"{}\";\n",
                ident(&h.name),
                pattern,
            ));
        }
        s.push_str("    }\n");
    }
    s.push_str("}\n\n");

    // Function-pointer typedef table.  Mirrors the namespace layout of
    // `cs2::signatures::<module>` but lives under `cs2::fn::<module>`
    // so the two stay decoupled (you can include this header purely
    // for the typedefs even when scanning yourself).
    s.push_str("namespace cs2::fn {\n");
    for (module, items) in grouped(hits) {
        s.push_str(&format!("    namespace {} {{\n", module_ident(&module)));
        for h in &items {
            if emit_pattern(h).is_none() { continue; }
            // Generic __fastcall(void* this_or_arg0, ...) shape.
            // Variadic gives consumers the freedom to call with any
            // arg list before reinterpret_cast'ing to the real proto.
            s.push_str(&format!(
                "        using {}_t = void(__fastcall*)(void*, ...);\n",
                ident(&h.name),
            ));
        }
        s.push_str("    }\n");
    }
    s.push_str("}\n");
    s
}

/// Rust module per game module, with `pub const &str` patterns.
pub fn render_rs(hits: &[SignatureHit]) -> String {
    let mut s = String::new();
    s.push_str("// Auto-generated by cs2-universal-dumper. Do not edit.\n");
    s.push_str("// Each constant is an IDA-style byte pattern; scan it at\n");
    s.push_str("// runtime with your favourite pattern scanner.\n");
    s.push_str("#![allow(non_upper_case_globals, non_snake_case, dead_code)]\n\n");
    for (module, items) in grouped(hits) {
        s.push_str(&format!("pub mod {} {{\n", module_ident(module)));
        for h in items {
            let Some(pattern) = emit_pattern(h) else { continue };
            s.push_str(&format!(
                "    pub const {}: &str = \"{}\";\n",
                ident(&h.name),
                pattern,
            ));
        }
        s.push_str("}\n\n");
    }
    s
}

/// Compact human-readable summary used by `SIGNATURES.md`.
pub fn render_markdown(hits: &[SignatureHit]) -> String {
    let mut s = String::new();
    s.push_str("# CS2 Signatures\n\n");
    s.push_str("_This file is regenerated on every successful run of `cs2-sdk`._\n\n");
    let groups = grouped(hits);
    let total_found = hits.iter().filter(|h| h.found).count();
    let total = hits.len();
    s.push_str(&format!(
        "**{}/{} signatures resolved across {} module(s).**\n\n",
        total_found,
        total,
        groups.len(),
    ));
    for (module, items) in groups {
        s.push_str(&format!("## `{}`\n\n", module));
        s.push_str("| Name | Resolve | VA | RVA | Pattern |\n");
        s.push_str("| --- | --- | --- | --- | --- |\n");
        for h in items {
            s.push_str(&format!(
                "| `{}` | `{}` | `0x{:X}` | `0x{:X}` | `{}` |\n",
                markdown_cell(&h.name),
                markdown_cell(&h.resolve),
                h.va.unwrap_or(0),
                h.rva.unwrap_or(0),
                markdown_cell(&h.pattern),
            ));
        }
        s.push('\n');
    }
    s
}
