// Auto-generated by cs2-universal-dumper. Do not edit.
//
// module:        networksystem.dll
// classes:       1
// enums:         0
// build_number:  14155
// generated_at:  2026-04-25T13:42:39.261872400+00:00
//
// Use:
//   auto* pawn = reinterpret_cast<C_CSPlayerPawn*>(addr);
//   pawn->m_iHealth() = 100;

#pragma once
#include "cs2sdk_macros.hpp"

namespace cs2::sdk::networksystem {

    inline constexpr std::uint32_t CS2_BUILD = 14155;

    class ChangeAccessorFieldPathIndex_t;

    // ChangeAccessorFieldPathIndex_t
    //   fields: 1
    class ChangeAccessorFieldPathIndex_t {
    public:
        SCHEMA_FIELD(std::int32_t                    , m_Value                                         , 0x0) // int32
    };

} // namespace cs2::sdk::networksystem
