// Auto-generated by cs2-universal-dumper. Do not edit.
//
// module:        soundsystem.dll
// classes:       136
// enums:         26
// build_number:  14152
// generated_at:  2026-04-21T22:47:42.668580400+00:00
//
// Use:
//   auto* pawn = reinterpret_cast<C_CSPlayerPawn*>(addr);
//   pawn->m_iHealth() = 100;

#pragma once
#include "cs2sdk_macros.hpp"

namespace cs2::sdk::soundsystem {

    inline constexpr std::uint32_t CS2_BUILD = 14152;

    class CVMixInputBase;
    class CVoiceContainerBlender;
    class CVMixPitchShiftProcessorDesc;
    class VMixFreeverbDesc_t;
    class CVoiceContainerStaticAdditiveSynth;
    class CVoiceContainerStaticAdditiveSynth;
    class CSosGroupActionOcclusionSchema;
    class CVoiceContainerRandomSampler;
    class CVMixSteamAudioDirectProcessorDesc;
    class CVMixSteamAudioHRTFProcessorDesc;
    class CVoiceContainerDefault;
    class CVSound;
    class CDSPPresetMixgroupModifierTable;
    class CSosGroupActionSoundeventClusterSchema;
    class CSosGroupActionSetSoundeventParameterSchema;
    class CSoundContainerReference;
    class CVoiceContainerNull;
    class VMixSubgraphSwitchDesc_t;
    class CVoiceContainerAnalysisBase;
    class CSosGroupActionSoundeventMinMaxValuesSchema;
    class CVMixEnvelopeProcessorDesc;
    class CVMixCommand;
    class SamplerVoice_t;
    class CVMixControlInput;
    class CVMixBoxverbProcessorDesc;
    class CVMixDynamicsCompressorProcessorDesc;
    class VMixPannerDesc_t;
    class CSosGroupActionSoundeventPrioritySchema;
    class CVoiceContainerRealtimeFMSineWave;
    class SelectedEditItemInfo_t;
    class VMixModDelayDesc_t;
    class CSndSeqInstSndEvtSchema;
    class CVMixNameInputMeter;
    class CSndSeqInstruments;
    class CVMixDynamics3BandProcessorDesc;
    class VMixBoxverbDesc_t;
    class CSosGroupActionSchema;
    class CSosSoundEventGroupSchema;
    class CSndSeqInstMidiSampler;
    class CSndSeqInstBaseSchema;
    class VMixDynamics3BandDesc_t;
    class CVMixEQ8ProcessorDesc;
    class CDSPMixgroupModifier;
    class CAudioMorphData;
    class VMixDualCompressorDesc_t;
    class CVoiceContainerStaticAdditiveSynth;
    class CVoiceContainerShapedNoise;
    class CDspPresetModifierList;
    class CVoiceContainerBase;
    class CVMixDiffusorProcessorDesc;
    class CVMixUtilityProcessorDesc;
    class CVoiceContainerGranulator;
    class CVMixPresetDSPProcessorDesc;
    class VMixDelayDesc_t;
    class VMixEQ8Desc_t;
    class CVMixDynamicsProcessorDesc;
    class CVMixGraphDescData;
    class CVoiceContainerLoopXFade;
    class VMixPresetDSPDesc_t;
    class CAudioPhonemeTag;
    class CVMixControlInputArray;
    class CVMixNameInput;
    class CSosGroupActionSoundeventCountSchema;
    class CVoiceContainerEnvelopeAnalyzer;
    class CVMixBaseProcessorDesc;
    class CVMixImpulseResponseInput;
    class CVMixSteamAudioHybridReverbProcessorDesc;
    class CSoundEventMetaData;
    class VMixPitchShiftDesc_t;
    class CVMixControlOutput;
    class CVMixModDelayProcessorDesc;
    class CVMixShaperProcessorDesc;
    class CVMixAutomaticControlInput;
    class CAudioEmphasisSample;
    class CVMixOscProcessorDesc;
    class CVMixCurveHeader;
    class CVoiceContainerGenerator;
    class CVoiceContainerSet;
    class VMixConvolutionDesc_t;
    class CVoiceContainerSetElement;
    class CVoiceContainerAsyncGenerator;
    class CSoundInfoHeader;
    class SosEditItemInfo_t;
    class CVMixFlangerProcessorDesc;
    class CVMixEffectChainProcessorDesc;
    class KeyGroup_t;
    class CVMixFreeverbProcessorDesc;
    class VMixPlateverbDesc_t;
    class CVMixConvolutionProcessorDesc;
    class CSoundContainerReferenceArray;
    class CVMixFilterProcessorDesc;
    class CVMixAdditionalOutput;
    class CVoiceContainerTapePlayer;
    class CVMixSubgraphSwitchProcessorDesc;
    class VMixDiffusorDesc_t;
    class CVMixSteamAudioPathingProcessorDesc;
    class CVMixPannerProcessorDesc;
    class VMixDynamicsCompressorDesc_t;
    class CVMixStereoDelayProcessorDesc;
    class VMixShaperDesc_t;
    class VMixEnvelopeDesc_t;
    class CAudioSentence;
    class CVoiceContainerParameterBlender;
    class CVMixAudioMeter;
    class CVMixVocoderProcessorDesc;
    class CSosGroupActionLimitSchema;
    class CVoiceContainerAmpedDecayingSineWave;
    class CVoiceContainerEnvelope;
    class VMixAutoFilterDesc_t;
    class VMixDynamicsBand_t;
    class VMixEffectChainDesc_t;
    class CVMixPlateReverbProcessorDesc;
    class CVoiceContainerMultiBlender;
    class CVMixVsndInput;
    class CVoiceContainerStaticAdditiveSynth;
    class VelocityZone_t;
    class CVoiceContainerSelector;
    class CSosGroupActionTimeBlockLimitSchema;
    class CSosGroupActionMemberCountEnvelopeSchema;
    class CVMixDualCompressorProcessorDesc;
    class CVoiceContainerSwitch;
    class CVMixControlMeter;
    class CVoiceContainerEnum;
    class CSosGroupActionTimeLimitSchema;
    class VMixVocoderDesc_t;
    class VMixUtilityDesc_t;
    class CVoiceContainerLoopTrigger;
    class CVoiceContainerDecayingSineWave;
    class CVMixDelayProcessorDesc;
    class CVMixBoxverb2ProcessorDesc;
    class VMixFilterDesc_t;
    class VMixOscDesc_t;
    class CVMixAutoFilterProcessorDesc;
    class ISndSeqInstruments;
    class VMixFlangerDesc_t;
    class VMixDynamicsDesc_t;

    enum class SndSeqInstrumentType_t : std::uint32_t {
        eSndSeqInstNull = 0x0,
        eSndSeqInstSndEvt = 0x1,
        eSndSeqInstMidiSampler = 0x2,
    };

    enum class EMode_t : std::uint32_t {
        Peak = 0x0,
        RMS = 0x1,
    };

    enum class VMixGraphCommandID_t : std::uint32_t {
        CMD_INVALID = 0xFFFFFFFFFFFFFFFF,
        CMD_CONTROL_INPUT_STORE = 0x1,
        CMD_CONTROL_INPUT_STORE_DB = 0x2,
        CMD_CONTROL_TRANSIENT_INPUT_STORE = 0x3,
        CMD_CONTROL_TRANSIENT_INPUT_RESET = 0x4,
        CMD_CONTROL_OUTPUT_STORE = 0x5,
        CMD_CONTROL_EVALUATE_CURVE = 0x6,
        CMD_CONTROL_COPY = 0x7,
        CMD_CONTROL_COND_COPY_IF_NEGATIVE = 0x8,
        CMD_CONTROL_REMAP_LINEAR = 0x9,
        CMD_CONTROL_REMAP_SINE = 0xA,
        CMD_CONTROL_REMAP_LOGLINEAR = 0xB,
        CMD_CONTROL_MAX = 0xC,
        CMD_CONTROL_RESET_TIMER = 0xD,
        CMD_CONTROL_INCREMENT_TIMER = 0xE,
        CMD_CONTROL_EVAL_ENVELOPE = 0xF,
        CMD_CONTROL_SINE_BLEND = 0x10,
        CMD_PROCESSOR_SET_CONTROL_VALUE = 0x11,
        CMD_PROCESSOR_SET_NAME_INPUT = 0x12,
        CMD_PROCESSOR_SET_CONTROL_ARRAYVALUE = 0x13,
        CMD_PROCESSOR_STORE_CONTROL_VALUE = 0x14,
        CMD_PROCESSOR_SET_VSND_VALUE = 0x15,
        CMD_SUBMIX_PROCESS = 0x16,
        CMD_SUBMIX_GENERATE = 0x17,
        CMD_SUBMIX_GENERATE_SIDECHAIN = 0x18,
        CMD_SUBMIX_DEBUG = 0x19,
        CMD_SUBMIX_MIX2x1 = 0x1A,
        CMD_SUBMIX_OUTPUT = 0x1B,
        CMD_SUBMIX_OUTPUTx2 = 0x1C,
        CMD_SUBMIX_COPY = 0x1D,
        CMD_SUBMIX_ACCUMULATE = 0x1E,
        CMD_SUBMIX_METER = 0x1F,
        CMD_SUBMIX_METER_SPECTRUM = 0x20,
        CMD_IMPULSERESPONSE_INPUT_STORE = 0x21,
        CMD_PROCESSOR_SET_IMPULSERESPONSE_VALUE = 0x22,
        CMD_REMAP_VSND_TO_IMPULSERESPONSE = 0x23,
        CMD_IMPULSERESPONSE_RESET = 0x24,
        CMD_BLEND_VSNDS_TO_IMPULSERESPONSE = 0x25,
        CMD_IMPULSERESPONSE_DELAY = 0x26,
    };

    enum class EWaveform : std::uint8_t {
        Sine = 0x0,
        Square = 0x1,
        Saw = 0x2,
        Triangle = 0x3,
        Noise = 0x4,
    };

    enum class VMixLFOShape_t : std::uint32_t {
        LFO_SHAPE_SINE = 0x0,
        LFO_SHAPE_SQUARE = 0x1,
        LFO_SHAPE_TRI = 0x2,
        LFO_SHAPE_SAW = 0x3,
        LFO_SHAPE_NOISE = 0x4,
    };

    enum class VMixFilterType_t : std::uint16_t {
        FILTER_UNKNOWN = 0xFFFFFFFFFFFFFFFF,
        FILTER_LOWPASS = 0x0,
        FILTER_HIGHPASS = 0x1,
        FILTER_BANDPASS = 0x2,
        FILTER_NOTCH = 0x3,
        FILTER_PEAKING_EQ = 0x4,
        FILTER_LOW_SHELF = 0x5,
        FILTER_HIGH_SHELF = 0x6,
        FILTER_ALLPASS = 0x7,
        FILTER_PASSTHROUGH = 0x8,
    };

    enum class SosActionStopType_t : std::uint32_t {
        SOS_STOPTYPE_NONE = 0x0,
        SOS_STOPTYPE_TIME = 0x1,
        SOS_STOPTYPE_OPVAR = 0x2,
    };

    enum class SndSeqTrackPlaybackType_t : std::uint32_t {
        eSndSeqTrackPlaybackTypeStep = 0x0,
        eSndSeqTrackPlaybackTypeFwd = 0x1,
    };

    enum class SosEditItemType_t : std::uint32_t {
        SOS_EDIT_ITEM_TYPE_SOUNDEVENTS = 0x0,
        SOS_EDIT_ITEM_TYPE_SOUNDEVENT = 0x1,
        SOS_EDIT_ITEM_TYPE_LIBRARYSTACKS = 0x2,
        SOS_EDIT_ITEM_TYPE_STACK = 0x3,
        SOS_EDIT_ITEM_TYPE_OPERATOR = 0x4,
        SOS_EDIT_ITEM_TYPE_FIELD = 0x5,
    };

    enum class SndSeqQuantizeType_t : std::uint32_t {
        eSndSeqQuantizeInvalid = 0xFFFFFFFFFFFFFFFF,
        eSndSeqQuantizeNone = 0x0,
        eSndSeqQuantizeBeat = 0x1,
        eSndSeqQuantizeBar = 0x2,
        eSndSeqQuantizeSequence = 0x3,
        eSndSeqQuantizeSeek = 0x4,
        eSndSeqQuantizeReset = 0x5,
    };

    enum class PlayBackMode_t : std::uint32_t {
        Random = 0x0,
        RandomNoRepeats = 0x1,
        RandomAvoidLast = 0x2,
        Sequential = 0x3,
        RandomWeights = 0x4,
    };

    enum class SosGroupFieldBehavior_t : std::uint32_t {
        kIgnore = 0x0,
        kBranch = 0x1,
        kMatch = 0x2,
    };

    enum class SndSeqSyncType_t : std::uint32_t {
        eSndSeqSyncTypeNone = 0x0,
        eSndSeqSyncTypeWait = 0x1,
        eSndSeqSyncTypeSeek = 0x2,
    };

    enum class soundlevel_t : std::uint32_t {
        SNDLVL_NONE = 0x0,
        SNDLVL_20dB = 0x14,
        SNDLVL_25dB = 0x19,
        SNDLVL_30dB = 0x1E,
        SNDLVL_35dB = 0x23,
        SNDLVL_40dB = 0x28,
        SNDLVL_45dB = 0x2D,
        SNDLVL_50dB = 0x32,
        SNDLVL_55dB = 0x37,
        SNDLVL_IDLE = 0x3C,
        SNDLVL_60dB = 0x3C,
        SNDLVL_65dB = 0x41,
        SNDLVL_STATIC = 0x42,
        SNDLVL_70dB = 0x46,
        SNDLVL_NORM = 0x4B,
        SNDLVL_75dB = 0x4B,
        SNDLVL_80dB = 0x50,
        SNDLVL_TALKING = 0x50,
        SNDLVL_85dB = 0x55,
        SNDLVL_90dB = 0x5A,
        SNDLVL_95dB = 0x5F,
        SNDLVL_100dB = 0x64,
        SNDLVL_105dB = 0x69,
        SNDLVL_110dB = 0x6E,
        SNDLVL_120dB = 0x78,
        SNDLVL_130dB = 0x82,
        SNDLVL_GUNFIRE = 0x8C,
        SNDLVL_140dB = 0x8C,
        SNDLVL_150dB = 0x96,
        SNDLVL_180dB = 0xB4,
    };

    enum class VMixPannerType_t : std::uint32_t {
        PANNER_TYPE_LINEAR = 0x0,
        PANNER_TYPE_EQUAL_POWER = 0x1,
    };

    enum class VMixChannelOperation_t : std::uint32_t {
        VMIX_CHAN_STEREO = 0x0,
        VMIX_CHAN_LEFT = 0x1,
        VMIX_CHAN_RIGHT = 0x2,
        VMIX_CHAN_SWAP = 0x3,
        VMIX_CHAN_MONO = 0x4,
        VMIX_CHAN_MID_SIDE = 0x5,
    };

    enum class EMidiNote : std::uint8_t {
        C = 0x0,
        C_Sharp = 0x1,
        D = 0x2,
        D_Sharp = 0x3,
        E = 0x4,
        F = 0x5,
        F_Sharp = 0x6,
        G = 0x7,
        G_Sharp = 0x8,
        A = 0x9,
        A_Sharp = 0xA,
        B = 0xB,
        Count = 0xC,
    };

    enum class SndSeqRegionType_t : std::uint32_t {
        eSndSeqRegionTypeNull = 0x0,
        eSndSeqRegionTypeSndEvt = 0x1,
        eSndSeqRegionTypeMidiSeq = 0x2,
    };

    enum class CVSoundFormat_t : std::uint8_t {
        PCM16 = 0x0,
        PCM8 = 0x1,
        MP3 = 0x2,
        ADPCM = 0x3,
    };

    enum class VMixFilterSlope_t : std::uint8_t {
        FILTER_SLOPE_1POLE_6dB = 0x0,
        FILTER_SLOPE_1POLE_12dB = 0x1,
        FILTER_SLOPE_1POLE_18dB = 0x2,
        FILTER_SLOPE_1POLE_24dB = 0x3,
        FILTER_SLOPE_12dB = 0x4,
        FILTER_SLOPE_24dB = 0x5,
        FILTER_SLOPE_36dB = 0x6,
        FILTER_SLOPE_48dB = 0x7,
        FILTER_SLOPE_MAX = 0x7,
    };

    enum class SndSeqPlayerType_t : std::uint32_t {
        eSndSeqPlayerNull = 0x0,
        eSndSeqPlayerSndEvt = 0x1,
        eSndSeqPlayerMidiSeq = 0x2,
    };

    enum class SosActionLimitSortType_t : std::uint32_t {
        SOS_LIMIT_SORTTYPE_HIGHEST = 0x0,
        SOS_LIMIT_SORTTYPE_LOWEST = 0x1,
    };

    enum class VMixSubgraphSwitchInterpolationType_t : std::uint32_t {
        SUBGRAPH_INTERPOLATION_TEMPORAL_CROSSFADE = 0x0,
        SUBGRAPH_INTERPOLATION_TEMPORAL_FADE_OUT = 0x1,
        SUBGRAPH_INTERPOLATION_KEEP_LAST_SUBGRAPH_RUNNING = 0x2,
    };

    enum class SosGroupType_t : std::uint32_t {
        SOS_GROUPTYPE_DYNAMIC = 0x0,
        SOS_GROUPTYPE_STATIC = 0x1,
    };

    enum class SosActionSetParamSortType_t : std::uint32_t {
        SOS_SETPARAM_SORTTYPE_HIGHEST = 0x0,
        SOS_SETPARAM_SORTTYPE_LOWEST = 0x1,
    };

    enum class SndSeqMidiStatusType_t : std::uint32_t {
        SndSeqMidiStatusNoteOff = 0x8,
        SndSeqMidiStatusNoteOn = 0x9,
        SndSeqMidiStatusKeyPressure = 0xA,
        SndSeqMidiStatusCtrlChange = 0xB,
        SndSeqMidiStatusProgramChange = 0xC,
        SndSeqMidiStatusChannelPressure = 0xD,
        SndSeqMidiStatusPitchBend = 0xE,
    };

    // CVMixInputBase
    //   fields: 1
    class CVMixInputBase {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVoiceContainerBlender
    //   fields: 0
    class CVoiceContainerBlender {
    public:
    };

    // CVMixPitchShiftProcessorDesc
    //   parent: soundsystem_lowlevel
    //   fields: 0
    class CVMixPitchShiftProcessorDesc : public soundsystem_lowlevel {
    public:
    };

    // VMixFreeverbDesc_t
    //   fields: 1
    class VMixFreeverbDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVoiceContainerStaticAdditiveSynth::CHarmonic
    //   fields: 1
    class CVoiceContainerStaticAdditiveSynth {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVoiceContainerStaticAdditiveSynth::CTone
    //   fields: 1
    class CVoiceContainerStaticAdditiveSynth {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CSosGroupActionOcclusionSchema
    //   fields: 0
    class CSosGroupActionOcclusionSchema {
    public:
    };

    // CVoiceContainerRandomSampler
    //   fields: 0
    class CVoiceContainerRandomSampler {
    public:
    };

    // CVMixSteamAudioDirectProcessorDesc
    //   fields: 0
    class CVMixSteamAudioDirectProcessorDesc {
    public:
    };

    // CVMixSteamAudioHRTFProcessorDesc
    //   fields: 0
    class CVMixSteamAudioHRTFProcessorDesc {
    public:
    };

    // CVoiceContainerDefault
    //   parent: soundsystem_voicecontainers
    //   fields: 0
    class CVoiceContainerDefault : public soundsystem_voicecontainers {
    public:
    };

    // CVSound
    //   fields: 1
    class CVSound {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CDSPPresetMixgroupModifierTable
    //   fields: 1
    class CDSPPresetMixgroupModifierTable {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CSosGroupActionSoundeventClusterSchema
    //   parent: xL��
    //   fields: 0
    class CSosGroupActionSoundeventClusterSchema : public xL {
    public:
    };

    // CSosGroupActionSetSoundeventParameterSchema
    //   parent: xL��
    //   fields: 0
    class CSosGroupActionSetSoundeventParameterSchema : public xL {
    public:
    };

    // CSoundContainerReference
    //   fields: 1
    class CSoundContainerReference {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVoiceContainerNull
    //   parent: soundsystem_voicecontainers
    //   fields: 0
    class CVoiceContainerNull : public soundsystem_voicecontainers {
    public:
    };

    // VMixSubgraphSwitchDesc_t
    //   fields: 1
    class VMixSubgraphSwitchDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVoiceContainerAnalysisBase
    //   fields: 1
    class CVoiceContainerAnalysisBase {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CSosGroupActionSoundeventMinMaxValuesSchema
    //   parent: xL��
    //   fields: 0
    class CSosGroupActionSoundeventMinMaxValuesSchema : public xL {
    public:
    };

    // CVMixEnvelopeProcessorDesc
    //   parent: soundsystem_lowlevel
    //   fields: 0
    class CVMixEnvelopeProcessorDesc : public soundsystem_lowlevel {
    public:
    };

    // CVMixCommand
    //   fields: 1
    class CVMixCommand {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // SamplerVoice_t
    //   fields: 0
    class SamplerVoice_t {
    public:
    };

    // CVMixControlInput
    //   fields: 0
    class CVMixControlInput {
    public:
    };

    // CVMixBoxverbProcessorDesc
    //   parent: `B?e�
    //   fields: 0
    class CVMixBoxverbProcessorDesc : public anonymous {
    public:
    };

    // CVMixDynamicsCompressorProcessorDesc
    //   fields: 0
    class CVMixDynamicsCompressorProcessorDesc {
    public:
    };

    // VMixPannerDesc_t
    //   fields: 1
    class VMixPannerDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CSosGroupActionSoundeventPrioritySchema
    //   parent: xL��
    //   fields: 0
    class CSosGroupActionSoundeventPrioritySchema : public xL {
    public:
    };

    // CVoiceContainerRealtimeFMSineWave
    //   fields: 0
    class CVoiceContainerRealtimeFMSineWave {
    public:
    };

    // SelectedEditItemInfo_t
    //   fields: 1
    class SelectedEditItemInfo_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // VMixModDelayDesc_t
    //   fields: 1
    class VMixModDelayDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CSndSeqInstSndEvtSchema
    //   parent: xL��
    //   fields: 0
    class CSndSeqInstSndEvtSchema : public xL {
    public:
    };

    // CVMixNameInputMeter
    //   parent: soundsystem_lowlevel
    //   fields: 0
    class CVMixNameInputMeter : public soundsystem_lowlevel {
    public:
    };

    // CSndSeqInstruments
    //   parent: xL��
    //   fields: 0
    class CSndSeqInstruments : public xL {
    public:
    };

    // CVMixDynamics3BandProcessorDesc
    //   fields: 0
    class CVMixDynamics3BandProcessorDesc {
    public:
    };

    // VMixBoxverbDesc_t
    //   fields: 1
    class VMixBoxverbDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CSosGroupActionSchema
    //   fields: 0
    class CSosGroupActionSchema {
    public:
    };

    // CSosSoundEventGroupSchema
    //   fields: 1
    class CSosSoundEventGroupSchema {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CSndSeqInstMidiSampler
    //   fields: 0
    class CSndSeqInstMidiSampler {
    public:
    };

    // CSndSeqInstBaseSchema
    //   fields: 0
    class CSndSeqInstBaseSchema {
    public:
    };

    // VMixDynamics3BandDesc_t
    //   fields: 1
    class VMixDynamics3BandDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVMixEQ8ProcessorDesc
    //   parent: soundsystem_lowlevel
    //   fields: 0
    class CVMixEQ8ProcessorDesc : public soundsystem_lowlevel {
    public:
    };

    // CDSPMixgroupModifier
    //   fields: 1
    class CDSPMixgroupModifier {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CAudioMorphData
    //   fields: 1
    class CAudioMorphData {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // VMixDualCompressorDesc_t
    //   fields: 1
    class VMixDualCompressorDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVoiceContainerStaticAdditiveSynth
    //   fields: 0
    class CVoiceContainerStaticAdditiveSynth {
    public:
    };

    // CVoiceContainerShapedNoise
    //   fields: 0
    class CVoiceContainerShapedNoise {
    public:
    };

    // CDspPresetModifierList
    //   fields: 1
    class CDspPresetModifierList {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVoiceContainerBase
    //   fields: 0
    class CVoiceContainerBase {
    public:
    };

    // CVMixDiffusorProcessorDesc
    //   parent: soundsystem_lowlevel
    //   fields: 0
    class CVMixDiffusorProcessorDesc : public soundsystem_lowlevel {
    public:
    };

    // CVMixUtilityProcessorDesc
    //   fields: 0
    class CVMixUtilityProcessorDesc {
    public:
    };

    // CVoiceContainerGranulator
    //   fields: 0
    class CVoiceContainerGranulator {
    public:
    };

    // CVMixPresetDSPProcessorDesc
    //   parent: soundsystem_lowlevel
    //   fields: 0
    class CVMixPresetDSPProcessorDesc : public soundsystem_lowlevel {
    public:
    };

    // VMixDelayDesc_t
    //   fields: 1
    class VMixDelayDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // VMixEQ8Desc_t
    //   fields: 1
    class VMixEQ8Desc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVMixDynamicsProcessorDesc
    //   fields: 0
    class CVMixDynamicsProcessorDesc {
    public:
    };

    // CVMixGraphDescData
    //   fields: 1
    class CVMixGraphDescData {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVoiceContainerLoopXFade
    //   fields: 0
    class CVoiceContainerLoopXFade {
    public:
    };

    // VMixPresetDSPDesc_t
    //   fields: 1
    class VMixPresetDSPDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CAudioPhonemeTag
    //   fields: 1
    class CAudioPhonemeTag {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVMixControlInputArray
    //   parent: soundsystem_lowlevel
    //   fields: 0
    class CVMixControlInputArray : public soundsystem_lowlevel {
    public:
    };

    // CVMixNameInput
    //   parent: soundsystem_lowlevel
    //   fields: 0
    class CVMixNameInput : public soundsystem_lowlevel {
    public:
    };

    // CSosGroupActionSoundeventCountSchema
    //   fields: 0
    class CSosGroupActionSoundeventCountSchema {
    public:
    };

    // CVoiceContainerEnvelopeAnalyzer
    //   fields: 0
    class CVoiceContainerEnvelopeAnalyzer {
    public:
    };

    // CVMixBaseProcessorDesc
    //   fields: 0
    class CVMixBaseProcessorDesc {
    public:
    };

    // CVMixImpulseResponseInput
    //   parent: soundsystem_lowlevel
    //   fields: 0
    class CVMixImpulseResponseInput : public soundsystem_lowlevel {
    public:
    };

    // CVMixSteamAudioHybridReverbProcessorDesc
    //   fields: 0
    class CVMixSteamAudioHybridReverbProcessorDesc {
    public:
    };

    // CSoundEventMetaData
    //   fields: 1
    class CSoundEventMetaData {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // VMixPitchShiftDesc_t
    //   fields: 1
    class VMixPitchShiftDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVMixControlOutput
    //   fields: 0
    class CVMixControlOutput {
    public:
    };

    // CVMixModDelayProcessorDesc
    //   fields: 0
    class CVMixModDelayProcessorDesc {
    public:
    };

    // CVMixShaperProcessorDesc
    //   parent: `B?e�
    //   fields: 0
    class CVMixShaperProcessorDesc : public anonymous {
    public:
    };

    // CVMixAutomaticControlInput
    //   fields: 1
    class CVMixAutomaticControlInput {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CAudioEmphasisSample
    //   fields: 1
    class CAudioEmphasisSample {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVMixOscProcessorDesc
    //   parent: `B?e�
    //   fields: 0
    class CVMixOscProcessorDesc : public anonymous {
    public:
    };

    // CVMixCurveHeader
    //   fields: 1
    class CVMixCurveHeader {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVoiceContainerGenerator
    //   parent: soundsystem_voicecontainers
    //   fields: 0
    class CVoiceContainerGenerator : public soundsystem_voicecontainers {
    public:
    };

    // CVoiceContainerSet
    //   fields: 0
    class CVoiceContainerSet {
    public:
    };

    // VMixConvolutionDesc_t
    //   fields: 1
    class VMixConvolutionDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVoiceContainerSetElement
    //   fields: 1
    class CVoiceContainerSetElement {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVoiceContainerAsyncGenerator
    //   parent: soundsystem_voicecontainers
    //   fields: 0
    class CVoiceContainerAsyncGenerator : public soundsystem_voicecontainers {
    public:
    };

    // CSoundInfoHeader
    //   fields: 1
    class CSoundInfoHeader {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x100) // 
    };

    // SosEditItemInfo_t
    //   fields: 1
    class SosEditItemInfo_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVMixFlangerProcessorDesc
    //   parent: soundsystem_lowlevel
    //   fields: 0
    class CVMixFlangerProcessorDesc : public soundsystem_lowlevel {
    public:
    };

    // CVMixEffectChainProcessorDesc
    //   parent: soundsystem_lowlevel
    //   fields: 0
    class CVMixEffectChainProcessorDesc : public soundsystem_lowlevel {
    public:
    };

    // KeyGroup_t
    //   fields: 0
    class KeyGroup_t {
    public:
    };

    // CVMixFreeverbProcessorDesc
    //   fields: 0
    class CVMixFreeverbProcessorDesc {
    public:
    };

    // VMixPlateverbDesc_t
    //   fields: 1
    class VMixPlateverbDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVMixConvolutionProcessorDesc
    //   parent: soundsystem_lowlevel
    //   fields: 0
    class CVMixConvolutionProcessorDesc : public soundsystem_lowlevel {
    public:
    };

    // CSoundContainerReferenceArray
    //   fields: 1
    class CSoundContainerReferenceArray {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVMixFilterProcessorDesc
    //   parent: `B?e�
    //   fields: 0
    class CVMixFilterProcessorDesc : public anonymous {
    public:
    };

    // CVMixAdditionalOutput
    //   fields: 1
    class CVMixAdditionalOutput {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVoiceContainerTapePlayer
    //   fields: 0
    class CVoiceContainerTapePlayer {
    public:
    };

    // CVMixSubgraphSwitchProcessorDesc
    //   parent: `B?e�
    //   fields: 0
    class CVMixSubgraphSwitchProcessorDesc : public anonymous {
    public:
    };

    // VMixDiffusorDesc_t
    //   fields: 1
    class VMixDiffusorDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVMixSteamAudioPathingProcessorDesc
    //   fields: 0
    class CVMixSteamAudioPathingProcessorDesc {
    public:
    };

    // CVMixPannerProcessorDesc
    //   parent: soundsystem_lowlevel
    //   fields: 0
    class CVMixPannerProcessorDesc : public soundsystem_lowlevel {
    public:
    };

    // VMixDynamicsCompressorDesc_t
    //   fields: 1
    class VMixDynamicsCompressorDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVMixStereoDelayProcessorDesc
    //   fields: 0
    class CVMixStereoDelayProcessorDesc {
    public:
    };

    // VMixShaperDesc_t
    //   fields: 1
    class VMixShaperDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // VMixEnvelopeDesc_t
    //   fields: 1
    class VMixEnvelopeDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CAudioSentence
    //   fields: 1
    class CAudioSentence {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVoiceContainerParameterBlender
    //   fields: 0
    class CVoiceContainerParameterBlender {
    public:
    };

    // CVMixAudioMeter
    //   fields: 1
    class CVMixAudioMeter {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVMixVocoderProcessorDesc
    //   parent: soundsystem_lowlevel
    //   fields: 0
    class CVMixVocoderProcessorDesc : public soundsystem_lowlevel {
    public:
    };

    // CSosGroupActionLimitSchema
    //   fields: 0
    class CSosGroupActionLimitSchema {
    public:
    };

    // CVoiceContainerAmpedDecayingSineWave
    //   parent: soundsystem_voicecontainers
    //   fields: 0
    class CVoiceContainerAmpedDecayingSineWave : public soundsystem_voicecontainers {
    public:
    };

    // CVoiceContainerEnvelope
    //   fields: 0
    class CVoiceContainerEnvelope {
    public:
    };

    // VMixAutoFilterDesc_t
    //   fields: 1
    class VMixAutoFilterDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // VMixDynamicsBand_t
    //   fields: 1
    class VMixDynamicsBand_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // VMixEffectChainDesc_t
    //   fields: 1
    class VMixEffectChainDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVMixPlateReverbProcessorDesc
    //   parent: `B?e�
    //   fields: 0
    class CVMixPlateReverbProcessorDesc : public anonymous {
    public:
    };

    // CVoiceContainerMultiBlender
    //   fields: 0
    class CVoiceContainerMultiBlender {
    public:
    };

    // CVMixVsndInput
    //   fields: 0
    class CVMixVsndInput {
    public:
    };

    // CVoiceContainerStaticAdditiveSynth::CGainScalePerInstance
    //   fields: 1
    class CVoiceContainerStaticAdditiveSynth {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // VelocityZone_t
    //   fields: 0
    class VelocityZone_t {
    public:
    };

    // CVoiceContainerSelector
    //   fields: 0
    class CVoiceContainerSelector {
    public:
    };

    // CSosGroupActionTimeBlockLimitSchema
    //   fields: 0
    class CSosGroupActionTimeBlockLimitSchema {
    public:
    };

    // CSosGroupActionMemberCountEnvelopeSchema
    //   fields: 0
    class CSosGroupActionMemberCountEnvelopeSchema {
    public:
    };

    // CVMixDualCompressorProcessorDesc
    //   fields: 0
    class CVMixDualCompressorProcessorDesc {
    public:
    };

    // CVoiceContainerSwitch
    //   fields: 0
    class CVoiceContainerSwitch {
    public:
    };

    // CVMixControlMeter
    //   parent: soundsystem_lowlevel
    //   fields: 0
    class CVMixControlMeter : public soundsystem_lowlevel {
    public:
    };

    // CVoiceContainerEnum
    //   fields: 0
    class CVoiceContainerEnum {
    public:
    };

    // CSosGroupActionTimeLimitSchema
    //   fields: 0
    class CSosGroupActionTimeLimitSchema {
    public:
    };

    // VMixVocoderDesc_t
    //   fields: 1
    class VMixVocoderDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // VMixUtilityDesc_t
    //   fields: 1
    class VMixUtilityDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVoiceContainerLoopTrigger
    //   fields: 0
    class CVoiceContainerLoopTrigger {
    public:
    };

    // CVoiceContainerDecayingSineWave
    //   fields: 0
    class CVoiceContainerDecayingSineWave {
    public:
    };

    // CVMixDelayProcessorDesc
    //   parent: xL��
    //   fields: 0
    class CVMixDelayProcessorDesc : public xL {
    public:
    };

    // CVMixBoxverb2ProcessorDesc
    //   fields: 0
    class CVMixBoxverb2ProcessorDesc {
    public:
    };

    // VMixFilterDesc_t
    //   fields: 1
    class VMixFilterDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // VMixOscDesc_t
    //   fields: 1
    class VMixOscDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVMixAutoFilterProcessorDesc
    //   parent: MGetKV3ClassDefaults
    //   fields: 0
    class CVMixAutoFilterProcessorDesc : public MGetKV3ClassDefaults {
    public:
    };

    // ISndSeqInstruments
    //   fields: 0
    class ISndSeqInstruments {
    public:
    };

    // VMixFlangerDesc_t
    //   fields: 1
    class VMixFlangerDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // VMixDynamicsDesc_t
    //   fields: 1
    class VMixDynamicsDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

} // namespace cs2::sdk::soundsystem
