// Auto-generated by cs2-universal-dumper. Do not edit.
//
// module:        vphysics2.dll
// classes:       110
// enums:         5
// build_number:  14152
// generated_at:  2026-04-21T22:41:52.146505500+00:00
//
// Use:
//   auto* pawn = reinterpret_cast<C_CSPlayerPawn*>(addr);
//   pawn->m_iHealth() = 100;

#pragma once
#include "cs2sdk_macros.hpp"

namespace cs2::sdk::vphysics2 {

    inline constexpr std::uint32_t CS2_BUILD = 14152;

    class RnSphereDesc_t;
    class RnSoftbodyParticle_t;
    class RnHullDesc_t;
    class RnCapsuleDesc_t;
    class PhysFeModelDesc_t;
    class RnMeshDesc_t;
    class RnSoftbodySpring_t;
    class RnSoftbodyCapsule_t;
    class vphysics_save_cphysicsbody_t;
    class FeBuildBoxRigid_t;
    class CFeIndexedJiggleBone;
    class IPhysAggregateInstance;
    class FeBandBendLimit_t;
    class FeTaperedCapsuleStretch_t;
    class constraint_axislimit_t;
    class FeSimdRodConstraintAnim_t;
    class FeSimdRodConstraint_t;
    class IPhysicsParticleRope;
    class constraint_hingeparams_t;
    class IPhysicsBodyList;
    class FeBuildSphereRigid_t;
    class FeSimdAnimStrayRadius_t;
    class RnTriangle_t;
    class FeProxyVertexMap_t;
    class FeNodeIntegrator_t;
    class RnCapsule_t;
    class CFeNamedJiggleBone;
    class FeAntiTunnelProbeBuild_t;
    class RnBodyDesc_t;
    class OldFeEdge_t;
    class FeFollowNode_t;
    class RnMesh_t;
    class VertexPositionNormal_t;
    class IPhysicsRagdollControl;
    class FeBuildSDFRigid_t;
    class RnBlendVertex_t;
    class CFeMorphLayer;
    class FeCtrlSoftOffset_t;
    class FeVertexMapDesc_t;
    class FeTaperedCapsuleRigid_t;
    class FeAnimStrayRadius_t;
    class IPhysicsJoint;
    class FeEdgeDesc_t;
    class FeNodeStrayBox_t;
    class FeNodeReverseOffset_t;
    class RnPlane_t;
    class FeSDFRigid_t;
    class CFeJiggleBone;
    class CRegionSVM;
    class FeWorldCollisionParams_t;
    class CGenericShapeProxy;
    class RnNode_t;
    class FeFitMatrix_t;
    class FeSimdQuad_t;
    class FeSimdSpringIntegrator_t;
    class FeSimdNodeBase_t;
    class FeQuad_t;
    class FeHingeLimit_t;
    class RnWing_t;
    class FeWeightedNode_t;
    class CollisionDetailLayerInfo_t;
    class FeEffectDesc_t;
    class FeSpringIntegrator_t;
    class FourVectors2D;
    class FeKelagerBend2_t;
    class CastSphereSATParams_t;
    class vphysics_save_ragdoll_control_t;
    class FeRigidColliderIndices_t;
    class FeCollisionPlane_t;
    class FeStiffHingeBuild_t;
    class FeBoxRigid_t;
    class FeMorphLayerDepr_t;
    class FeCtrlOffset_t;
    class IPhysicsPlayerController;
    class FeNodeBase_t;
    class FeVertexMapBuild_t;
    class CFeVertexMapBuildArray;
    class FeTri_t;
    class RnHull_t;
    class FeModelSelfCollisionLayer_t;
    class FeAntiTunnelGroupBuild_t;
    class CovMatrix3;
    class PhysicsParticleId_t;
    class RnVertex_t;
    class IPhysicsMotionController;
    class Dop26_t;
    class FeDynKinLink_t;
    class RnFace_t;
    class FeCtrlOsOffset_t;
    class FeAntiTunnelProbe_t;
    class FeSourceEdge_t;
    class FeTwistConstraint_t;
    class FeNodeWindBase_t;
    class FeAxialEdgeBend_t;
    class FourCovMatrices3;
    class constraint_breakableparams_t;
    class FeSphereRigid_t;
    class CollisionDetailLayerInfo_t;
    class FeBuildTaperedCapsuleRigid_t;
    class IPhysicsBody;
    class FeSoftParent_t;
    class RnShapeDesc_t;
    class FeTreeChildren_t;
    class FeRodConstraint_t;
    class FeFitWeight_t;
    class RnHalfEdge_t;
    class FeSimdTri_t;
    class VertexPositionColor_t;
    class FeFitInfluence_t;
    class FeHingeLimitBuild_t;

    enum class JointMotion_t : std::uint32_t {
        JOINT_MOTION_FREE = 0x0,
        JOINT_MOTION_LOCKED = 0x1,
        JOINT_MOTION_COUNT = 0x2,
    };

    enum class JointAxis_t : std::uint32_t {
        JOINT_AXIS_X = 0x0,
        JOINT_AXIS_Y = 0x1,
        JOINT_AXIS_Z = 0x2,
        JOINT_AXIS_COUNT = 0x3,
    };

    enum class DynamicContinuousContactBehavior_t : std::uint8_t {
        DYNAMIC_CONTINUOUS_ALLOW_IF_REQUESTED_BY_OTHER_BODY = 0x0,
        DYNAMIC_CONTINUOUS_ALWAYS = 0x1,
        DYNAMIC_CONTINUOUS_NEVER = 0x2,
    };

    enum class PhysInterfaceId_t : std::uint32_t {
        PIID_UNKNOWN = 0x0,
        PIID_IPHYSICSBODY = 0x1,
        PIID_IPHYSAGGREGATE = 0x2,
        PIID_IPHYSICSJOINT = 0x3,
        PIID_IPHYSICSMOTIONCONTROLLER = 0x4,
        PIID_IPHYSICSPARTICLEROPE = 0x5,
        PIID_IPHYSICSRAGDOLLCONTROL = 0x6,
        PIID_NUM_TYPES = 0x7,
    };

    enum class PhysGenericShapeType_t : std::uint8_t {
        GENERIC_SHAPE_POINT = 0x0,
        GENERIC_SHAPE_SPHERE = 0x1,
        GENERIC_SHAPE_AABB = 0x2,
        GENERIC_SHAPE_CAPSULE = 0x3,
        GENERIC_SHAPE_HULL = 0x4,
    };

    // RnSphereDesc_t
    //   parent: physicslib
    //   fields: 0
    class RnSphereDesc_t : public physicslib {
    public:
    };

    // RnSoftbodyParticle_t
    //   fields: 1
    class RnSoftbodyParticle_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // RnHullDesc_t
    //   parent: physicslib
    //   fields: 0
    class RnHullDesc_t : public physicslib {
    public:
    };

    // RnCapsuleDesc_t
    //   parent: physicslib
    //   fields: 0
    class RnCapsuleDesc_t : public physicslib {
    public:
    };

    // PhysFeModelDesc_t
    //   fields: 1
    class PhysFeModelDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // RnMeshDesc_t
    //   parent: physicslib
    //   fields: 0
    class RnMeshDesc_t : public physicslib {
    public:
    };

    // RnSoftbodySpring_t
    //   fields: 1
    class RnSoftbodySpring_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // RnSoftbodyCapsule_t
    //   fields: 1
    class RnSoftbodyCapsule_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // vphysics_save_cphysicsbody_t
    //   parent: xL��
    //   fields: 0
    class vphysics_save_cphysicsbody_t : public xL {
    public:
    };

    // FeBuildBoxRigid_t
    //   fields: 0
    class FeBuildBoxRigid_t {
    public:
    };

    // CFeIndexedJiggleBone
    //   fields: 1
    class CFeIndexedJiggleBone {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // IPhysAggregateInstance
    //   parent: xL��
    //   fields: 0
    class IPhysAggregateInstance : public xL {
    public:
    };

    // FeBandBendLimit_t
    //   fields: 1
    class FeBandBendLimit_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeTaperedCapsuleStretch_t
    //   fields: 1
    class FeTaperedCapsuleStretch_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // constraint_axislimit_t
    //   fields: 0
    class constraint_axislimit_t {
    public:
    };

    // FeSimdRodConstraintAnim_t
    //   fields: 0
    class FeSimdRodConstraintAnim_t {
    public:
    };

    // FeSimdRodConstraint_t
    //   fields: 0
    class FeSimdRodConstraint_t {
    public:
    };

    // IPhysicsParticleRope
    //   fields: 0
    class IPhysicsParticleRope {
    public:
    };

    // constraint_hingeparams_t
    //   fields: 0
    class constraint_hingeparams_t {
    public:
    };

    // IPhysicsBodyList
    //   fields: 0
    class IPhysicsBodyList {
    public:
    };

    // FeBuildSphereRigid_t
    //   fields: 0
    class FeBuildSphereRigid_t {
    public:
    };

    // FeSimdAnimStrayRadius_t
    //   fields: 0
    class FeSimdAnimStrayRadius_t {
    public:
    };

    // RnTriangle_t
    //   fields: 1
    class RnTriangle_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeProxyVertexMap_t
    //   fields: 1
    class FeProxyVertexMap_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeNodeIntegrator_t
    //   fields: 1
    class FeNodeIntegrator_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // RnCapsule_t
    //   fields: 1
    class RnCapsule_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CFeNamedJiggleBone
    //   fields: 0
    class CFeNamedJiggleBone {
    public:
    };

    // FeAntiTunnelProbeBuild_t
    //   fields: 1
    class FeAntiTunnelProbeBuild_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // RnBodyDesc_t
    //   fields: 1
    class RnBodyDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // OldFeEdge_t
    //   fields: 1
    class OldFeEdge_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeFollowNode_t
    //   fields: 1
    class FeFollowNode_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // RnMesh_t
    //   fields: 1
    class RnMesh_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // VertexPositionNormal_t
    //   fields: 0
    class VertexPositionNormal_t {
    public:
    };

    // IPhysicsRagdollControl
    //   fields: 0
    class IPhysicsRagdollControl {
    public:
    };

    // FeBuildSDFRigid_t
    //   fields: 0
    class FeBuildSDFRigid_t {
    public:
    };

    // RnBlendVertex_t
    //   fields: 0
    class RnBlendVertex_t {
    public:
    };

    // CFeMorphLayer
    //   fields: 1
    class CFeMorphLayer {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeCtrlSoftOffset_t
    //   fields: 1
    class FeCtrlSoftOffset_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeVertexMapDesc_t
    //   fields: 1
    class FeVertexMapDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeTaperedCapsuleRigid_t
    //   fields: 0
    class FeTaperedCapsuleRigid_t {
    public:
    };

    // FeAnimStrayRadius_t
    //   fields: 1
    class FeAnimStrayRadius_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // IPhysicsJoint
    //   fields: 0
    class IPhysicsJoint {
    public:
    };

    // FeEdgeDesc_t
    //   fields: 1
    class FeEdgeDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x1) // 
    };

    // FeNodeStrayBox_t
    //   fields: 0
    class FeNodeStrayBox_t {
    public:
    };

    // FeNodeReverseOffset_t
    //   fields: 1
    class FeNodeReverseOffset_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // RnPlane_t
    //   fields: 1
    class RnPlane_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeSDFRigid_t
    //   fields: 1
    class FeSDFRigid_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CFeJiggleBone
    //   fields: 1
    class CFeJiggleBone {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CRegionSVM
    //   fields: 1
    class CRegionSVM {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeWorldCollisionParams_t
    //   fields: 1
    class FeWorldCollisionParams_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CGenericShapeProxy
    //   fields: 0
    class CGenericShapeProxy {
    public:
    };

    // RnNode_t
    //   fields: 0
    class RnNode_t {
    public:
    };

    // FeFitMatrix_t
    //   fields: 0
    class FeFitMatrix_t {
    public:
    };

    // FeSimdQuad_t
    //   fields: 0
    class FeSimdQuad_t {
    public:
    };

    // FeSimdSpringIntegrator_t
    //   fields: 0
    class FeSimdSpringIntegrator_t {
    public:
    };

    // FeSimdNodeBase_t
    //   fields: 0
    class FeSimdNodeBase_t {
    public:
    };

    // FeQuad_t
    //   fields: 1
    class FeQuad_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeHingeLimit_t
    //   fields: 1
    class FeHingeLimit_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // RnWing_t
    //   fields: 1
    class RnWing_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeWeightedNode_t
    //   fields: 1
    class FeWeightedNode_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x1) // 
    };

    // CollisionDetailLayerInfo_t
    //   fields: 1
    class CollisionDetailLayerInfo_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeEffectDesc_t
    //   fields: 1
    class FeEffectDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeSpringIntegrator_t
    //   fields: 1
    class FeSpringIntegrator_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FourVectors2D
    //   fields: 0
    class FourVectors2D {
    public:
    };

    // FeKelagerBend2_t
    //   fields: 1
    class FeKelagerBend2_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CastSphereSATParams_t
    //   fields: 1
    class CastSphereSATParams_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // vphysics_save_ragdoll_control_t
    //   fields: 1
    class vphysics_save_ragdoll_control_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeRigidColliderIndices_t
    //   fields: 1
    class FeRigidColliderIndices_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x1) // 
    };

    // FeCollisionPlane_t
    //   fields: 1
    class FeCollisionPlane_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeStiffHingeBuild_t
    //   fields: 1
    class FeStiffHingeBuild_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeBoxRigid_t
    //   fields: 0
    class FeBoxRigid_t {
    public:
    };

    // FeMorphLayerDepr_t
    //   fields: 1
    class FeMorphLayerDepr_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeCtrlOffset_t
    //   fields: 1
    class FeCtrlOffset_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // IPhysicsPlayerController
    //   fields: 0
    class IPhysicsPlayerController {
    public:
    };

    // FeNodeBase_t
    //   fields: 0
    class FeNodeBase_t {
    public:
    };

    // FeVertexMapBuild_t
    //   fields: 1
    class FeVertexMapBuild_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CFeVertexMapBuildArray
    //   fields: 1
    class CFeVertexMapBuildArray {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeTri_t
    //   fields: 1
    class FeTri_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // RnHull_t
    //   fields: 1
    class RnHull_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeModelSelfCollisionLayer_t
    //   fields: 1
    class FeModelSelfCollisionLayer_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeAntiTunnelGroupBuild_t
    //   fields: 1
    class FeAntiTunnelGroupBuild_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CovMatrix3
    //   fields: 1
    class CovMatrix3 {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // PhysicsParticleId_t
    //   fields: 0
    class PhysicsParticleId_t {
    public:
    };

    // RnVertex_t
    //   fields: 1
    class RnVertex_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x100) // 
    };

    // IPhysicsMotionController
    //   fields: 0
    class IPhysicsMotionController {
    public:
    };

    // Dop26_t
    //   fields: 1
    class Dop26_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeDynKinLink_t
    //   fields: 1
    class FeDynKinLink_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x1) // 
    };

    // RnFace_t
    //   fields: 1
    class RnFace_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x100) // 
    };

    // FeCtrlOsOffset_t
    //   fields: 1
    class FeCtrlOsOffset_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeAntiTunnelProbe_t
    //   fields: 1
    class FeAntiTunnelProbe_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeSourceEdge_t
    //   fields: 1
    class FeSourceEdge_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x1) // 
    };

    // FeTwistConstraint_t
    //   fields: 1
    class FeTwistConstraint_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeNodeWindBase_t
    //   fields: 1
    class FeNodeWindBase_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x1) // 
    };

    // FeAxialEdgeBend_t
    //   fields: 1
    class FeAxialEdgeBend_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FourCovMatrices3
    //   fields: 0
    class FourCovMatrices3 {
    public:
    };

    // constraint_breakableparams_t
    //   fields: 0
    class constraint_breakableparams_t {
    public:
    };

    // FeSphereRigid_t
    //   fields: 0
    class FeSphereRigid_t {
    public:
    };

    // CollisionDetailLayerInfo_t::Name_t
    //   fields: 1
    class CollisionDetailLayerInfo_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeBuildTaperedCapsuleRigid_t
    //   fields: 0
    class FeBuildTaperedCapsuleRigid_t {
    public:
    };

    // IPhysicsBody
    //   fields: 0
    class IPhysicsBody {
    public:
    };

    // FeSoftParent_t
    //   fields: 1
    class FeSoftParent_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // RnShapeDesc_t
    //   fields: 1
    class RnShapeDesc_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeTreeChildren_t
    //   fields: 1
    class FeTreeChildren_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x1) // 
    };

    // FeRodConstraint_t
    //   fields: 1
    class FeRodConstraint_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeFitWeight_t
    //   fields: 1
    class FeFitWeight_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // RnHalfEdge_t
    //   fields: 1
    class RnHalfEdge_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x100) // 
    };

    // FeSimdTri_t
    //   fields: 0
    class FeSimdTri_t {
    public:
    };

    // VertexPositionColor_t
    //   fields: 0
    class VertexPositionColor_t {
    public:
    };

    // FeFitInfluence_t
    //   fields: 1
    class FeFitInfluence_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // FeHingeLimitBuild_t
    //   fields: 1
    class FeHingeLimitBuild_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

} // namespace cs2::sdk::vphysics2
