// Auto-generated by cs2-universal-dumper. Do not edit.
//
// module:        worldrenderer.dll
// classes:       32
// enums:         3
// build_number:  14152
// generated_at:  2026-04-21T22:47:42.668580400+00:00
//
// Use:
//   auto* pawn = reinterpret_cast<C_CSPlayerPawn*>(addr);
//   pawn->m_iHealth() = 100;

#pragma once
#include "cs2sdk_macros.hpp"

namespace cs2::sdk::worldrenderer {

    inline constexpr std::uint32_t CS2_BUILD = 14152;

    class CEntityInstance;
    class CEntityComponent;
    class CScriptComponent;
    class CEntityIdentity;
    class RTProxyInstanceInfo_t;
    class AggregateVertexAlbedoStreamOnDiskData_t;
    class SceneObject_t;
    class AggregateLODSetup_t;
    class ExtraVertexStreamOverride_t;
    class ClutterTile_t;
    class AggregateSceneObject_t;
    class NodeData_t;
    class VMapResourceData_t;
    class AggregateInstanceStreamOnDiskData_t;
    class RTProxyBLAS_t;
    class ClutterSceneObject_t;
    class WorldBuilderParams_t;
    class PermEntityLumpData_t;
    class WorldNode_t;
    class BaseSceneObjectOverride_t;
    class EntityIOConnectionData_t;
    class BakedLightingInfo_t;
    class VoxelVisBlockOffset_t;
    class InfoForResourceTypeVMapResourceData_t;
    class WorldNodeOnDiskBufferData_t;
    class AggregateMeshInfo_t;
    class World_t;
    class BakedLightingInfo_t;
    class MaterialOverride_t;
    class AggregateRTProxySceneObject_t;
    class EntityKeyValueData_t;
    class CVoxelVisibility;

    enum class RTProxyInstanceFlags_t : std::uint8_t {
        RTPROXY_INSTANCE_FLAG_NONE = 0x0,
        RTPROXY_INSTANCE_UNIQUE_MESH = 0x1,
    };

    enum class ObjectTypeFlags_t : std::uint32_t {
        OBJECT_TYPE_NONE = 0x0,
        OBJECT_TYPE_MODEL = 0x8,
        OBJECT_TYPE_BLOCK_LIGHT = 0x10,
        OBJECT_TYPE_NO_SHADOWS = 0x20,
        OBJECT_TYPE_WORLDSPACE_TEXURE_BLEND = 0x40,
        OBJECT_TYPE_DISABLED_IN_LOW_QUALITY = 0x80,
        OBJECT_TYPE_RENDER_WITH_DYNAMIC = 0x200,
        OBJECT_TYPE_RENDER_TO_CUBEMAPS = 0x400,
        OBJECT_TYPE_MODEL_HAS_LODS = 0x800,
        OBJECT_TYPE_OVERLAY = 0x2000,
        OBJECT_TYPE_PRECOMPUTED_VISMEMBERS = 0x4000,
        OBJECT_TYPE_STATIC_CUBE_MAP = 0x8000,
        OBJECT_TYPE_DISABLE_VIS_CULLING = 0x10000,
        OBJECT_TYPE_BAKED_GEOMETRY = 0x20000,
        OBJECT_TYPE_NEEDS_DYNAMIC_SHADOWS = 0x40000,
        OBJECT_TYPE_HAS_AGGREGATE_RTPROXY = 0x80000,
    };

    enum class AggregateInstanceStream_t : std::uint8_t {
        AGGREGATE_INSTANCE_STREAM_NONE = 0x0,
        AGGREGATE_INSTANCE_STREAM_LIGHTMAPUV_UNORM16 = 0x1,
        AGGREGATE_INSTANCE_STREAM_VERTEXTINT_UNORM8 = 0x2,
        AGGREGATE_INSTANCE_STREAM_VERTEXBLEND_UNORM8 = 0x4,
    };

    // CEntityInstance
    //   fields: 0
    class CEntityInstance {
    public:
    };

    // CEntityComponent
    //   fields: 0
    class CEntityComponent {
    public:
    };

    // CScriptComponent
    //   fields: 0
    class CScriptComponent {
    public:
    };

    // CEntityIdentity
    //   fields: 0
    class CEntityIdentity {
    public:
    };

    // RTProxyInstanceInfo_t
    //   fields: 1
    class RTProxyInstanceInfo_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // AggregateVertexAlbedoStreamOnDiskData_t
    //   fields: 1
    class AggregateVertexAlbedoStreamOnDiskData_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // SceneObject_t
    //   fields: 1
    class SceneObject_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // AggregateLODSetup_t
    //   fields: 1
    class AggregateLODSetup_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // ExtraVertexStreamOverride_t
    //   parent: xL��
    //   fields: 0
    class ExtraVertexStreamOverride_t : public xL {
    public:
    };

    // ClutterTile_t
    //   fields: 1
    class ClutterTile_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // AggregateSceneObject_t
    //   fields: 1
    class AggregateSceneObject_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // NodeData_t
    //   fields: 1
    class NodeData_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // VMapResourceData_t
    //   fields: 0
    class VMapResourceData_t {
    public:
    };

    // AggregateInstanceStreamOnDiskData_t
    //   fields: 1
    class AggregateInstanceStreamOnDiskData_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // RTProxyBLAS_t
    //   fields: 1
    class RTProxyBLAS_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // ClutterSceneObject_t
    //   fields: 1
    class ClutterSceneObject_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // WorldBuilderParams_t
    //   fields: 1
    class WorldBuilderParams_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // PermEntityLumpData_t
    //   fields: 1
    class PermEntityLumpData_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // WorldNode_t
    //   fields: 1
    class WorldNode_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // BaseSceneObjectOverride_t
    //   fields: 1
    class BaseSceneObjectOverride_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // EntityIOConnectionData_t
    //   fields: 1
    class EntityIOConnectionData_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // BakedLightingInfo_t
    //   fields: 1
    class BakedLightingInfo_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // VoxelVisBlockOffset_t
    //   fields: 1
    class VoxelVisBlockOffset_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // InfoForResourceTypeVMapResourceData_t
    //   fields: 0
    class InfoForResourceTypeVMapResourceData_t {
    public:
    };

    // WorldNodeOnDiskBufferData_t
    //   fields: 1
    class WorldNodeOnDiskBufferData_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // AggregateMeshInfo_t
    //   fields: 1
    class AggregateMeshInfo_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // World_t
    //   fields: 1
    class World_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // BakedLightingInfo_t::BakedShadowAssignment_t
    //   fields: 1
    class BakedLightingInfo_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // MaterialOverride_t
    //   parent: xL��
    //   fields: 0
    class MaterialOverride_t : public xL {
    public:
    };

    // AggregateRTProxySceneObject_t
    //   fields: 1
    class AggregateRTProxySceneObject_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // EntityKeyValueData_t
    //   fields: 1
    class EntityKeyValueData_t {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

    // CVoxelVisibility
    //   fields: 1
    class CVoxelVisibility {
    public:
        SCHEMA_FIELD(                                ,                                                 , 0x0) // 
    };

} // namespace cs2::sdk::worldrenderer
